import type {jsPDF as JsPDFType} from "jspdf";
import {user} from "@/data/mock-data";
import {formatDPRDate} from "@/lib/dpr";
import {buildDPRReportData,workProgress} from "@/lib/dpr-report";
import {getPhotoBlob,isStoredPhoto} from "@/lib/photo-store";
import type {DPR,Project} from "@/types";

export type GeneratedDPRPdf={blob:Blob;file:File;filename:string;size:number};
type Doc=JsPDFType;
type Row=Array<string|number>;
const page={width:210,height:297,left:14,right:14,top:14,bottom:15};
const contentWidth=page.width-page.left-page.right;

export function dprPdfFilename(project:Project,dpr:DPR){const projectName=project.name.normalize("NFKD").replace(/[^a-zA-Z0-9]+/g,"-").replace(/^-+|-+$/g,"")||"Project";return `DPR-${projectName}-${dpr.date}.pdf`}

export async function generateDPRPdf(dpr:DPR,project:Project):Promise<GeneratedDPRPdf>{
 if(dpr.status!=="submitted")throw new Error("Only submitted DPRs can be exported");
 const{jsPDF}=await import("jspdf");const doc=new jsPDF({orientation:"portrait",unit:"mm",format:"a4",compress:true});const report=buildDPRReportData(dpr,project);let y=page.top;
 const ensure=(height:number)=>{if(y+height<=page.height-page.bottom)return;doc.addPage();y=page.top};
 const text=(value:string,x:number,size=9,style:"normal"|"bold"="normal",maxWidth=contentWidth)=>{doc.setFont("helvetica",style);doc.setFontSize(size);doc.setTextColor(35,38,45);const lines=doc.splitTextToSize(value,maxWidth) as string[];ensure(lines.length*(size*.38)+2);doc.text(lines,x,y);y+=lines.length*(size*.38)+2};
 const rule=()=>{doc.setDrawColor(190,195,203);doc.line(page.left,y,page.width-page.right,y);y+=5};
 const heading=(number:string,title:string)=>{ensure(12);rule();doc.setFont("helvetica","bold");doc.setFontSize(11);doc.setTextColor(221,77,72);doc.text(number,page.left,y);doc.setTextColor(35,38,45);doc.text(title.toUpperCase(),page.left+11,y);y+=7};
 const table=(headers:string[],rows:Row[],widths:number[],footer?:Row)=>{const drawRow=(row:Row,header=false,bold=false)=>{const cells=row.map((cell,index)=>doc.splitTextToSize(String(cell),widths[index]-4) as string[]);const height=Math.max(...cells.map(lines=>lines.length))*4+4;ensure(height);let x=page.left;doc.setFillColor(header?241:255,header?243:255,header?246:255);if(header)doc.rect(page.left,y,contentWidth,height,"F");doc.setDrawColor(222,225,230);doc.line(page.left,y+height,page.width-page.right,y+height);cells.forEach((lines,index)=>{doc.setFont("helvetica",header||bold?"bold":"normal");doc.setFontSize(header?7:8);doc.setTextColor(header?95:35,header?101:38,header?112:45);doc.text(lines,x+2,y+4);x+=widths[index]});y+=height};drawRow(headers,true);rows.forEach(row=>drawRow(row));if(footer){doc.setDrawColor(52,56,65);doc.line(page.left,y,page.width-page.right,y);drawRow(footer,false,true)}y+=4};

 doc.setFont("helvetica","bold");doc.setFontSize(8);doc.setTextColor(221,77,72);doc.text("DIGITAL DPR",page.left,y);y+=7;doc.setFontSize(21);doc.setTextColor(30,33,40);doc.text("DAILY PROGRESS REPORT",page.left,y);y+=10;doc.setFontSize(14);doc.text(project.name,page.left,y);y+=6;doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(100,106,118);doc.text(project.workType,page.left,y);doc.setFillColor(235,247,241);doc.setTextColor(38,126,94);doc.roundedRect(page.width-page.right-30,page.top,30,9,1.5,1.5,"F");doc.setFont("helvetica","bold");doc.setFontSize(7);doc.text("SUBMITTED",page.width-page.right-15,page.top+5.8,{align:"center"});y+=8;rule();
 const submitted=formatTimestamp(dpr.updatedAt);const meta=[["DPR DATE",formatDPRDate(dpr.date)],["PREPARED BY",user.name],["STATUS","Submitted"],["SUBMITTED",submitted]];let metaX=page.left;for(const[label,value]of meta){doc.setFont("helvetica","bold");doc.setFontSize(6.5);doc.setTextColor(116,122,133);doc.text(label,metaX,y);doc.setFontSize(8);doc.setTextColor(35,38,45);doc.text(doc.splitTextToSize(value,40) as string[],metaX,y+4);metaX+=45.5}y+=15;
 text("SUMMARY",page.left,8,"bold");const metricWidth=contentWidth/report.summary.length;let metricX=page.left;for(const item of report.summary){doc.setDrawColor(222,225,230);doc.rect(metricX,y,metricWidth,14);doc.setFont("helvetica","bold");doc.setFontSize(13);doc.setTextColor(35,38,45);doc.text(String(item.value),metricX+3,y+6);doc.setFontSize(6);doc.setTextColor(110,116,127);doc.text(item.label.toUpperCase(),metricX+3,y+11);metricX+=metricWidth}y+=20;

 heading("01","Work Done");table(["Activity","Location","Planned","Achieved","Progress"],dpr.work.map(row=>[`${row.activity}${row.remarks?`\n${row.remarks}`:""}`,row.location||"—",`${row.planned} ${row.unit}`,row.achieved===null?"—":`${row.achieved} ${row.unit}`,workProgress(row.planned,row.achieved)===null?"—":`${workProgress(row.planned,row.achieved)}%`]),[58,42,27,27,28]);
 heading("02","Manpower");table(["Trade / Role","In-house","Subcontractor","Total"],dpr.manpower.map(row=>[`${row.role}${row.subcontractorName?`\n${row.subcontractorName}`:""}`,row.inHouse,row.subcontractor,row.inHouse+row.subcontractor]),[83,30,39,30],["TOTAL",report.manpower.inHouse,report.manpower.subcontractor,report.manpower.total]);
 heading("03","Materials Used");table(["Material","Quantity","Remarks"],dpr.materials.map(row=>[row.material,`${row.quantity} ${row.unit}`,row.remarks||"—"]),[74,38,70]);
 heading("04","Site Photos");const photoWidth=(contentWidth-5)/2,photoHeight=49;for(let index=0;index<dpr.photos.length;index+=2){ensure(photoHeight+13);const pair=dpr.photos.slice(index,index+2);await Promise.all(pair.map(async(photo,pairIndex)=>{const x=page.left+pairIndex*(photoWidth+5);doc.setDrawColor(218,221,226);doc.rect(x,y,photoWidth,photoHeight+10);try{const image=await resolvePdfImage(photo.src);if(image)doc.addImage(image.data,"JPEG",x+2,y+2,photoWidth-4,photoHeight-4,undefined,"MEDIUM");else drawPhotoUnavailable(doc,x+2,y+2,photoWidth-4,photoHeight-4)}catch{drawPhotoUnavailable(doc,x+2,y+2,photoWidth-4,photoHeight-4)}doc.setFont("helvetica","bold");doc.setFontSize(6.5);doc.setTextColor(110,116,127);doc.text(`PHOTO ${String(index+pairIndex+1).padStart(2,"0")}`,x+2,y+photoHeight+3);const caption=photo.caption||photo.name;if(caption){doc.setFont("helvetica","normal");doc.setTextColor(35,38,45);doc.text(doc.splitTextToSize(caption,photoWidth-4) as string[],x+2,y+photoHeight+7)}}));y+=photoHeight+15}
 if(dpr.siteVisits.length){heading("05","Site Visit / Feedback");for(const visit of dpr.siteVisits){ensure(20);text(`${visit.visitorName}${visit.designation?` · ${visit.designation}`:""} · ${formatTime(visit.visitTime)}`,page.left,8,"bold");text(visit.feedback,page.left,8,"normal");if(visit.actionRequired)text("Action required",page.left,7,"bold");y+=2}}
 if(dpr.tomorrowPlan.length){heading("06","Tomorrow's Plan");table(["Activity","Target","Notes"],dpr.tomorrowPlan.map(row=>[row.activity,`${row.planned} ${row.unit}`,row.remarks||"—"]),[78,34,70])}
 if(dpr.generalRemarks.trim()){heading("","General Remarks");text(dpr.generalRemarks,page.left,8,"normal")}
 const totalPages=doc.getNumberOfPages();for(let number=1;number<=totalPages;number++){doc.setPage(number);doc.setDrawColor(190,195,203);doc.line(page.left,page.height-10,page.width-page.right,page.height-10);doc.setFont("helvetica","normal");doc.setFontSize(6.5);doc.setTextColor(110,116,127);doc.text(`Digital DPR · ${project.name} · ${formatDPRDate(dpr.date,{day:"numeric",month:"short",year:"numeric"})}`,page.left,page.height-6);doc.text(`Page ${number} of ${totalPages}`,page.width-page.right,page.height-6,{align:"right"})}
 const blob=doc.output("blob");const filename=dprPdfFilename(project,dpr);return{blob,file:new File([blob],filename,{type:"application/pdf",lastModified:Date.now()}),filename,size:blob.size};
}

async function resolvePdfImage(src:string){let blob:Blob|undefined;if(isStoredPhoto(src))blob=await getPhotoBlob(src);else{const response=await fetch(src);if(response.ok)blob=await response.blob()}if(!blob)return null;return blobToJpeg(blob)}
async function blobToJpeg(blob:Blob){const url=URL.createObjectURL(blob);try{const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const value=new Image();value.onload=()=>resolve(value);value.onerror=()=>reject(new Error("Photo unavailable"));value.src=url});const maxEdge=1200,scale=Math.min(1,maxEdge/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext("2d");if(!context)throw new Error("Photo conversion unavailable");context.fillStyle="#ffffff";context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(image,0,0,canvas.width,canvas.height);return{data:canvas.toDataURL("image/jpeg",.78)}}finally{URL.revokeObjectURL(url)}}
function drawPhotoUnavailable(doc:Doc,x:number,y:number,width:number,height:number){doc.setFillColor(240,241,243);doc.rect(x,y,width,height,"F");doc.setFont("helvetica","normal");doc.setFontSize(8);doc.setTextColor(116,122,133);doc.text("Photo unavailable",x+width/2,y+height/2,{align:"center"})}
function formatTimestamp(value:string){const date=new Date(value);if(Number.isNaN(date.getTime()))return "Submitted";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(date)}
function formatTime(value:string){const[hours,minutes]=value.split(":").map(Number);if(!Number.isFinite(hours))return value;return `${hours%12||12}:${String(minutes||0).padStart(2,"0")} ${hours>=12?"PM":"AM"}`}
