"use client";

import {ArrowRight,BriefcaseBusiness,CalendarDays,Camera,Check,ChevronRight,ClipboardCheck,HardHat,PackageOpen,UsersRound} from "lucide-react";
import {motion,useReducedMotion} from "motion/react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import {BottomSheet} from "@/components/dpr/bottom-sheet";
import {user} from "@/data/mock-data";
import {addDays,completedRequired,completionPercent,createDPR,DPR_CHANGE_EVENT,formatDPRDate,getDPR,loadDPRRecords,parseISODate,sectionComplete,todayISO} from "@/lib/dpr";
import {ease,transitions} from "@/lib/motion";
import {resolveProject} from "@/lib/projects";
import type {DPR} from "@/types";

const sectionMeta=[
 {id:"work",label:"Work Done",helper:"Add work activities",icon:BriefcaseBusiness,tone:"bg-[#ffeded] text-[#e44f49]"},
 {id:"manpower",label:"Manpower",helper:"Add team details",icon:UsersRound,tone:"bg-[#edf3ff] text-[#4c6fc4]"},
 {id:"materials",label:"Materials Used",helper:"Add materials",icon:PackageOpen,tone:"bg-[#e9f8f3] text-[#2b9a77]"},
 {id:"photos",label:"Site Photos",helper:"Capture progress",icon:Camera,tone:"bg-[#fff5dd] text-[#d8920a]"},
 {id:"visit",label:"Site Visit / Feedback",helper:"Optional",icon:HardHat,tone:"bg-[#f0efff] text-[#5b62c9]",optional:true},
 {id:"tomorrow",label:"Tomorrow's Plan",helper:"Add planned work",icon:CalendarDays,tone:"bg-[#fff0e5] text-[#ed771f]",optional:true},
] as const;
const greeting=(hour:number)=>hour<12?"Good morning":hour<17?"Good afternoon":"Good evening";

export function TodayDashboard({projectId}:{projectId:string}){
 const router=useRouter();const reduce=useReducedMotion();const date=todayISO();const project=resolveProject(projectId);
 const[record,setRecord]=useState<DPR|null>(null);const[previous,setPrevious]=useState<DPR|null>(null);const[createOpen,setCreateOpen]=useState(false);const[destination,setDestination]=useState("");const[hour,setHour]=useState(12);
 useEffect(()=>{const reload=()=>{setRecord(getDPR(projectId,date));setPrevious(getDPR(projectId,addDays(date,-1)));setHour(new Date().getHours())};const timer=window.setTimeout(reload,0);window.addEventListener(DPR_CHANGE_EVENT,reload);return()=>{window.clearTimeout(timer);window.removeEventListener(DPR_CHANGE_EVENT,reload)}},[date,projectId]);
 const current=parseISODate(date);const monday=addDays(date,-((current.getDay()+6)%7));const week=Array.from({length:7},(_,index)=>{const value=addDays(monday,index);return{date:value,label:new Intl.DateTimeFormat("en-GB",{weekday:"narrow"}).format(parseISODate(value)),number:Number(value.slice(-2)),record:getDPR(projectId,value)}});
 const completed=record?completedRequired(record):0;const percent=record?completionPercent(record):0;const submitted=record?.status==="submitted";const editorHref=`/dpr/today?project=${projectId}&date=${date}`;
 const start=(carry:boolean,anchor=destination)=>{const draft=createDPR(projectId,date,carry?previous?.tomorrowPlan:[]);setCreateOpen(false);router.push(`/dpr/today?project=${projectId}&date=${draft.date}${anchor}`)};
 const openDPR=(anchor="")=>{if(record){router.push(record.status==="submitted"?`/dpr/report?project=${projectId}&date=${date}`:`${editorHref}${anchor}`);return}setDestination(anchor);if(previous?.tomorrowPlan.length)setCreateOpen(true);else start(false,anchor)};
 const sectionState=(key:(typeof sectionMeta)[number]["id"]):SectionStatus=>{if(!record)return "untouched";if(key==="visit")return record.siteVisits.length?"complete":"untouched";if(key==="tomorrow")return record.tomorrowPlan.length?(record.tomorrowPlan.every(row=>!!row.activity&&row.planned>0)?"complete":"attention"):"untouched";const rows=record[key];if(sectionComplete(record,key))return "complete";return rows.length?"attention":"untouched"};
 const recent=Object.values(loadDPRRecords()).filter(item=>item.projectId===projectId).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);
 return <motion.main initial={reduce?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={transitions.page} className="mx-auto w-full min-w-0 max-w-[1240px] overflow-x-clip px-4 pb-[calc(96px+env(safe-area-inset-bottom))] pt-4 sm:px-6 lg:px-8 lg:pb-12 lg:pt-8 xl:px-10">
<div className="lg:grid lg:grid-cols-[minmax(0,1fr)_360px] lg:items-center lg:gap-10"><GreetingBlock date={date} hour={hour}/><DprProgressHero projectName={project.name} percent={percent} completed={completed} submitted={submitted} reduce={Boolean(reduce)} onContinue={()=>openDPR()}/></div>
  <div className="mt-5 min-w-0 lg:mt-3"><div className="min-w-0 space-y-7 lg:space-y-8">
   <WeekStrip date={date} week={week} projectId={projectId}/>
   <section aria-labelledby="dpr-sections-title"><div className="mb-4 flex items-end justify-between gap-4 lg:hidden"><h2 id="dpr-sections-title" className="text-[21px] font-bold tracking-[-.035em]">DPR Sections</h2><span className="shrink-0 text-[13px] font-medium text-[#858997]">{completed} / 4 required</span></div><div className="grid min-w-0 grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-3">{sectionMeta.map((item,index)=><SectionTile key={item.id} {...item} status={sectionState(item.id)} delay={reduce?0:index*.035} onClick={()=>openDPR(`#${item.id}`)}/>)}</div></section>
   <ReviewSubmitCard ready={completed===4} submitted={submitted} onClick={()=>openDPR()}/>
   <RecentDPRs records={recent} projectId={projectId}/>
  </div></div>
  <BottomSheet open={createOpen} title="Start today's DPR" onClose={()=>setCreateOpen(false)}><div className="p-5"><p className="text-[14px] leading-6 text-[#71717a]">{previous?.tomorrowPlan.length??0} activities were planned yesterday for today.</p><div className="my-5 divide-y divide-black/[.06] rounded-xl bg-[#f7f8fa] px-4">{previous?.tomorrowPlan.map(item=><div key={item.id} className="flex justify-between gap-3 py-3 text-[14px]"><span className="min-w-0">{item.activity}</span><span className="shrink-0">{item.planned} {item.unit}</span></div>)}</div><button onClick={()=>start(true)} className="h-[50px] w-full rounded-[12px] bg-[#ed4f49] text-[14px] font-semibold text-white active:scale-[.98]">Use planned work</button><button onClick={()=>start(false)} className="mt-2 h-12 w-full rounded-[11px] border border-black/[.08] text-[14px] font-semibold active:scale-[.98]">Start empty</button></div></BottomSheet>
 </motion.main>
}

function GreetingBlock({date,hour}:{date:string;hour:number}){return <section className="mb-8 lg:mb-0"><p className="text-[12px] font-bold uppercase tracking-[.16em] text-[#777b88] lg:text-[10px]">{formatDPRDate(date,{weekday:"long",day:"numeric",month:"long",year:"numeric"})}</p><h1 className="mt-3 max-w-[620px] text-[34px] font-bold leading-[1.04] tracking-[-.052em] sm:text-[38px] lg:text-[36px]">{greeting(hour)},<br/>{user.name}</h1><p className="mt-3 text-[15px] leading-6 text-[#737784] lg:text-[14px]">Let&apos;s capture today&apos;s site progress</p><span className="mt-4 block h-1 w-12 rounded-full bg-[#ed4f49] lg:hidden"/></section>}

function DprProgressHero({projectName,percent,completed,submitted,reduce,onContinue}:{projectName:string;percent:number;completed:number;submitted:boolean;reduce:boolean;onContinue:()=>void}){const circumference=2*Math.PI*48;const offset=circumference*(1-percent/100);return <section className="relative isolate min-w-0 overflow-hidden rounded-[26px] bg-[#18191f] px-5 py-6 text-white shadow-[0_14px_32px_rgba(20,21,29,.14)] sm:px-7 sm:py-7 lg:rounded-[16px] lg:border lg:border-[#e1e5eb] lg:bg-white lg:px-5 lg:py-4 lg:text-[#151821] lg:shadow-[0_5px_18px_rgba(20,25,35,.04)]"><div className="pointer-events-none absolute -bottom-28 -right-16 -z-10 size-64 rounded-full bg-[#ef4f49]/20 blur-3xl lg:hidden"/><div className="grid min-w-0 grid-cols-[minmax(0,1fr)_90px] items-center gap-4 sm:grid-cols-[minmax(0,1fr)_116px] sm:gap-7 lg:grid-cols-[minmax(0,1fr)_76px] lg:gap-3"><div className="min-w-0"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-white/60 lg:normal-case lg:tracking-normal lg:text-[#333844]">Today&apos;s DPR</p><h2 className="mt-4 text-[21px] font-bold leading-[1.18] tracking-[-.035em] sm:text-[25px] lg:mt-1 lg:text-[24px]">{submitted?"Today's site record is complete":`${percent}%`}<span className="hidden lg:inline lg:text-[13px] lg:font-medium lg:text-[#727988]"> complete</span></h2><p className="mt-3 max-w-md text-[14px] leading-[1.55] text-white/68 lg:mt-2 lg:text-[11px] lg:text-[#747b89]">{submitted?`Submitted for ${projectName}.`:`${completed} of 4 required sections complete`}</p><button onClick={onContinue} className="mt-5 inline-flex min-h-12 items-center justify-center gap-2 rounded-[13px] bg-[#ed4f49] px-5 text-[14px] font-bold shadow-[0_8px_18px_rgba(237,79,73,.2)] transition-transform duration-200 active:scale-[.98] lg:mt-3 lg:h-10 lg:min-h-0 lg:w-full lg:rounded-[8px] lg:text-[12px]">{submitted?"View Report":"Continue DPR"}<ArrowRight size={15}/></button><p className="mt-3 text-[11px] text-white/45 lg:hidden">{completed} of 4 required sections complete</p></div><div className="relative grid place-items-center justify-self-end"><svg viewBox="0 0 120 120" className="size-[90px] -rotate-90 overflow-visible sm:size-[116px] lg:size-[76px]" aria-hidden="true"><circle cx="60" cy="60" r="48" fill="none" stroke="rgba(255,255,255,.15)" strokeWidth="11" className="lg:stroke-[#e5e7eb]"/><motion.circle cx="60" cy="60" r="48" fill="none" stroke="#ef504b" strokeWidth="11" strokeLinecap="round" strokeDasharray={circumference} initial={false} animate={{strokeDashoffset:offset}} transition={{duration:reduce?0:.8,ease}}/></svg><strong className="absolute text-[27px] font-bold tracking-[-.05em] sm:text-[34px] lg:text-[20px]">{percent}<span className="text-[14px] sm:text-[17px] lg:text-[11px]">%</span></strong></div></div></section>}

type WeekDay={date:string;label:string;number:number;record:DPR|null};
function WeekStrip({date,week,projectId}:{date:string;week:WeekDay[];projectId:string}){return <section className="min-w-0 rounded-[22px] border border-black/[.06] bg-white px-4 py-5 shadow-[0_8px_24px_rgba(20,25,35,.035)] sm:px-5 lg:hidden"><div className="flex items-start justify-between gap-4"><div><h2 className="text-[18px] font-bold tracking-[-.03em]">This week</h2><p className="mt-0.5 text-[13px] text-[#858997]">{formatDPRDate(date,{month:"long",year:"numeric"})}</p></div><Link href={`/calendar?project=${projectId}`} className="flex min-h-11 items-center gap-1 text-[12px] font-semibold">View calendar <ArrowRight size={14}/></Link></div><div className="mt-4 grid min-w-0 grid-cols-7 gap-0.5">{week.map(day=>{const today=day.date===date;const status=day.record?.status;return <Link key={day.date} href={`/calendar?project=${projectId}&date=${day.date}`} aria-label={`${formatDPRDate(day.date)}${status?`, ${status}`:""}`} className="flex min-w-0 flex-col items-center gap-1.5 rounded-xl py-1"><span className={`text-[11px] font-medium ${today?"text-[#202127]":"text-[#9296a3]"}`}>{day.label}</span><strong className={`grid size-9 place-items-center rounded-full text-[13px] ${today?"bg-[#ed4f49] text-white shadow-[0_5px_12px_rgba(237,79,73,.22)]":""}`}>{day.number}</strong>{status==="submitted"?<span aria-label="Submitted" className="grid size-3 place-items-center rounded-full bg-[#3fa77a] text-white"><Check size={8} strokeWidth={3}/></span>:<span aria-label={status==="draft"?"Draft":today?"Today":"No DPR"} className={`size-1.5 rounded-full ${status==="draft"||today?"bg-[#ed4f49]":"border border-[#aeb2bd]"}`}/>}</Link>})}</div></section>}

type SectionStatus="untouched"|"attention"|"complete";
function SectionTile({label,helper,icon:Icon,tone,status,optional,delay,onClick}:{id:string;label:string;helper:string;icon:typeof BriefcaseBusiness;tone:string;status:SectionStatus;optional?:boolean;delay:number;onClick:()=>void}){return <motion.button initial={{opacity:0,y:7}} animate={{opacity:1,y:0}} transition={{...transitions.reveal,delay}} whileTap={{scale:.98}} onClick={onClick} className="relative min-h-[140px] min-w-0 rounded-[20px] border border-black/[.055] bg-white p-[14px] text-left shadow-[0_7px_22px_rgba(20,25,35,.035)] sm:min-h-[146px] sm:p-4 lg:min-h-[126px] lg:rounded-[14px] lg:shadow-[0_4px_14px_rgba(20,25,35,.025)]"><span className={`grid size-11 place-items-center rounded-[14px] lg:size-10 lg:rounded-[11px] ${tone}`}><Icon size={21} strokeWidth={2}/></span><SectionStatusMark status={status}/><span className="mt-4 block min-w-0 pr-3 text-[15px] font-bold leading-[1.2] tracking-[-.02em] sm:text-[16px] lg:mt-3 lg:text-[14px]">{label}</span><span className="mt-1.5 block min-w-0 text-[12px] leading-4 text-[#858997] sm:text-[13px] lg:text-[12px]">{status==="complete"?"Completed":helper}{optional&&status!=="complete"&&<span className="ml-1.5 inline-flex rounded-full bg-[#eef0f3] px-2 py-0.5 text-[10px] font-semibold text-[#6f7582]">Optional</span>}</span><ChevronRight size={17} className="absolute bottom-3.5 right-3 text-[#969aa5]"/></motion.button>}

function SectionStatusMark({status}:{status:SectionStatus}){if(status==="complete")return <span aria-label="Completed" className="absolute right-3.5 top-3.5 grid size-[18px] place-items-center rounded-full bg-[#3fa77a] text-white"><Check size={11} strokeWidth={3}/></span>;return <span aria-label={status==="attention"?"Needs attention":"Not started"} className={`absolute right-4 top-4 size-2.5 rounded-full ${status==="attention"?"bg-[#ed4f49]":"bg-[#b7bac3]"}`}/>}

function ReviewSubmitCard({ready,submitted,onClick}:{ready:boolean;submitted:boolean;onClick:()=>void}){const actionable=ready&&!submitted;return <button onClick={onClick} className={`flex min-h-[92px] w-full min-w-0 items-center gap-4 rounded-[20px] border p-4 text-left transition-transform active:scale-[.99] sm:p-5 lg:hidden ${actionable?"border-[#ed4f49] bg-[#ed4f49] text-white shadow-[0_8px_20px_rgba(237,79,73,.18)]":"border-black/[.06] bg-white shadow-[0_7px_22px_rgba(20,25,35,.035)]"}`}><span className={`grid size-12 shrink-0 place-items-center rounded-[15px] ${actionable?"bg-white/16 text-white":ready?"bg-[#ffebe9] text-[#ed4f49]":"bg-[#f0f3f8] text-[#687080]"}`}><ClipboardCheck size={22}/></span><span className="min-w-0 flex-1"><strong className="block text-[16px] font-bold tracking-[-.025em]">Review &amp; Submit</strong><span className={`mt-1 block text-[12px] leading-4 sm:text-[13px] ${actionable?"text-white/82":"text-[#858997]"}`}>{submitted?"View your submitted site record":actionable?"DPR ready to submit":"Complete all required sections to submit today's DPR"}</span></span><ChevronRight size={19} className={`shrink-0 ${actionable?"text-white":"text-[#8f939e]"}`}/></button>}

function RecentDPRs({records,projectId}:{records:DPR[];projectId:string}){return <section className="hidden lg:block"><div className="mb-3 flex items-center justify-between"><h2 className="text-[14px] font-bold">Recent DPRs</h2><Link href={`/calendar?project=${projectId}`} className="flex items-center gap-1 text-[11px] font-semibold">View all <ArrowRight size={13}/></Link></div><div className="grid grid-cols-3 gap-4">{records.length?records.map(record=><Link key={record.id} href={`/dpr/today?project=${record.projectId}&date=${record.date}`} className="flex min-w-0 items-center gap-3 rounded-[12px] border border-[#e1e5eb] bg-white px-4 py-3 shadow-[0_3px_12px_rgba(20,25,35,.025)]"><span className={`size-2.5 shrink-0 rounded-full ${record.status==="submitted"?"bg-[#32a675]":"bg-[#ed4f49]"}`}/><span className="min-w-0 flex-1"><strong className="block text-[12px]">{formatDPRDate(record.date,{day:"numeric",month:"short",year:"numeric"})}</strong><span className="mt-1 block text-[10px] capitalize text-[#747b89]">{record.status}</span></span><span className="text-[10px] font-semibold text-[#747b89]">{completedRequired(record)}/4</span></Link>):<p className="col-span-3 text-[12px] text-[#747b89]">No recent DPRs.</p>}</div></section>}
