"use client";

import {ArrowRight,BriefcaseBusiness,CalendarDays,Camera,Check,ChevronRight,ClipboardCheck,HardHat,PackageOpen,UsersRound} from "lucide-react";
import {motion,useReducedMotion} from "motion/react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import {BottomSheet} from "@/components/dpr/bottom-sheet";
import {projects,user} from "@/data/mock-data";
import {addDays,completedRequired,completionPercent,createDPR,DPR_CHANGE_EVENT,formatDPRDate,getDPR,parseISODate,sectionComplete,todayISO} from "@/lib/dpr";
import {ease,transitions} from "@/lib/motion";
import type {DPR} from "@/types";

const projectId="commercial-tower";
const project=projects.find(item=>item.id===projectId)??projects[0];
const sectionMeta=[
 {id:"work",label:"Work Done",helper:"Add work activities",icon:BriefcaseBusiness,tone:"bg-[#ffeded] text-[#e44f49]"},
 {id:"manpower",label:"Manpower",helper:"Add team details",icon:UsersRound,tone:"bg-[#edf3ff] text-[#4c6fc4]"},
 {id:"materials",label:"Materials Used",helper:"Add materials",icon:PackageOpen,tone:"bg-[#e9f8f3] text-[#2b9a77]"},
 {id:"photos",label:"Site Photos",helper:"Capture progress",icon:Camera,tone:"bg-[#fff5dd] text-[#d8920a]"},
 {id:"visit",label:"Site Visit / Feedback",helper:"Optional",icon:HardHat,tone:"bg-[#f0efff] text-[#5b62c9]",optional:true},
 {id:"tomorrow",label:"Tomorrow's Plan",helper:"Add planned work",icon:CalendarDays,tone:"bg-[#fff0e5] text-[#ed771f]"},
] as const;
const greeting=(hour:number)=>hour<12?"Good morning":hour<17?"Good afternoon":"Good evening";

export function TodayDashboard(){
 const router=useRouter();const reduce=useReducedMotion();const date=todayISO();
 const[record,setRecord]=useState<DPR|null>(null);const[previous,setPrevious]=useState<DPR|null>(null);const[createOpen,setCreateOpen]=useState(false);const[destination,setDestination]=useState("");const[hour,setHour]=useState(12);
 useEffect(()=>{const reload=()=>{setRecord(getDPR(projectId,date));setPrevious(getDPR(projectId,addDays(date,-1)));setHour(new Date().getHours())};const timer=window.setTimeout(reload,0);window.addEventListener(DPR_CHANGE_EVENT,reload);return()=>{window.clearTimeout(timer);window.removeEventListener(DPR_CHANGE_EVENT,reload)}},[date]);
 const current=parseISODate(date);const monday=addDays(date,-((current.getDay()+6)%7));const week=Array.from({length:7},(_,index)=>{const value=addDays(monday,index);return{date:value,label:new Intl.DateTimeFormat("en-GB",{weekday:"narrow"}).format(parseISODate(value)),number:Number(value.slice(-2)),record:getDPR(projectId,value)}});
 const completed=record?completedRequired(record):0;const percent=record?completionPercent(record):0;const submitted=record?.status==="submitted";const editorHref=`/dpr/today?project=${projectId}&date=${date}`;
 const start=(carry:boolean,anchor=destination)=>{const draft=createDPR(projectId,date,carry?previous?.tomorrowPlan:[]);setCreateOpen(false);router.push(`/dpr/today?project=${projectId}&date=${draft.date}${anchor}`)};
 const openDPR=(anchor="")=>{if(record){router.push(`${editorHref}${anchor}`);return}setDestination(anchor);if(previous?.tomorrowPlan.length)setCreateOpen(true);else start(false,anchor)};
 const sectionState=(key:(typeof sectionMeta)[number]["id"]):SectionStatus=>{if(!record)return "untouched";if(key==="visit")return record.siteVisits.length?"complete":"untouched";const dataKey=key==="tomorrow"?"tomorrowPlan":key;const rows=record[dataKey];if(sectionComplete(record,dataKey))return "complete";return rows.length?"attention":"untouched"};
 return <motion.main initial={reduce?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={transitions.page} className="mx-auto w-full min-w-0 max-w-[1180px] overflow-x-clip px-4 pb-[calc(96px+env(safe-area-inset-bottom))] pt-4 sm:px-6 lg:px-8 lg:pb-12 lg:pt-10">
  <GreetingBlock date={date} hour={hour}/>
  <DprProgressHero percent={percent} completed={completed} submitted={submitted} reduce={Boolean(reduce)} onContinue={()=>openDPR()}/>
  <div className="mt-5 grid min-w-0 gap-7 lg:grid-cols-[minmax(0,1.35fr)_minmax(320px,.65fr)] lg:items-start"><div className="min-w-0 space-y-7">
   <WeekStrip date={date} week={week}/>
   <section aria-labelledby="dpr-sections-title"><div className="mb-4 flex items-end justify-between gap-4"><h2 id="dpr-sections-title" className="text-[21px] font-bold tracking-[-.035em]">DPR Sections</h2><span className="shrink-0 text-[13px] font-medium text-[#858997]">{completed} / 5 required</span></div><div className="grid min-w-0 grid-cols-2 gap-3 sm:gap-4">{sectionMeta.map((item,index)=><SectionTile key={item.id} {...item} status={sectionState(item.id)} delay={reduce?0:index*.035} onClick={()=>openDPR(`#${item.id}`)}/>)}</div></section>
   <ReviewSubmitCard ready={completed===5} submitted={submitted} onClick={()=>openDPR()}/>
  </div><aside className="hidden space-y-5 lg:block">{previous?.tomorrowPlan.length?<section className="rounded-[22px] border border-black/[.06] bg-white p-5 shadow-[0_12px_35px_rgba(20,25,35,.05)]"><h2 className="text-[16px] font-bold">Planned for today</h2><div className="mt-3 divide-y divide-black/[.06]">{previous.tomorrowPlan.map(item=><div key={item.id} className="flex justify-between gap-4 py-3 text-[13px]"><span>{item.activity}</span><span className="shrink-0 text-[#777b88]">{item.planned} {item.unit}</span></div>)}</div></section>:null}</aside></div>
  <BottomSheet open={createOpen} title="Start today's DPR" onClose={()=>setCreateOpen(false)}><div className="p-5"><p className="text-[14px] leading-6 text-[#71717a]">{previous?.tomorrowPlan.length??0} activities were planned yesterday for today.</p><div className="my-5 divide-y divide-black/[.06] rounded-xl bg-[#f7f8fa] px-4">{previous?.tomorrowPlan.map(item=><div key={item.id} className="flex justify-between gap-3 py-3 text-[14px]"><span className="min-w-0">{item.activity}</span><span className="shrink-0">{item.planned} {item.unit}</span></div>)}</div><button onClick={()=>start(true)} className="h-[50px] w-full rounded-[12px] bg-[#ed4f49] text-[14px] font-semibold text-white active:scale-[.98]">Use planned work</button><button onClick={()=>start(false)} className="mt-2 h-12 w-full rounded-[11px] border border-black/[.08] text-[14px] font-semibold active:scale-[.98]">Start empty</button></div></BottomSheet>
 </motion.main>
}

function GreetingBlock({date,hour}:{date:string;hour:number}){return <section className="mb-8 lg:mb-9"><p className="text-[12px] font-bold uppercase tracking-[.16em] text-[#777b88]">{formatDPRDate(date,{weekday:"long",day:"numeric",month:"long"})}</p><h1 className="mt-3 max-w-[620px] text-[34px] font-bold leading-[1.04] tracking-[-.052em] sm:text-[38px]">{greeting(hour)},<br/>{user.name}</h1><p className="mt-3 text-[15px] leading-6 text-[#737784]">Let&apos;s capture today&apos;s site progress</p><span className="mt-4 block h-1 w-12 rounded-full bg-[#ed4f49]"/></section>}

function DprProgressHero({percent,completed,submitted,reduce,onContinue}:{percent:number;completed:number;submitted:boolean;reduce:boolean;onContinue:()=>void}){const circumference=2*Math.PI*48;const offset=circumference*(1-percent/100);return <section className="relative isolate min-w-0 overflow-hidden rounded-[26px] bg-[#18191f] px-5 py-6 text-white shadow-[0_14px_32px_rgba(20,21,29,.14)] sm:px-7 sm:py-7"><div className="pointer-events-none absolute -bottom-28 -right-16 -z-10 size-64 rounded-full bg-[#ef4f49]/20 blur-3xl"/><div className="grid min-w-0 grid-cols-[minmax(0,1fr)_90px] items-center gap-4 sm:grid-cols-[minmax(0,1fr)_116px] sm:gap-7"><div className="min-w-0"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-white/60">Today&apos;s DPR</p><h2 className="mt-4 text-[21px] font-bold leading-[1.18] tracking-[-.035em] sm:text-[25px]">{submitted?"Today's site record is complete":`Your report is ${percent}% complete`}</h2><p className="mt-3 max-w-md text-[14px] leading-[1.55] text-white/68">{submitted?`Submitted for ${project.name}.`:"Complete all five required sections to submit today's site record."}</p><button onClick={onContinue} className="mt-5 inline-flex min-h-12 items-center justify-center gap-2 rounded-[13px] bg-[#ed4f49] px-5 text-[14px] font-bold shadow-[0_8px_18px_rgba(237,79,73,.2)] transition-transform duration-200 active:scale-[.98]">{submitted?"View DPR":"Continue DPR"}<ArrowRight size={17}/></button><p className="mt-3 text-[11px] text-white/45">{completed} of 5 required sections complete</p></div><div className="relative grid place-items-center justify-self-end"><svg viewBox="0 0 120 120" className="size-[90px] -rotate-90 overflow-visible sm:size-[116px]" aria-hidden="true"><circle cx="60" cy="60" r="48" fill="none" stroke="rgba(255,255,255,.15)" strokeWidth="11"/><motion.circle cx="60" cy="60" r="48" fill="none" stroke="#ef504b" strokeWidth="11" strokeLinecap="round" strokeDasharray={circumference} initial={reduce?false:{strokeDashoffset:circumference}} animate={{strokeDashoffset:offset}} transition={{duration:reduce?0:.8,ease}}/></svg><strong className="absolute text-[27px] font-bold tracking-[-.05em] sm:text-[34px]">{percent}<span className="text-[14px] sm:text-[17px]">%</span></strong></div></div></section>}

type WeekDay={date:string;label:string;number:number;record:DPR|null};
function WeekStrip({date,week}:{date:string;week:WeekDay[]}){return <section className="min-w-0 rounded-[22px] border border-black/[.06] bg-white px-4 py-5 shadow-[0_8px_24px_rgba(20,25,35,.035)] sm:px-5"><div className="flex items-start justify-between gap-4"><div><h2 className="text-[18px] font-bold tracking-[-.03em]">This week</h2><p className="mt-0.5 text-[13px] text-[#858997]">{formatDPRDate(date,{month:"long",year:"numeric"})}</p></div><Link href="/calendar" className="flex min-h-11 items-center gap-1 text-[12px] font-semibold">View calendar <ArrowRight size={14}/></Link></div><div className="mt-4 grid min-w-0 grid-cols-7 gap-0.5">{week.map(day=>{const today=day.date===date;const status=day.record?.status;return <Link key={day.date} href={`/calendar?date=${day.date}`} aria-label={`${formatDPRDate(day.date)}${status?`, ${status}`:""}`} className="flex min-w-0 flex-col items-center gap-1.5 rounded-xl py-1"><span className={`text-[11px] font-medium ${today?"text-[#202127]":"text-[#9296a3]"}`}>{day.label}</span><strong className={`grid size-9 place-items-center rounded-full text-[13px] ${today?"bg-[#ed4f49] text-white shadow-[0_5px_12px_rgba(237,79,73,.22)]":""}`}>{day.number}</strong><span className={`size-1.5 rounded-full ${status==="submitted"?"bg-[#3fa77a]":status==="draft"||today?"bg-[#ed4f49]":"border border-[#aeb2bd]"}`}/></Link>})}</div></section>}

type SectionStatus="untouched"|"attention"|"complete";
function SectionTile({label,helper,icon:Icon,tone,status,delay,onClick}:{id:string;label:string;helper:string;icon:typeof BriefcaseBusiness;tone:string;status:SectionStatus;optional?:boolean;delay:number;onClick:()=>void}){return <motion.button initial={{opacity:0,y:7}} animate={{opacity:1,y:0}} transition={{...transitions.reveal,delay}} whileTap={{scale:.98}} onClick={onClick} className="relative min-h-[140px] min-w-0 rounded-[20px] border border-black/[.055] bg-white p-[14px] text-left shadow-[0_7px_22px_rgba(20,25,35,.035)] sm:min-h-[146px] sm:p-4"><span className={`grid size-11 place-items-center rounded-[14px] ${tone}`}><Icon size={21} strokeWidth={2}/></span><SectionStatusMark status={status}/><span className="mt-4 block min-w-0 pr-3 text-[15px] font-bold leading-[1.2] tracking-[-.02em] sm:text-[16px]">{label}</span><span className="mt-1.5 block min-w-0 text-[12px] leading-4 text-[#858997] sm:text-[13px]">{status==="complete"?"Completed":helper}</span><ChevronRight size={17} className="absolute bottom-3.5 right-3 text-[#969aa5]"/></motion.button>}

function SectionStatusMark({status}:{status:SectionStatus}){if(status==="complete")return <span aria-label="Completed" className="absolute right-3.5 top-3.5 grid size-[18px] place-items-center rounded-full bg-[#3fa77a] text-white"><Check size={11} strokeWidth={3}/></span>;return <span aria-label={status==="attention"?"Needs attention":"Not started"} className={`absolute right-4 top-4 size-2.5 rounded-full ${status==="attention"?"bg-[#ed4f49]":"bg-[#b7bac3]"}`}/>}

function ReviewSubmitCard({ready,submitted,onClick}:{ready:boolean;submitted:boolean;onClick:()=>void}){const actionable=ready&&!submitted;return <button onClick={onClick} className={`flex min-h-[92px] w-full min-w-0 items-center gap-4 rounded-[20px] border p-4 text-left transition-transform active:scale-[.99] sm:p-5 ${actionable?"border-[#ed4f49] bg-[#ed4f49] text-white shadow-[0_8px_20px_rgba(237,79,73,.18)]":"border-black/[.06] bg-white shadow-[0_7px_22px_rgba(20,25,35,.035)]"}`}><span className={`grid size-12 shrink-0 place-items-center rounded-[15px] ${actionable?"bg-white/16 text-white":ready?"bg-[#ffebe9] text-[#ed4f49]":"bg-[#f0f3f8] text-[#687080]"}`}><ClipboardCheck size={22}/></span><span className="min-w-0 flex-1"><strong className="block text-[16px] font-bold tracking-[-.025em]">Review &amp; Submit</strong><span className={`mt-1 block text-[12px] leading-4 sm:text-[13px] ${actionable?"text-white/82":"text-[#858997]"}`}>{submitted?"View your submitted site record":actionable?"DPR ready to submit":"Complete all required sections to submit today's DPR"}</span></span><ChevronRight size={19} className={`shrink-0 ${actionable?"text-white":"text-[#8f939e]"}`}/></button>}
