/* eslint-disable @next/next/no-img-element */
"use client";
import {ArrowLeft,Camera,Check,ChevronRight,ClipboardCheck,Package,Plus,Trash2,Users,X} from "lucide-react";
import {motion} from "motion/react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {ChangeEvent,FormEvent,useCallback,useEffect,useRef,useState} from "react";
import {BottomSheet} from "@/components/dpr/bottom-sheet";
import {DPRDeleteMenu} from "@/components/dpr/dpr-delete-menu";
import {SectionCard} from "@/components/dpr/section-card";
import {completedRequired,completionPercent,formatDPRDate,getDPR,missingSections,saveDPR,todayISO} from "@/lib/dpr";
import type {DPR,DPRManpower,DPRMaterial,DPRPhoto,DPRWork,SiteVisit,TomorrowActivity} from "@/types";

type Sheet="work"|"manpower"|"material"|"visit"|"plan"|"confirm"|null;
const activities:Record<string,string>={"Cable Tray Installation":"m","Conduit Laying":"m","Cable Pulling":"m","Panel Installation":"nos","Earthing":"m","Light Fixture Installation":"nos","Testing & Commissioning":"job","Other":""};
const materialUnits:Record<string,string>={"Electrical Cable":"m","Cable Tray":"m","PVC Conduit":"m","GI Conduit":"m","Earthing Cable":"m","Light Fixture":"nos","Distribution Board":"nos","Cable Gland":"nos","Other":""};
const roles=["Electrician","Helper","Supervisor","Technician","Welder","Plumber","Other"];
const field="h-12 w-full rounded-[10px] border border-[#e4e4e7] bg-white px-3.5 text-[15px] outline-none transition-colors focus:border-[#e14d48]";
const label="mb-2 block text-[14px] font-medium";
const id=()=>crypto.randomUUID();

export function DPREditor({projectId,date}:{projectId:string;date:string}){const router=useRouter();const[dpr,setDpr]=useState<DPR>({id:"",projectId,date,status:"draft",work:[],manpower:[],materials:[],photos:[],siteVisits:[],tomorrowPlan:[],generalRemarks:"",updatedAt:""});const[ready,setReady]=useState(false);const[exists,setExists]=useState(false);const[saveState,setSaveState]=useState<"saving"|"saved">("saved");const[sheet,setSheet]=useState<Sheet>(null);const[editing,setEditing]=useState<string|null>(null);const[review,setReview]=useState(false);const[success,setSuccess]=useState(false);const[viewer,setViewer]=useState<DPRPhoto|null>(null);const[replaceId,setReplaceId]=useState<string|null>(null);const galleryRef=useRef<HTMLInputElement>(null);const cameraRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const timer=window.setTimeout(()=>{const stored=getDPR(projectId,date);if(stored){setDpr(stored);setExists(true)}setReady(true)},0);return()=>window.clearTimeout(timer)},[projectId,date]);
 useEffect(()=>{if(!ready||!exists||dpr.status==="submitted")return;const savingTimer=window.setTimeout(()=>setSaveState("saving"),0);const timer=window.setTimeout(()=>{saveDPR(dpr);setSaveState("saved")},450);return()=>{window.clearTimeout(savingTimer);window.clearTimeout(timer)}},[dpr,ready,exists]);
 useEffect(()=>{if(!ready||!location.hash)return;window.setTimeout(()=>document.querySelector(location.hash)?.scrollIntoView({behavior:"smooth",block:"start"}),150)},[ready]);
 const update=useCallback(<K extends keyof DPR>(key:K,value:DPR[K])=>setDpr(current=>({...current,[key]:value})),[]);
 const completed=completedRequired(dpr),percent=completionPercent(dpr),missing=missingSections(dpr);
 const totalManpower=dpr.manpower.reduce((sum,row)=>sum+row.inHouse+row.subcontractor,0);
 const open=(type:Sheet,itemId?:string)=>{setEditing(itemId??null);setSheet(type)};
 const remove=<K extends "work"|"manpower"|"materials"|"siteVisits"|"tomorrowPlan">(key:K,itemId:string)=>{if(window.confirm("Remove this entry?"))setDpr(current=>({...current,[key]:current[key].filter(item=>item.id!==itemId)}))};
 const photoFiles=(event:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files??[]);files.forEach(file=>{const reader=new FileReader();reader.onload=()=>{const photo:DPRPhoto={id:replaceId??id(),src:String(reader.result),name:file.name};setDpr(current=>({...current,photos:replaceId?current.photos.map(item=>item.id===replaceId?photo:item):[...current.photos,photo]}));setReplaceId(null)};reader.readAsDataURL(file)});event.target.value=""};
 const reviewNow=()=>{setReview(true);window.scrollTo({top:0,behavior:"smooth"})};
 const submit=()=>{if(missing.length){setSheet(null);setReview(true);return}const next={...dpr,status:"submitted" as const,updatedAt:new Date().toISOString()};saveDPR(next);setDpr(next);setSheet(null);setSuccess(true)};
 const afterDelete=()=>router.replace(date===todayISO()?"/today":`/calendar?date=${date}`);
 if(!ready)return <div className="grid min-h-[70dvh] place-items-center text-[14px] text-[#71717a]">Opening today&apos;s DPR…</div>;
 if(!exists)return <div className="grid min-h-[70dvh] place-items-center px-4"><div className="text-center"><h1 className="text-[20px] font-semibold">No DPR for this date</h1><p className="mt-2 text-[14px] text-[#71717a]">Create it from Today or Calendar first.</p><Link href="/calendar" className="mt-5 inline-grid h-11 place-items-center rounded-[10px] bg-[#18181b] px-5 text-[14px] font-semibold text-white">Back to calendar</Link></div></div>;
 if(dpr.status==="submitted")return <ReadOnlyDPR dpr={dpr} onDeleted={afterDelete}/>;
 if(success)return <Success date={date} onDone={()=>router.push("/today")}/>;
 if(review)return <Review dpr={dpr} missing={missing} totalManpower={totalManpower} onBack={()=>setReview(false)} onEdit={section=>{setReview(false);window.setTimeout(()=>document.getElementById(section)?.scrollIntoView({behavior:"smooth"}),50)}} onSubmit={()=>setSheet("confirm")}/>;
 return <div className="min-h-dvh pb-[calc(150px+env(safe-area-inset-bottom))] lg:pb-12"><header className="sticky top-0 z-40 border-b border-[#e4e4e7] bg-white/95 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-[1180px] items-center justify-between px-4 sm:px-6"><Link href="/today" className="focus-ring flex h-11 items-center gap-2 rounded-[10px] text-[15px] font-semibold"><ArrowLeft size={19}/><span>Today&apos;s DPR</span></Link><div className="flex items-center gap-2"><motion.span key={saveState} initial={{opacity:0,y:2}} animate={{opacity:1,y:0}} className="text-[13px] text-[#71717a]">{saveState==="saving"?"Saving…":"Saved ✓"}</motion.span><DPRDeleteMenu dpr={dpr} onDeleted={afterDelete}/></div></div></header>
  <main className="mx-auto grid w-full min-w-0 max-w-[1180px] gap-5 px-4 py-4 sm:px-6 lg:grid-cols-[minmax(0,800px)_300px] lg:items-start lg:gap-6 lg:py-8"><div className="min-w-0 space-y-3 lg:space-y-5"><div className="mb-5 min-w-0"><div className="flex min-w-0 items-center gap-2"><h1 className="min-w-0 truncate text-[24px] font-semibold sm:text-[20px]">Commercial Tower</h1><span className="shrink-0 rounded-full bg-[#fdeceb] px-2.5 py-1 text-[11px] font-semibold text-[#c43f3b]">Draft</span></div><p className="mt-1 text-[14px] text-[#71717a]">{formatDPRDate(date)} · MEP Works</p></div>
   <nav className="hidden gap-2 lg:flex" aria-label="DPR sections">{[["work","Work"],["manpower","Manpower"],["materials","Materials"],["photos","Photos"],["visit","Visit"],["tomorrow","Tomorrow"]].map(([anchor,name],index)=>{const done=index===4?dpr.siteVisits.length>0:index===0?dpr.work.length>0:index===1?dpr.manpower.length>0:index===2?dpr.materials.length>0:index===3?dpr.photos.length>0:dpr.tomorrowPlan.length>0;return <a key={anchor} href={`#${anchor}`} className="focus-ring flex h-10 shrink-0 items-center gap-1.5 rounded-full border border-[#e4e4e7] bg-white px-3 text-[12px] font-medium"><span className={`grid size-4 place-items-center rounded-full text-[9px] ${done?"bg-[#eaf5ef] text-[#3f8f6b]":"bg-[#f4f4f5] text-[#a1a1aa]"}`}>{done?<Check size={10}/>:index===4?"○":"·"}</span>{name}</a>})}</nav><div className="rounded-xl border border-[#e4e4e7] bg-white p-4 lg:hidden"><div className="flex items-center justify-between text-[13px]"><span className="font-medium">DPR progress</span><strong>{completed} / 5</strong></div><p className="mt-1 text-[12px] text-[#71717a]">{completed} of 5 required sections complete</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#f0f0f2]"><motion.div animate={{width:`${percent}%`}} className="h-full rounded-full bg-[#e14d48]"/></div></div>
   <SectionCard id="work" number="01" title="Work Done" supporting="What was done today?" action={<AddButton onClick={()=>open("work")}>Add activity</AddButton>}><Rows empty="No work added yet.">{dpr.work.map(row=><WorkRow key={row.id} row={row} onEdit={()=>open("work",row.id)}/>)}</Rows></SectionCard>
   <SectionCard id="manpower" number="02" title="Manpower" supporting="Who worked on site today?" action={<AddButton onClick={()=>open("manpower")}>Add manpower</AddButton>}><Rows empty="No manpower added yet.">{dpr.manpower.map(row=><ListRow key={row.id} icon={<Users size={17}/>} title={row.role} value={`${row.inHouse+row.subcontractor}`} onClick={()=>open("manpower",row.id)}/>)}</Rows>{dpr.manpower.length>0&&<div className="mt-4 flex justify-between border-t border-[#e4e4e7] pt-4 text-[14px] font-semibold"><span>Total manpower</span><span>{totalManpower}</span></div>}</SectionCard>
   <SectionCard id="materials" number="03" title="Materials Used" supporting="What materials were used today?" action={<AddButton onClick={()=>open("material")}>Add material</AddButton>}><Rows empty="No materials added yet.">{dpr.materials.map(row=><ListRow key={row.id} icon={<Package size={17}/>} title={row.material} subtitle={row.remarks} value={`${row.quantity} ${row.unit}`} onClick={()=>open("material",row.id)}/>)}</Rows></SectionCard>
   <SectionCard id="photos" number="04" title="Site Photos" supporting="Add photos showing today's site progress."><input ref={cameraRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={photoFiles}/><input ref={galleryRef} className="hidden" type="file" accept="image/*" multiple onChange={photoFiles}/>{dpr.photos.length===0?<div className="rounded-xl border border-dashed border-[#cfcfd5] bg-[#fafafa] p-7 text-center"><span className="mx-auto grid size-12 place-items-center rounded-xl bg-[#fdeceb] text-[#e14d48]"><Camera size={21}/></span><p className="mt-4 text-[15px] font-semibold">Show today&apos;s progress</p><p className="mt-1 text-[13px] text-[#71717a]">Take a site photo or choose one from your gallery.</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><button onClick={()=>cameraRef.current?.click()} className="focus-ring h-12 rounded-[10px] bg-[#e14d48] text-[14px] font-semibold text-white">Take photo</button><button onClick={()=>galleryRef.current?.click()} className="focus-ring h-12 rounded-[10px] border border-[#e4e4e7] bg-white text-[14px] font-semibold">Choose from gallery</button></div></div>:<><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{dpr.photos.map(photo=><motion.div initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} key={photo.id} className="overflow-hidden rounded-xl border border-[#e4e4e7]"><button onClick={()=>setViewer(photo)} className="block w-full cursor-zoom-in"><img src={photo.src} alt={photo.caption||"Site progress"} className="aspect-[4/3] w-full object-cover"/></button><div className="flex items-center justify-between p-2"><button onClick={()=>setViewer(photo)} className="text-[12px] font-medium">View</button><div className="flex gap-1"><button onClick={()=>{setReplaceId(photo.id);galleryRef.current?.click()}} className="h-8 px-2 text-[11px] text-[#71717a]">Replace</button><button onClick={()=>update("photos",dpr.photos.filter(item=>item.id!==photo.id))} className="grid size-8 place-items-center text-[#e14d48]" aria-label="Remove photo"><Trash2 size={14}/></button></div></div></motion.div>)}</div><button onClick={()=>cameraRef.current?.click()} className="mt-4 flex h-11 items-center gap-2 text-[13px] font-semibold text-[#e14d48]"><Plus size={16}/>Add another photo</button></>}</SectionCard>
   <SectionCard id="visit" number="05" title="Site Visit / Feedback" supporting="Record feedback if a senior person or client visited today." optional action={<AddButton onClick={()=>open("visit")}>Add visit</AddButton>}>{dpr.siteVisits.length===0?<Empty text="No site visit recorded today."/>:<div className="space-y-4">{dpr.siteVisits.map(visit=><button key={visit.id} onClick={()=>open("visit",visit.id)} className="w-full border-l-2 border-[#e14d48] pl-4 text-left"><span className="text-[12px] font-semibold text-[#71717a]">{visit.visitTime}</span><p className="mt-1 text-[15px] font-semibold">{visit.visitorName} <span className="font-normal text-[#71717a]">{visit.designation}</span></p><p className="mt-2 text-[13px] leading-5 text-[#71717a]">{visit.feedback}</p>{visit.actionRequired&&<span className="mt-2 inline-flex rounded-full bg-[#fff5e5] px-2 py-1 text-[10px] font-semibold text-[#9b6726]">Action required</span>}</button>)}</div>}</SectionCard>
   <SectionCard id="tomorrow" number="06" title="Tomorrow's Plan" supporting="What is planned for the next working day?" action={<AddButton onClick={()=>open("plan")}>Add planned work</AddButton>}><Rows empty="No work planned for tomorrow yet.">{dpr.tomorrowPlan.map(row=><ListRow key={row.id} icon={<ClipboardCheck size={17}/>} title={row.activity} subtitle={row.remarks} value={`${row.planned} ${row.unit}`} onClick={()=>open("plan",row.id)}/>)}</Rows></SectionCard>
   <SectionCard id="remarks" number="07" title="General Remarks" supporting="Anything else from site today?" optional><textarea value={dpr.generalRemarks} onChange={e=>update("generalRemarks",e.target.value)} rows={4} placeholder="Add an optional note…" className="w-full resize-none rounded-[10px] border border-[#e4e4e7] p-3.5 text-[15px] outline-none focus:border-[#e14d48]"/></SectionCard>
  </div><aside className="sticky top-24 hidden rounded-2xl border border-[#e4e4e7] bg-white p-5 lg:block"><p className="text-[13px] font-semibold">DPR progress</p><div className="mt-3 flex items-end justify-between"><strong className="text-[30px]">{percent}%</strong><span className="text-[12px] text-[#71717a]">{completed} of 5 required</span></div><div className="mt-3 h-2 rounded-full bg-[#f0f0f2]"><motion.div animate={{width:`${percent}%`}} className="h-full rounded-full bg-[#e14d48]"/></div><div className="mt-5 space-y-3 text-[13px]">{[["Work Done",dpr.work.length],["Manpower",dpr.manpower.length],["Materials Used",dpr.materials.length],["Site Photos",dpr.photos.length],["Tomorrow's Plan",dpr.tomorrowPlan.length]].map(([name,count])=><div key={String(name)} className="flex items-center justify-between"><span>{name}</span>{Number(count)>0?<Check size={15} className="text-[#3f8f6b]"/>:<span className="text-[#c98932]">Add</span>}</div>)}</div><button onClick={reviewNow} className="mt-6 h-12 w-full rounded-[10px] bg-[#e14d48] text-[14px] font-semibold text-white">Review DPR</button></aside></main>
  <div className="fixed inset-x-0 bottom-[calc(68px+env(safe-area-inset-bottom))] z-30 border-t border-[#e4e4e7] bg-white/95 p-3 backdrop-blur-md lg:hidden"><div className="mx-auto flex max-w-lg items-center gap-3"><span className="min-w-0 flex-1 text-[12px] text-[#71717a]"><strong className="block text-[13px] text-[#18181b]">{completed} of 5 required complete</strong>{missing.length?`${missing.length} remaining`:"Ready to submit"}</span><button onClick={reviewNow} className="h-12 rounded-[10px] bg-[#e14d48] px-5 text-[14px] font-semibold text-white">Review DPR</button></div></div>
  <EditorSheets sheet={sheet} setSheet={setSheet} editing={editing} dpr={dpr} setDpr={setDpr} remove={remove} submit={submit}/>{viewer&&<PhotoViewer photo={viewer} onClose={()=>setViewer(null)} onRemove={()=>{update("photos",dpr.photos.filter(p=>p.id!==viewer.id));setViewer(null)}}/>}
 </div>}

function AddButton({onClick,children}:{onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className="focus-ring flex h-11 shrink-0 items-center gap-1 rounded-[10px] px-2 text-[12px] font-semibold text-[#e14d48]"><Plus size={17}/><span className="hidden min-[390px]:inline">Add</span><span className="sr-only">{children}</span></button>}
function Rows({children,empty}:{children:React.ReactNode;empty:string}){return <div className="divide-y divide-[#e4e4e7]">{Array.isArray(children)&&children.length===0?<Empty text={empty}/>:children}</div>}
function Empty({text}:{text:string}){return <div className="w-full min-w-0 rounded-[10px] bg-[#f7f8fa] px-4 py-3.5 text-[13px] leading-5 text-[#71717a] [overflow-wrap:anywhere]">{text}</div>}
function ListRow({icon,title,subtitle,value,onClick}:{icon:React.ReactNode;title:string;subtitle?:string;value:string;onClick:()=>void}){return <button onClick={onClick} className="group grid min-h-16 w-full min-w-0 grid-cols-[40px_minmax(0,1fr)_auto_18px] items-center gap-2.5 py-2 text-left sm:gap-3"><span className="grid size-10 place-items-center rounded-[10px] bg-[#f4f4f5] text-[#71717a]">{icon}</span><span className="min-w-0"><strong className="block truncate text-[14px]">{title}</strong>{subtitle&&<span className="mt-0.5 block truncate text-[12px] text-[#71717a]">{subtitle}</span>}</span><span className="whitespace-nowrap text-[13px] font-medium">{value}</span><ChevronRight size={16} className="text-[#a1a1aa] group-hover:translate-x-0.5"/></button>}
function WorkRow({row,onEdit}:{row:DPRWork;onEdit:()=>void}){const progress=row.planned&&row.achieved!==null?Math.min(100,Math.round(row.achieved/row.planned*100)):0;return <button onClick={onEdit} className="w-full py-3 text-left"><div className="flex items-center justify-between"><strong className="text-[15px]">{row.activity}</strong><ChevronRight size={16} className="text-[#a1a1aa]"/></div><div className="mt-3 grid grid-cols-3 gap-3 text-[12px]"><span className="text-[#71717a]">Planned<strong className="mt-1 block text-[14px] text-[#18181b]">{row.planned} {row.unit}</strong></span><span className="text-[#71717a]">Achieved<strong className="mt-1 block text-[14px] text-[#18181b]">{row.achieved===null?"—":`${row.achieved} ${row.unit}`}</strong></span><span className="text-[#71717a]">Progress<strong className="mt-1 block text-[14px] text-[#18181b]">{row.achieved===null?"—":`${progress}%`}</strong></span></div><div className="mt-3 h-1.5 rounded-full bg-[#f0f0f2]"><motion.div animate={{width:`${progress}%`}} className="h-full rounded-full bg-[#3f8f6b]"/></div></button>}

type RemoveFn=<K extends "work"|"manpower"|"materials"|"siteVisits"|"tomorrowPlan">(key:K,id:string)=>void;
function EditorSheets({sheet,setSheet,editing,dpr,setDpr,remove,submit}:{sheet:Sheet;setSheet:(s:Sheet)=>void;editing:string|null;dpr:DPR;setDpr:React.Dispatch<React.SetStateAction<DPR>>;remove:RemoveFn;submit:()=>void}){const close=()=>setSheet(null);return <>{sheet==="work"&&<WorkForm current={dpr.work.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,work:editing?v.work.map(x=>x.id===editing?row:x):[...v.work,row]}));close()}} onDelete={editing?()=>{remove("work",editing);close()}:undefined} onClose={close}/>} {sheet==="manpower"&&<ManpowerForm current={dpr.manpower.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,manpower:editing?v.manpower.map(x=>x.id===editing?row:x):[...v.manpower,row]}));close()}} onDelete={editing?()=>{remove("manpower",editing);close()}:undefined} onClose={close}/>} {sheet==="material"&&<MaterialForm current={dpr.materials.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,materials:editing?v.materials.map(x=>x.id===editing?row:x):[...v.materials,row]}));close()}} onDelete={editing?()=>{remove("materials",editing);close()}:undefined} onClose={close}/>} {sheet==="visit"&&<VisitForm current={dpr.siteVisits.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,siteVisits:editing?v.siteVisits.map(x=>x.id===editing?row:x):[...v.siteVisits,row]}));close()}} onDelete={editing?()=>{remove("siteVisits",editing);close()}:undefined} onClose={close}/>} {sheet==="plan"&&<PlanForm current={dpr.tomorrowPlan.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,tomorrowPlan:editing?v.tomorrowPlan.map(x=>x.id===editing?row:x):[...v.tomorrowPlan,row]}));close()}} onDelete={editing?()=>{remove("tomorrowPlan",editing);close()}:undefined} onClose={close}/>}<BottomSheet open={sheet==="confirm"} title="Submit today's DPR?" onClose={close}><div className="p-5"><p className="text-[14px] leading-6 text-[#71717a]">Please confirm that today&apos;s site information is complete.</p><div className="my-5 grid grid-cols-2 gap-3 rounded-xl bg-[#f7f8fa] p-4 text-[13px]"><span>{dpr.work.length} activities</span><span>{dpr.manpower.reduce((s,r)=>s+r.inHouse+r.subcontractor,0)} manpower</span><span>{dpr.materials.length} materials</span><span>{dpr.photos.length} photos</span><span>{dpr.tomorrowPlan.length} planned activities</span></div><div className="grid grid-cols-2 gap-3"><button onClick={close} className="h-12 rounded-[10px] border border-[#e4e4e7] font-semibold">Cancel</button><button onClick={submit} className="h-12 rounded-[10px] bg-[#e14d48] font-semibold text-white">Submit DPR</button></div></div></BottomSheet></>}

type FormProps<T>={current?:T;onSave:(row:T)=>void;onDelete?:()=>void;onClose:()=>void};
function FormActions({editing,onDelete}:{editing:boolean;onDelete?:()=>void}){return <div className="sticky bottom-0 z-10 -mx-4 mt-4 border-t border-[#e4e4e7] bg-white px-4 pb-[calc(8px+env(safe-area-inset-bottom))] pt-2 sm:static sm:mx-0 sm:border-0 sm:p-0">{onDelete&&<button type="button" onClick={onDelete} className="flex h-11 w-full items-center justify-center gap-2 text-[13px] font-semibold text-[#e14d48]"><Trash2 size={15}/>Delete entry</button>}<button type="submit" className="h-[52px] w-full rounded-[11px] bg-[#e14d48] text-[16px] font-semibold text-white sm:mt-5 sm:h-[50px] sm:text-[15px]">{editing?"Update":"Add"}</button></div>}
function WorkForm({current,onSave,onDelete,onClose}:FormProps<DPRWork>){const[activity,setActivity]=useState(current?.activity??"Cable Tray Installation");const[custom,setCustom]=useState(current?.activity==="Other"?current.activity:"");const[planned,setPlanned]=useState(current?.planned??0);const[achieved,setAchieved]=useState(current?.achieved??0);const[remarks,setRemarks]=useState(current?.remarks??"");const unit=activities[activity]??"";function save(e:FormEvent){e.preventDefault();onSave({id:current?.id??id(),activity:activity==="Other"?custom:activity,unit,planned,achieved,remarks})}return <BottomSheet open title={current?"Edit Work":"Add Work"} onClose={onClose}><form onSubmit={save} className="p-5"><Select labelText="Activity" value={activity} onChange={setActivity} options={Object.keys(activities)}/>{activity==="Other"&&<Field labelText="Activity description" value={custom} onChange={setCustom} required/>}<div className="mt-4 grid grid-cols-2 gap-3"><NumberField labelText={`Planned quantity (${unit||"unit"})`} value={planned} onChange={setPlanned}/><NumberField labelText={`Achieved quantity (${unit||"unit"})`} value={achieved} onChange={setAchieved}/></div><Field labelText="Remarks — optional" value={remarks} onChange={setRemarks}/><FormActions editing={!!current} onDelete={onDelete}/></form></BottomSheet>}
function ManpowerForm({current,onSave,onDelete,onClose}:FormProps<DPRManpower>){const[role,setRole]=useState(current?.role??roles[0]);const[inHouse,setInHouse]=useState(current?.inHouse??0);const[subcontractor,setSubcontractor]=useState(current?.subcontractor??0);const[name,setName]=useState(current?.subcontractorName??"");const[remarks,setRemarks]=useState(current?.remarks??"");function save(e:FormEvent){e.preventDefault();onSave({id:current?.id??id(),role,inHouse,subcontractor,subcontractorName:name,remarks})}return <BottomSheet open title={current?"Edit Manpower":"Add Manpower"} onClose={onClose}><form onSubmit={save} className="p-5"><Select labelText="Trade / Role" value={role} onChange={setRole} options={roles}/><div className="mt-4 grid grid-cols-2 gap-3"><NumberField labelText="In-house" value={inHouse} onChange={setInHouse}/><NumberField labelText="Subcontractor" value={subcontractor} onChange={setSubcontractor}/></div>{subcontractor>0&&<Field labelText="Subcontractor name — optional" value={name} onChange={setName}/>}<Field labelText="Remarks — optional" value={remarks} onChange={setRemarks}/><div className="mt-4 flex justify-between rounded-[10px] bg-[#f7f8fa] p-3 text-[13px]"><span>Total</span><strong>{inHouse+subcontractor}</strong></div><FormActions editing={!!current} onDelete={onDelete}/></form></BottomSheet>}
function MaterialForm({current,onSave,onDelete,onClose}:FormProps<DPRMaterial>){const[material,setMaterial]=useState(current?.material??Object.keys(materialUnits)[0]);const[quantity,setQuantity]=useState(current?.quantity??0);const[remarks,setRemarks]=useState(current?.remarks??"");const unit=materialUnits[material]??"";function save(e:FormEvent){e.preventDefault();onSave({id:current?.id??id(),material,unit,quantity,remarks})}return <BottomSheet open title={current?"Edit Material":"Add Material"} onClose={onClose}><form onSubmit={save} className="p-5"><Select labelText="Material" value={material} onChange={setMaterial} options={Object.keys(materialUnits)}/><NumberField labelText={`Quantity used (${unit||"unit"})`} value={quantity} onChange={setQuantity}/><Field labelText="Remarks — optional" value={remarks} onChange={setRemarks}/><FormActions editing={!!current} onDelete={onDelete}/></form></BottomSheet>}
function VisitForm({current,onSave,onDelete,onClose}:FormProps<SiteVisit>){const[name,setName]=useState(current?.visitorName??"");const[designation,setDesignation]=useState(current?.designation??"");const[time,setTime]=useState(current?.visitTime??new Date().toTimeString().slice(0,5));const[feedback,setFeedback]=useState(current?.feedback??"");const[action,setAction]=useState(current?.actionRequired??false);function save(e:FormEvent){e.preventDefault();onSave({id:current?.id??id(),visitorName:name,designation,visitTime:time,feedback,actionRequired:action})}return <BottomSheet open title={current?"Edit Visit / Feedback":"Add Visit / Feedback"} onClose={onClose}><form onSubmit={save} className="p-5"><Field labelText="Visitor name" value={name} onChange={setName} required/><Field labelText="Designation / Role — optional" value={designation} onChange={setDesignation}/><label className="mt-4 block"><span className={label}>Visit time</span><input type="time" value={time} onChange={e=>setTime(e.target.value)} className={field}/></label><label className="mt-4 block"><span className={label}>Feedback / Observation</span><textarea required value={feedback} onChange={e=>setFeedback(e.target.value)} rows={4} className={`${field} h-auto py-3`}/></label><div className="mt-4 flex items-center justify-between"><span className="text-[13px] font-medium">Action required?</span><button type="button" onClick={()=>setAction(v=>!v)} className={`relative h-8 w-14 rounded-full transition-colors ${action?"bg-[#e14d48]":"bg-[#d4d4d8]"}`}><span className={`absolute top-1 size-6 rounded-full bg-white transition-transform ${action?"left-7":"left-1"}`}/></button></div><FormActions editing={!!current} onDelete={onDelete}/></form></BottomSheet>}
function PlanForm({current,onSave,onDelete,onClose}:FormProps<TomorrowActivity>){const[activity,setActivity]=useState(current?.activity??"Cable Pulling");const[planned,setPlanned]=useState(current?.planned??0);const[remarks,setRemarks]=useState(current?.remarks??"");const unit=activities[activity]??"";function save(e:FormEvent){e.preventDefault();onSave({id:current?.id??id(),activity,unit,planned,remarks})}return <BottomSheet open title={current?"Edit Planned Work":"Add Planned Work"} onClose={onClose}><form onSubmit={save} className="p-5"><Select labelText="Activity" value={activity} onChange={setActivity} options={Object.keys(activities)}/><NumberField labelText={`Planned quantity (${unit||"unit"})`} value={planned} onChange={setPlanned}/><Field labelText="Remarks — optional" value={remarks} onChange={setRemarks}/><FormActions editing={!!current} onDelete={onDelete}/></form></BottomSheet>}
function Select({labelText,value,onChange,options}:{labelText:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="block"><span className={label}>{labelText}</span><select value={value} onChange={e=>onChange(e.target.value)} className={field}>{options.map(option=><option key={option}>{option}</option>)}</select></label>}
function Field({labelText,value,onChange,required}:{labelText:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label className="mt-4 block"><span className={label}>{labelText}</span><input required={required} value={value} onChange={e=>onChange(e.target.value)} className={field}/></label>}
function NumberField({labelText,value,onChange}:{labelText:string;value:number;onChange:(v:number)=>void}){return <label className="mt-4 block"><span className={label}>{labelText}</span><input required min="0" inputMode="decimal" type="number" value={value} onChange={e=>onChange(Number(e.target.value))} className={field}/></label>}

function Review({dpr,missing,totalManpower,onBack,onEdit,onSubmit}:{dpr:DPR;missing:string[];totalManpower:number;onBack:()=>void;onEdit:(s:string)=>void;onSubmit:()=>void}){const rows=[{id:"work",name:"Work Done",summary:`${dpr.work.length} activities`},{id:"manpower",name:"Manpower",summary:`${totalManpower} people`},{id:"materials",name:"Materials Used",summary:`${dpr.materials.length} materials`},{id:"photos",name:"Site Photos",summary:`${dpr.photos.length} photos`},{id:"visit",name:"Site Visit / Feedback",summary:dpr.siteVisits.length?`${dpr.siteVisits.length} recorded`:"Not added · Optional"},{id:"tomorrow",name:"Tomorrow's Plan",summary:`${dpr.tomorrowPlan.length} activities`},{id:"remarks",name:"General Remarks",summary:dpr.generalRemarks||"Not added · Optional"}];const map:Record<string,string>={work:"work",manpower:"manpower",materials:"materials",photos:"photos",tomorrowPlan:"tomorrow"};return <main className="mx-auto min-h-dvh max-w-[760px] px-4 pb-12 pt-5 sm:px-6"><button onClick={onBack} className="flex h-11 items-center gap-2 text-[14px] font-semibold"><ArrowLeft size={18}/>Back to DPR</button><div className="mt-4"><h1 className="text-[26px] font-semibold tracking-[-.03em]">Review today&apos;s DPR</h1><p className="mt-2 text-[14px] text-[#71717a]">Commercial Tower · {formatDPRDate(dpr.date)}</p></div>{missing.length>0&&<section className="mt-6 rounded-2xl border border-[#f0d7b4] bg-[#fff5e5] p-5"><h2 className="text-[16px] font-semibold">{missing.length} {missing.length===1?"item needs":"items need"} attention</h2><div className="mt-3 space-y-2">{missing.map(key=><button key={key} onClick={()=>onEdit(map[key])} className="flex w-full items-center justify-between rounded-[10px] bg-white/70 p-3 text-left"><span><strong className="block text-[13px]">{key==="materials"?"Materials Used":key==="photos"?"Site Photos":key==="tomorrowPlan"?"Tomorrow's Plan":key==="work"?"Work Done":"Manpower"}</strong><span className="text-[12px] text-[#71717a]">Add at least one valid entry</span></span><ChevronRight size={16}/></button>)}</div></section>}<section className="mt-6 divide-y divide-[#e4e4e7] rounded-2xl border border-[#e4e4e7] bg-white px-5">{rows.map(row=><div key={row.id} className="flex min-h-[72px] items-center justify-between gap-4"><span><strong className="block text-[14px]">{row.name}</strong><span className="mt-1 block max-w-[440px] truncate text-[12px] text-[#71717a]">{row.summary}</span></span><button onClick={()=>onEdit(row.id)} className="h-10 px-2 text-[13px] font-semibold text-[#e14d48]">Edit</button></div>)}</section><button onClick={onSubmit} disabled={missing.length>0} className="mt-6 h-[52px] w-full rounded-[11px] bg-[#e14d48] text-[15px] font-semibold text-white disabled:cursor-not-allowed disabled:bg-[#d4d4d8]">Submit DPR</button></main>}
function Success({date,onDone}:{date:string;onDone:()=>void}){return <motion.main initial={{opacity:0}} animate={{opacity:1}} className="grid min-h-dvh place-items-center px-5"><div className="max-w-md text-center"><motion.span initial={{scale:.7,opacity:0}} animate={{scale:1,opacity:1}} transition={{duration:.65,ease:[.22,1,.36,1]}} className="mx-auto grid size-16 place-items-center rounded-full bg-[#eaf5ef] text-[#3f8f6b]"><Check size={30} strokeWidth={2.5}/></motion.span><h1 className="mt-6 text-[26px] font-semibold">DPR submitted</h1><p className="mt-3 text-[15px] font-medium">Commercial Tower</p><p className="mt-1 text-[13px] text-[#71717a]">{formatDPRDate(date)}</p><p className="mt-5 text-[14px] leading-6 text-[#71717a]">Today&apos;s site record has been submitted successfully.</p><div className="mt-7 grid grid-cols-2 gap-3"><Link href={`/dpr/today?project=commercial-tower&date=${date}`} className="grid h-12 place-items-center rounded-[10px] border border-[#e4e4e7] text-[14px] font-semibold">View DPR</Link><button onClick={onDone} className="h-12 rounded-[10px] bg-[#18181b] text-[14px] font-semibold text-white">Done</button></div></div></motion.main>}
function ReadOnlyDPR({dpr,onDeleted}:{dpr:DPR;onDeleted:()=>void}){const total=dpr.manpower.reduce((sum,row)=>sum+row.inHouse+row.subcontractor,0);const rows=[["Work Done",`${dpr.work.length} activities`],["Manpower",`${total} people`],["Materials Used",`${dpr.materials.length} materials`],["Site Photos",`${dpr.photos.length} photos`],["Site Visit / Feedback",dpr.siteVisits.length?`${dpr.siteVisits.length} recorded`:"Not recorded · Optional"],["Tomorrow's Plan",`${dpr.tomorrowPlan.length} activities`],["General Remarks",dpr.generalRemarks||"Not added · Optional"]];return <main className="mx-auto min-h-dvh max-w-[800px] px-4 py-5 sm:px-6 lg:py-8"><div className="flex items-center justify-between"><Link href="/today" className="flex h-11 items-center gap-2 text-[14px] font-semibold"><ArrowLeft size={18}/>Back</Link><DPRDeleteMenu dpr={dpr} onDeleted={onDeleted}/></div><div className="mt-4 flex items-start justify-between gap-4"><div><h1 className="text-[24px] font-semibold">Today&apos;s DPR</h1><p className="mt-1 text-[14px] text-[#71717a]">Commercial Tower · {formatDPRDate(dpr.date)}</p></div><span className="rounded-full bg-[#eaf5ef] px-3 py-1.5 text-[11px] font-semibold text-[#3f8f6b]">Submitted ✓</span></div><section className="mt-6 divide-y divide-[#e4e4e7] rounded-2xl border border-[#e4e4e7] bg-white px-5">{rows.map(([name,value])=><div key={name} className="flex min-h-[70px] items-center justify-between gap-4"><strong className="text-[14px]">{name}</strong><span className="text-right text-[13px] text-[#71717a]">{value}</span></div>)}</section><p className="mt-4 text-center text-[12px] text-[#71717a]">Submitted DPRs are read-only.</p></main>}
function PhotoViewer({photo,onClose,onRemove}:{photo:DPRPhoto;onClose:()=>void;onRemove:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="fixed inset-0 z-[80] flex flex-col bg-[#18181b]"><div className="flex h-16 items-center justify-between px-4 text-white"><span className="text-[13px]">{photo.caption||photo.name}</span><button onClick={onClose} className="grid size-11 place-items-center" aria-label="Close viewer"><X/></button></div><div className="flex min-h-0 flex-1 items-center justify-center p-4"><img src={photo.src} alt={photo.caption||"Site photo"} className="max-h-full max-w-full object-contain"/></div><div className="flex justify-end p-4 pb-[calc(16px+env(safe-area-inset-bottom))]"><button onClick={onRemove} className="flex h-11 items-center gap-2 rounded-[10px] bg-white/10 px-4 text-[13px] font-semibold text-white"><Trash2 size={15}/>Remove</button></div></motion.div>}
