"use client";
import {ArrowLeft,BriefcaseBusiness,Building2,Camera,Check,ChevronDown,ChevronRight,ClipboardCheck,House,MapPin,Minus,Package,Plus,Trash2,Users,UsersRound,X} from "lucide-react";
import {motion} from "motion/react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {ChangeEvent,FormEvent,useCallback,useEffect,useRef,useState} from "react";
import {BottomSheet} from "@/components/dpr/bottom-sheet";
import {DPRDeleteMenu} from "@/components/dpr/dpr-delete-menu";
import {ManpowerScreen} from "@/components/dpr/manpower-screen";
import {MaterialsScreen} from "@/components/dpr/materials-screen";
import {SitePhotosScreen} from "@/components/dpr/site-photos-screen";
import {SiteVisitForm,SiteVisitScreen} from "@/components/dpr/site-visit-screen";
import {MobileOptionPicker} from "@/components/dpr/mobile-option-picker";
import {StoredPhoto} from "@/components/dpr/stored-photo";
import {TomorrowPlanScreen} from "@/components/dpr/tomorrow-plan-screen";
import {SectionCard} from "@/components/dpr/section-card";
import {WorkDoneScreen} from "@/components/dpr/work-done-screen";
import {completedRequired,completionPercent,formatDPRDate,loadDPRRecords,missingSections,recordKey,replaceDPRRecords,saveDPR,todayISO} from "@/lib/dpr";
import {deleteStoredPhotoIfUnreferenced,migrateEmbeddedPhotoRecords,savePhotoDataUrl} from "@/lib/photo-store";
import type {DPR,DPRManpower,DPRMaterial,DPRPhoto,DPRWork,SiteVisit,TomorrowActivity} from "@/types";

type Sheet="work"|"manpower"|"material"|"visit"|"plan"|"confirm"|null;
const activities:Record<string,string>={"Cable Tray Installation":"m","Conduit Laying":"m","Cable Pulling":"m","Panel Installation":"nos","Earthing":"m","Light Fixture Installation":"nos","Testing & Commissioning":"job","Other":""};
const materialUnits:Record<string,string>={"Electrical Cable":"m","Cable Tray":"m","PVC Conduit":"m","GI Conduit":"m","Earthing Cable":"m","Light Fixture":"nos","Distribution Board":"nos","Cable Gland":"nos","Other":""};
const roles=["Electrician","Helper","Supervisor","Technician","Welder","Plumber","Other"];
const workUnits=["m","m²","m³","nos","kg","lot","job"];
const field="h-12 w-full rounded-[10px] border border-[#e4e4e7] bg-white px-3.5 text-[15px] outline-none transition-colors focus:border-[#e14d48]";
const label="mb-2 block text-[14px] font-medium";
const id=()=>crypto.randomUUID();

export function DPREditor({projectId,date}:{projectId:string;date:string}){const router=useRouter();const[dpr,setDpr]=useState<DPR>({id:"",projectId,date,status:"draft",work:[],manpower:[],materials:[],photos:[],siteVisits:[],tomorrowPlan:[],generalRemarks:"",updatedAt:""});const[ready,setReady]=useState(false);const[exists,setExists]=useState(false);const[saveState,setSaveState]=useState<"saving"|"saved">("saved");const[sheet,setSheet]=useState<Sheet>(null);const[editing,setEditing]=useState<string|null>(null);const[review,setReview]=useState(false);const[success,setSuccess]=useState(false);const[viewer,setViewer]=useState<DPRPhoto|null>(null);const[replaceId,setReplaceId]=useState<string|null>(null);const[focusedWork,setFocusedWork]=useState(false);const[focusedManpower,setFocusedManpower]=useState(false);const[focusedMaterials,setFocusedMaterials]=useState(false);const[focusedPhotos,setFocusedPhotos]=useState(false);const[focusedVisit,setFocusedVisit]=useState(false);const[focusedTomorrow,setFocusedTomorrow]=useState(false);const galleryRef=useRef<HTMLInputElement>(null);const cameraRef=useRef<HTMLInputElement>(null);
 const[saveFailed,setSaveFailed]=useState(false);const latestDprRef=useRef(dpr);const submitLockRef=useRef(false);
 useEffect(()=>{latestDprRef.current=dpr},[dpr]);
 useEffect(()=>{let cancelled=false;const timer=window.setTimeout(async()=>{let records=loadDPRRecords();try{const migration=await migrateEmbeddedPhotoRecords(records);records=migration.records;if(migration.changed)replaceDPRRecords(records)}catch{}const stored=records[recordKey(projectId,date)];if(stored&&!cancelled){setDpr(stored);setExists(true)}if(!cancelled)setReady(true)},0);return()=>{cancelled=true;window.clearTimeout(timer)}},[projectId,date]);
 useEffect(()=>{if(!ready||!exists||dpr.status==="submitted")return;const savingTimer=window.setTimeout(()=>{setSaveFailed(false);setSaveState("saving")},0);const timer=window.setTimeout(()=>{try{saveDPR(dpr);setSaveState("saved")}catch(error){console.error("Could not autosave DPR",error);setSaveFailed(true)}},450);return()=>{window.clearTimeout(savingTimer);window.clearTimeout(timer)}},[dpr,ready,exists]);
 useEffect(()=>{if(!ready||!exists)return;return()=>{const latest=latestDprRef.current;if(latest.status!=="submitted")try{saveDPR(latest)}catch(error){console.error("Could not flush DPR changes",error)}}},[ready,exists]);
 useEffect(()=>{if(!ready)return;const syncHash=()=>{setFocusedWork(location.hash==="#work");setFocusedManpower(location.hash==="#manpower");setFocusedMaterials(location.hash==="#materials");setFocusedPhotos(location.hash==="#photos");setFocusedVisit(location.hash==="#visit");setFocusedTomorrow(location.hash==="#tomorrow")};syncHash();window.addEventListener("hashchange",syncHash);if(location.hash&&!['#work','#manpower','#materials','#photos','#visit','#tomorrow'].includes(location.hash))window.setTimeout(()=>document.querySelector(location.hash)?.scrollIntoView({behavior:"smooth",block:"start"}),150);return()=>window.removeEventListener("hashchange",syncHash)},[ready]);
 const update=useCallback(<K extends keyof DPR>(key:K,value:DPR[K])=>setDpr(current=>({...current,[key]:value})),[]);
 const completed=completedRequired(dpr),percent=completionPercent(dpr),missing=missingSections(dpr);
 const totalManpower=dpr.manpower.reduce((sum,row)=>sum+row.inHouse+row.subcontractor,0);
 const open=(type:Sheet,itemId?:string)=>{setEditing(itemId??null);setSheet(type)};
 const remove=<K extends "work"|"manpower"|"materials"|"siteVisits"|"tomorrowPlan">(key:K,itemId:string)=>{if(window.confirm("Remove this entry?"))setDpr(current=>({...current,[key]:current[key].filter(item=>item.id!==itemId)}))};
 const photoFiles=(event:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files??[]);files.forEach(file=>{const reader=new FileReader();reader.onload=async()=>{const photoId=replaceId??id();try{const previous=replaceId?dpr.photos.find(item=>item.id===replaceId):undefined;const src=await savePhotoDataUrl(photoId,String(reader.result));const photo:DPRPhoto={id:photoId,src,name:file.name};setDpr(current=>({...current,photos:replaceId?current.photos.map(item=>item.id===replaceId?photo:item):[...current.photos,photo]}));setReplaceId(null);if(previous)window.setTimeout(()=>void deleteStoredPhotoIfUnreferenced(previous.src),700)}catch{}};reader.readAsDataURL(file)});event.target.value=""};
 const reviewNow=()=>{setReview(true);window.scrollTo({top:0,behavior:"smooth"})};
 const submit=()=>{if(submitLockRef.current)return;if(missing.length){setSheet(null);setReview(true);return}submitLockRef.current=true;const next={...dpr,status:"submitted" as const,updatedAt:new Date().toISOString()};try{saveDPR(next)}catch(error){submitLockRef.current=false;console.error("Could not submit DPR",error);setSaveFailed(true);setSheet(null);return}setDpr(next);setSheet(null);setSuccess(true)};
 const afterDelete=()=>router.replace(date===todayISO()?"/today":`/calendar?date=${date}`);
 const continueToManpower=()=>{setFocusedWork(false);setFocusedManpower(true);window.history.replaceState(null,"",`${location.pathname}${location.search}#manpower`);window.scrollTo({top:0,behavior:"smooth"})};
 const continueToMaterials=()=>{setFocusedManpower(false);setFocusedMaterials(true);window.history.replaceState(null,"",`${location.pathname}${location.search}#materials`);window.scrollTo({top:0,behavior:"smooth"})};
 const continueToPhotos=()=>{setFocusedMaterials(false);setFocusedPhotos(true);window.history.replaceState(null,"",`${location.pathname}${location.search}#photos`);window.scrollTo({top:0,behavior:"smooth"})};
 const continueToVisit=()=>{setFocusedPhotos(false);setFocusedVisit(true);window.history.replaceState(null,"",`${location.pathname}${location.search}#visit`);window.scrollTo({top:0,behavior:"smooth"})};
 const continueToTomorrow=()=>{setFocusedVisit(false);setFocusedTomorrow(true);window.history.replaceState(null,"",`${location.pathname}${location.search}#tomorrow`);window.scrollTo({top:0,behavior:"smooth"})};
 const reviewFromTomorrow=()=>{setFocusedTomorrow(false);setReview(true);window.history.replaceState(null,"",`${location.pathname}${location.search}`);window.scrollTo({top:0,behavior:"smooth"})};
 if(!ready)return <div className="grid min-h-[70dvh] place-items-center text-[14px] text-[#71717a]">Opening today&apos;s DPR…</div>;
 if(!exists)return <div className="grid min-h-[70dvh] place-items-center px-4"><div className="text-center"><h1 className="text-[20px] font-semibold">No DPR for this date</h1><p className="mt-2 text-[14px] text-[#71717a]">Create it from Today or Calendar first.</p><Link href="/calendar" className="mt-5 inline-grid h-11 place-items-center rounded-[10px] bg-[#18181b] px-5 text-[14px] font-semibold text-white">Back to calendar</Link></div></div>;
 if(dpr.status==="submitted")return <ReadOnlyDPR dpr={dpr} onDeleted={afterDelete}/>;
 if(success)return <Success date={date} onDone={()=>router.push("/today")}/>;
 if(review)return <Review dpr={dpr} missing={missing} totalManpower={totalManpower} onBack={()=>setReview(false)} onEdit={section=>{setReview(false);window.setTimeout(()=>document.getElementById(section)?.scrollIntoView({behavior:"smooth"}),50)}} onSubmit={()=>setSheet("confirm")}/>;
 if(focusedWork)return <><WorkDoneScreen dpr={dpr} saveState={saveState} completed={completed} percent={percent} onAdd={()=>open("work")} onEdit={itemId=>open("work",itemId)} onDuplicate={row=>setDpr(current=>({...current,work:[...current.work,{...row,id:id()}]}))} onDelete={itemId=>setDpr(current=>({...current,work:current.work.filter(row=>row.id!==itemId)}))} onNext={continueToManpower} onDprDeleted={afterDelete}/><EditorSheets sheet={sheet} setSheet={setSheet} editing={editing} dpr={dpr} setDpr={setDpr} remove={remove} submit={submit}/>{saveFailed&&<SaveErrorNotice/>}</>;
 if(focusedManpower)return <><ManpowerScreen dpr={dpr} saveState={saveState} completed={completed} percent={percent} onAdd={()=>open("manpower")} onEdit={itemId=>open("manpower",itemId)} onDuplicate={row=>setDpr(current=>({...current,manpower:[...current.manpower,{...row,id:id()}]}))} onDelete={itemId=>setDpr(current=>({...current,manpower:current.manpower.filter(row=>row.id!==itemId)}))} onNext={continueToMaterials} onDprDeleted={afterDelete}/><EditorSheets sheet={sheet} setSheet={setSheet} editing={editing} dpr={dpr} setDpr={setDpr} remove={remove} submit={submit}/>{saveFailed&&<SaveErrorNotice/>}</>;
 if(focusedMaterials)return <><MaterialsScreen dpr={dpr} saveState={saveState} completed={completed} percent={percent} onAdd={()=>open("material")} onEdit={itemId=>open("material",itemId)} onDuplicate={row=>setDpr(current=>({...current,materials:[...current.materials,{...row,id:id()}]}))} onDelete={itemId=>setDpr(current=>({...current,materials:current.materials.filter(row=>row.id!==itemId)}))} onNext={continueToPhotos} onDprDeleted={afterDelete}/><EditorSheets sheet={sheet} setSheet={setSheet} editing={editing} dpr={dpr} setDpr={setDpr} remove={remove} submit={submit}/>{saveFailed&&<SaveErrorNotice/>}</>;
 if(focusedPhotos)return <><SitePhotosScreen dpr={dpr} saveState={saveState} completed={completed} percent={percent} onAdd={photos=>setDpr(current=>({...current,photos:[...current.photos,...photos]}))} onCaption={(photoId,caption)=>setDpr(current=>({...current,photos:current.photos.map(photo=>photo.id===photoId?{...photo,caption}:photo)}))} onDelete={photoId=>setDpr(current=>({...current,photos:current.photos.filter(photo=>photo.id!==photoId)}))} onNext={continueToVisit} onDprDeleted={afterDelete}/>{saveFailed&&<SaveErrorNotice/>}</>;
 if(focusedVisit)return <><SiteVisitScreen dpr={dpr} saveState={saveState} completed={completed} percent={percent} onUpsert={visit=>setDpr(current=>({...current,siteVisits:current.siteVisits.some(item=>item.id===visit.id)?current.siteVisits.map(item=>item.id===visit.id?visit:item):[...current.siteVisits,visit]}))} onDelete={visitId=>setDpr(current=>({...current,siteVisits:current.siteVisits.filter(visit=>visit.id!==visitId)}))} onNext={continueToTomorrow} onDprDeleted={afterDelete}/>{saveFailed&&<SaveErrorNotice/>}</>;
 if(focusedTomorrow)return <><TomorrowPlanScreen dpr={dpr} saveState={saveState} completed={completed} percent={percent} onUpsert={activity=>setDpr(current=>({...current,tomorrowPlan:current.tomorrowPlan.some(item=>item.id===activity.id)?current.tomorrowPlan.map(item=>item.id===activity.id?activity:item):[...current.tomorrowPlan,activity]}))} onDuplicate={activity=>setDpr(current=>({...current,tomorrowPlan:[...current.tomorrowPlan,{...activity,id:id()}]}))} onDelete={activityId=>setDpr(current=>({...current,tomorrowPlan:current.tomorrowPlan.filter(activity=>activity.id!==activityId)}))} onReview={reviewFromTomorrow} onDprDeleted={afterDelete}/>{saveFailed&&<SaveErrorNotice/>}</>;
 return <div className="dpr-sticky-action-space min-h-dvh lg:pb-12">{saveFailed&&<SaveErrorNotice/>}<header className="sticky top-0 z-40 border-b border-[#e4e4e7] bg-white/95 backdrop-blur-md"><div className="mx-auto flex h-16 max-w-[1180px] items-center justify-between px-4 sm:px-6"><Link href="/today" className="focus-ring flex h-11 items-center gap-2 rounded-[10px] text-[15px] font-semibold"><ArrowLeft size={19}/><span>Today&apos;s DPR</span></Link><div className="flex items-center gap-2"><motion.span key={saveState} initial={{opacity:0,y:2}} animate={{opacity:1,y:0}} className="text-[13px] text-[#71717a]">{saveState==="saving"?"Saving…":"Saved ✓"}</motion.span><DPRDeleteMenu dpr={dpr} onDeleted={afterDelete}/></div></div></header>
  <main className="mx-auto grid w-full min-w-0 max-w-[1180px] gap-5 px-4 py-4 sm:px-6 lg:grid-cols-[minmax(0,800px)_300px] lg:items-start lg:gap-6 lg:py-8"><div className="min-w-0 space-y-3 lg:space-y-5"><div className="mb-5 min-w-0"><div className="flex min-w-0 items-center gap-2"><h1 className="min-w-0 truncate text-[24px] font-semibold sm:text-[20px]">Commercial Tower</h1><span className="shrink-0 rounded-full bg-[#fdeceb] px-2.5 py-1 text-[11px] font-semibold text-[#c43f3b]">Draft</span></div><p className="mt-1 text-[14px] text-[#71717a]">{formatDPRDate(date)} · MEP Works</p></div>
   <nav className="hidden gap-2 lg:flex" aria-label="DPR sections">{[["work","Work"],["manpower","Manpower"],["materials","Materials"],["photos","Photos"],["visit","Visit"],["tomorrow","Tomorrow"]].map(([anchor,name],index)=>{const done=index===4?dpr.siteVisits.length>0:index===0?dpr.work.length>0:index===1?dpr.manpower.length>0:index===2?dpr.materials.length>0:index===3?dpr.photos.length>0:dpr.tomorrowPlan.length>0;return <a key={anchor} href={`#${anchor}`} className="focus-ring flex h-10 shrink-0 items-center gap-1.5 rounded-full border border-[#e4e4e7] bg-white px-3 text-[12px] font-medium"><span className={`grid size-4 place-items-center rounded-full text-[9px] ${done?"bg-[#eaf5ef] text-[#3f8f6b]":"bg-[#f4f4f5] text-[#a1a1aa]"}`}>{done?<Check size={10}/>:index===4?"○":"·"}</span>{name}</a>})}</nav><div className="rounded-xl border border-[#e4e4e7] bg-white p-4 lg:hidden"><div className="flex items-center justify-between text-[13px]"><span className="font-medium">DPR progress</span><strong>{completed} / 5</strong></div><p className="mt-1 text-[12px] text-[#71717a]">{completed} of 5 required sections complete</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#f0f0f2]"><motion.div animate={{width:`${percent}%`}} className="h-full rounded-full bg-[#e14d48]"/></div></div>
   <SectionCard id="work" number="01" title="Work Done" supporting="What was done today?" action={<AddButton onClick={()=>open("work")}>Add activity</AddButton>}><Rows empty="No work added yet.">{dpr.work.map(row=><WorkRow key={row.id} row={row} onEdit={()=>open("work",row.id)}/>)}</Rows></SectionCard>
   <SectionCard id="manpower" number="02" title="Manpower" supporting="Who worked on site today?" action={<AddButton onClick={()=>open("manpower")}>Add manpower</AddButton>}><Rows empty="No manpower added yet.">{dpr.manpower.map(row=><ListRow key={row.id} icon={<Users size={17}/>} title={row.role} value={`${row.inHouse+row.subcontractor}`} onClick={()=>open("manpower",row.id)}/>)}</Rows>{dpr.manpower.length>0&&<div className="mt-4 flex justify-between border-t border-[#e4e4e7] pt-4 text-[14px] font-semibold"><span>Total manpower</span><span>{totalManpower}</span></div>}</SectionCard>
   <SectionCard id="materials" number="03" title="Materials Used" supporting="What materials were used today?" action={<AddButton onClick={()=>open("material")}>Add material</AddButton>}><Rows empty="No materials added yet.">{dpr.materials.map(row=><ListRow key={row.id} icon={<Package size={17}/>} title={row.material} subtitle={row.remarks} value={`${row.quantity} ${row.unit}`} onClick={()=>open("material",row.id)}/>)}</Rows></SectionCard>
   <SectionCard id="photos" number="04" title="Site Photos" supporting="Add photos showing today's site progress."><input ref={cameraRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={photoFiles}/><input ref={galleryRef} className="hidden" type="file" accept="image/*" multiple onChange={photoFiles}/>{dpr.photos.length===0?<div className="rounded-xl border border-dashed border-[#cfcfd5] bg-[#fafafa] p-7 text-center"><span className="mx-auto grid size-12 place-items-center rounded-xl bg-[#fdeceb] text-[#e14d48]"><Camera size={21}/></span><p className="mt-4 text-[15px] font-semibold">Show today&apos;s progress</p><p className="mt-1 text-[13px] text-[#71717a]">Take a site photo or choose one from your gallery.</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><button onClick={()=>cameraRef.current?.click()} className="focus-ring h-12 rounded-[10px] bg-[#e14d48] text-[14px] font-semibold text-white">Take photo</button><button onClick={()=>galleryRef.current?.click()} className="focus-ring h-12 rounded-[10px] border border-[#e4e4e7] bg-white text-[14px] font-semibold">Choose from gallery</button></div></div>:<><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{dpr.photos.map(photo=><motion.div initial={{opacity:0,scale:.98}} animate={{opacity:1,scale:1}} key={photo.id} className="overflow-hidden rounded-xl border border-[#e4e4e7]"><button onClick={()=>setViewer(photo)} className="block w-full cursor-zoom-in"><StoredPhoto src={photo.src} alt={photo.caption||"Site progress"} className="aspect-[4/3] w-full object-cover"/></button><div className="flex items-center justify-between p-2"><button onClick={()=>setViewer(photo)} className="text-[12px] font-medium">View</button><div className="flex gap-1"><button onClick={()=>{setReplaceId(photo.id);galleryRef.current?.click()}} className="h-8 px-2 text-[11px] text-[#71717a]">Replace</button><button onClick={()=>{const src=photo.src;update("photos",dpr.photos.filter(item=>item.id!==photo.id));window.setTimeout(()=>void deleteStoredPhotoIfUnreferenced(src),700)}} className="grid size-8 place-items-center text-[#e14d48]" aria-label="Remove photo"><Trash2 size={14}/></button></div></div></motion.div>)}</div><button onClick={()=>cameraRef.current?.click()} className="mt-4 flex h-11 items-center gap-2 text-[13px] font-semibold text-[#e14d48]"><Plus size={16}/>Add another photo</button></>}</SectionCard>
   <SectionCard id="visit" number="05" title="Site Visit / Feedback" supporting="Record feedback if a senior person or client visited today." optional action={<AddButton onClick={()=>open("visit")}>Add visit</AddButton>}>{dpr.siteVisits.length===0?<Empty text="No site visit recorded today."/>:<div className="space-y-4">{dpr.siteVisits.map(visit=><button key={visit.id} onClick={()=>open("visit",visit.id)} className="w-full border-l-2 border-[#e14d48] pl-4 text-left"><span className="text-[12px] font-semibold text-[#71717a]">{visit.visitTime}</span><p className="mt-1 text-[15px] font-semibold">{visit.visitorName} <span className="font-normal text-[#71717a]">{visit.designation}</span></p><p className="mt-2 text-[13px] leading-5 text-[#71717a]">{visit.feedback}</p>{visit.actionRequired&&<span className="mt-2 inline-flex rounded-full bg-[#fff5e5] px-2 py-1 text-[10px] font-semibold text-[#9b6726]">Action required</span>}</button>)}</div>}</SectionCard>
   <SectionCard id="tomorrow" number="06" title="Tomorrow's Plan" supporting="What is planned for the next working day?" action={<AddButton onClick={()=>open("plan")}>Add planned work</AddButton>}><Rows empty="No work planned for tomorrow yet.">{dpr.tomorrowPlan.map(row=><ListRow key={row.id} icon={<ClipboardCheck size={17}/>} title={row.activity} subtitle={row.remarks} value={`${row.planned} ${row.unit}`} onClick={()=>open("plan",row.id)}/>)}</Rows></SectionCard>
   <SectionCard id="remarks" number="07" title="General Remarks" supporting="Anything else from site today?" optional><textarea value={dpr.generalRemarks} onChange={e=>update("generalRemarks",e.target.value)} rows={4} placeholder="Add an optional note…" className="w-full resize-none rounded-[10px] border border-[#e4e4e7] p-3.5 text-[15px] outline-none focus:border-[#e14d48]"/></SectionCard>
  </div><aside className="sticky top-24 hidden rounded-2xl border border-[#e4e4e7] bg-white p-5 lg:block"><p className="text-[13px] font-semibold">DPR progress</p><div className="mt-3 flex items-end justify-between"><strong className="text-[30px]">{percent}%</strong><span className="text-[12px] text-[#71717a]">{completed} of 5 required</span></div><div className="mt-3 h-2 rounded-full bg-[#f0f0f2]"><motion.div animate={{width:`${percent}%`}} className="h-full rounded-full bg-[#e14d48]"/></div><div className="mt-5 space-y-3 text-[13px]">{[["Work Done",dpr.work.length],["Manpower",dpr.manpower.length],["Materials Used",dpr.materials.length],["Site Photos",dpr.photos.length],["Tomorrow's Plan",dpr.tomorrowPlan.length]].map(([name,count])=><div key={String(name)} className="flex items-center justify-between"><span>{name}</span>{Number(count)>0?<Check size={15} className="text-[#3f8f6b]"/>:<span className="text-[#c98932]">Add</span>}</div>)}</div><button onClick={reviewNow} className="mt-6 h-12 w-full rounded-[10px] bg-[#e14d48] text-[14px] font-semibold text-white">Review DPR</button></aside></main>
  <div className="fixed inset-x-0 bottom-[calc(68px+env(safe-area-inset-bottom))] z-30 border-t border-[#e4e4e7] bg-white/95 p-3 backdrop-blur-md lg:hidden"><div className="mx-auto flex max-w-lg items-center gap-3"><span className="min-w-0 flex-1 text-[12px] text-[#71717a]"><strong className="block text-[13px] text-[#18181b]">{completed} of 5 required complete</strong>{missing.length?`${missing.length} remaining`:"Ready to submit"}</span><button onClick={reviewNow} className="h-12 rounded-[10px] bg-[#e14d48] px-5 text-[14px] font-semibold text-white">Review DPR</button></div></div>
  <EditorSheets sheet={sheet} setSheet={setSheet} editing={editing} dpr={dpr} setDpr={setDpr} remove={remove} submit={submit}/>{viewer&&<PhotoViewer photo={viewer} onClose={()=>setViewer(null)} onRemove={()=>{const src=viewer.src;update("photos",dpr.photos.filter(p=>p.id!==viewer.id));setViewer(null);window.setTimeout(()=>void deleteStoredPhotoIfUnreferenced(src),700)}}/>}
 </div>}

function AddButton({onClick,children}:{onClick:()=>void;children:React.ReactNode}){return <button onClick={onClick} className="focus-ring flex h-11 shrink-0 items-center gap-1 rounded-[10px] px-2 text-[12px] font-semibold text-[#e14d48]"><Plus size={17}/><span className="hidden min-[390px]:inline">Add</span><span className="sr-only">{children}</span></button>}
function Rows({children,empty}:{children:React.ReactNode;empty:string}){return <div className="divide-y divide-[#e4e4e7]">{Array.isArray(children)&&children.length===0?<Empty text={empty}/>:children}</div>}
function Empty({text}:{text:string}){return <div className="w-full min-w-0 rounded-[10px] bg-[#f7f8fa] px-4 py-3.5 text-[13px] leading-5 text-[#71717a] [overflow-wrap:anywhere]">{text}</div>}
function ListRow({icon,title,subtitle,value,onClick}:{icon:React.ReactNode;title:string;subtitle?:string;value:string;onClick:()=>void}){return <button onClick={onClick} className="group grid min-h-16 w-full min-w-0 grid-cols-[40px_minmax(0,1fr)_auto_18px] items-center gap-2.5 py-2 text-left sm:gap-3"><span className="grid size-10 place-items-center rounded-[10px] bg-[#f4f4f5] text-[#71717a]">{icon}</span><span className="min-w-0"><strong className="block truncate text-[14px]">{title}</strong>{subtitle&&<span className="mt-0.5 block truncate text-[12px] text-[#71717a]">{subtitle}</span>}</span><span className="whitespace-nowrap text-[13px] font-medium">{value}</span><ChevronRight size={16} className="text-[#a1a1aa] group-hover:translate-x-0.5"/></button>}
function WorkRow({row,onEdit}:{row:DPRWork;onEdit:()=>void}){const progress=row.planned&&row.achieved!==null?Math.min(100,Math.round(row.achieved/row.planned*100)):0;return <button onClick={onEdit} className="w-full py-3 text-left"><div className="flex items-center justify-between"><strong className="text-[15px]">{row.activity}</strong><ChevronRight size={16} className="text-[#a1a1aa]"/></div><div className="mt-3 grid grid-cols-3 gap-3 text-[12px]"><span className="text-[#71717a]">Planned<strong className="mt-1 block text-[14px] text-[#18181b]">{row.planned} {row.unit}</strong></span><span className="text-[#71717a]">Achieved<strong className="mt-1 block text-[14px] text-[#18181b]">{row.achieved===null?"—":`${row.achieved} ${row.unit}`}</strong></span><span className="text-[#71717a]">Progress<strong className="mt-1 block text-[14px] text-[#18181b]">{row.achieved===null?"—":`${progress}%`}</strong></span></div><div className="mt-3 h-1.5 rounded-full bg-[#f0f0f2]"><motion.div animate={{width:`${progress}%`}} className="h-full rounded-full bg-[#3f8f6b]"/></div></button>}

type RemoveFn=<K extends "work"|"manpower"|"materials"|"siteVisits"|"tomorrowPlan">(key:K,id:string)=>void;
function EditorSheets({sheet,setSheet,editing,dpr,setDpr,remove,submit}:{sheet:Sheet;setSheet:(s:Sheet)=>void;editing:string|null;dpr:DPR;setDpr:React.Dispatch<React.SetStateAction<DPR>>;remove:RemoveFn;submit:()=>void}){const close=()=>setSheet(null);return <>{sheet==="work"&&<WorkForm current={dpr.work.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,work:editing?v.work.map(x=>x.id===editing?row:x):[...v.work,row]}));close()}} onDelete={editing?()=>{remove("work",editing);close()}:undefined} onClose={close}/>} {sheet==="manpower"&&<ManpowerForm current={dpr.manpower.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,manpower:editing?v.manpower.map(x=>x.id===editing?row:x):[...v.manpower,row]}));close()}} onDelete={editing?()=>{remove("manpower",editing);close()}:undefined} onClose={close}/>} {sheet==="material"&&<MaterialForm current={dpr.materials.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,materials:editing?v.materials.map(x=>x.id===editing?row:x):[...v.materials,row]}));close()}} onDelete={editing?()=>{remove("materials",editing);close()}:undefined} onClose={close}/>} {sheet==="visit"&&<VisitForm current={dpr.siteVisits.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,siteVisits:editing?v.siteVisits.map(x=>x.id===editing?row:x):[...v.siteVisits,row]}));close()}} onDelete={editing?()=>{remove("siteVisits",editing);close()}:undefined} onClose={close}/>} {sheet==="plan"&&<PlanForm current={dpr.tomorrowPlan.find(x=>x.id===editing)} onSave={row=>{setDpr(v=>({...v,tomorrowPlan:editing?v.tomorrowPlan.map(x=>x.id===editing?row:x):[...v.tomorrowPlan,row]}));close()}} onDelete={editing?()=>{remove("tomorrowPlan",editing);close()}:undefined} onClose={close}/>}<BottomSheet open={sheet==="confirm"} title="Submit today's DPR?" onClose={close}><div className="p-5"><p className="text-[14px] leading-6 text-[#71717a]">Please confirm that today&apos;s site information is complete.</p><div className="my-5 grid grid-cols-2 gap-3 rounded-xl bg-[#f7f8fa] p-4 text-[13px]"><span>{dpr.work.length} activities</span><span>{dpr.manpower.reduce((s,r)=>s+r.inHouse+r.subcontractor,0)} manpower</span><span>{dpr.materials.length} materials</span><span>{dpr.photos.length} photos</span><span>{dpr.tomorrowPlan.length} planned activities</span></div><div className="grid grid-cols-2 gap-3"><button onClick={close} className="h-12 rounded-[10px] border border-[#e4e4e7] font-semibold">Cancel</button><button onClick={submit} className="h-12 rounded-[10px] bg-[#e14d48] font-semibold text-white">Submit DPR</button></div></div></BottomSheet></>}

type FormProps<T>={current?:T;onSave:(row:T)=>void;onDelete?:()=>void;onClose:()=>void};
function SheetFormFooter({formId,label,onDelete,deleteLabel="Delete entry"}:{formId:string;label:string;onDelete?:()=>void;deleteLabel?:string}){return <>{onDelete&&<button type="button" onClick={onDelete} className="mb-1 flex min-h-11 w-full items-center justify-center gap-2 text-[13px] font-semibold text-[#d9423d]"><Trash2 size={15}/>{deleteLabel}</button>}<button form={formId} type="submit" className="h-[54px] w-full rounded-[14px] bg-[#ed4f49] text-[16px] font-bold text-white shadow-[0_8px_18px_rgba(237,79,73,.18)] transition-transform active:scale-[.98]">{label}</button></>}
function WorkForm({current,onSave,onDelete,onClose}:FormProps<DPRWork>){
 const knownActivity=current&&current.activity in activities?current.activity:"Other";const[activity,setActivity]=useState(current?knownActivity:"Cable Tray Installation");const[custom,setCustom]=useState(current&&knownActivity==="Other"?current.activity:"");const[location,setLocation]=useState(current?.location??"");const[unit,setUnit]=useState(current?.unit??activities[activity]??"m");const[planned,setPlanned]=useState(current?String(current.planned):"");const[achieved,setAchieved]=useState(current?.achieved===null||current?.achieved===undefined?"":String(current.achieved));const[remarks,setRemarks]=useState(current?.remarks??"");const[errors,setErrors]=useState<Record<string,string>>({});
 const customRef=useRef<HTMLInputElement>(null),locationRef=useRef<HTMLInputElement>(null),plannedRef=useRef<HTMLInputElement>(null),achievedRef=useRef<HTMLInputElement>(null),noteRef=useRef<HTMLTextAreaElement>(null);
 const plannedNumber=Number(planned),achievedNumber=Number(achieved);const hasProgress=planned!==""&&plannedNumber>0&&achieved!=="";const progress=hasProgress?Math.min(100,Math.max(0,Math.round(achievedNumber/plannedNumber*100))):0;const status=hasProgress?(achievedNumber>=plannedNumber?"Completed":"In Progress"):"Add quantities";
 const clearError=(key:string)=>setErrors(value=>{if(!value[key])return value;const next={...value};delete next[key];return next});
 const changeActivity=(value:string)=>{setActivity(value);clearError("activity");const suggested=activities[value];if(suggested)setUnit(suggested)};
 const nextOnEnter=(event:React.KeyboardEvent<HTMLInputElement|HTMLSelectElement>,target:React.RefObject<HTMLInputElement|null>)=>{if(event.key!=="Enter")return;event.preventDefault();target.current?.focus()};
 function save(event:FormEvent){event.preventDefault();const nextErrors:Record<string,string>={};const activityName=activity==="Other"?custom.trim():activity;if(!activityName)nextErrors.activity="Activity is required";if(planned===""||!Number.isFinite(plannedNumber)||plannedNumber<=0)nextErrors.planned="Enter a planned quantity greater than 0";if(achieved===""||!Number.isFinite(achievedNumber)||achievedNumber<0)nextErrors.achieved="Enter the achieved quantity";if(!unit)nextErrors.unit="Unit is required";setErrors(nextErrors);if(Object.keys(nextErrors).length)return;onSave({id:current?.id??id(),activity:activityName,location:location.trim(),unit,planned:plannedNumber,achieved:achievedNumber,remarks:remarks.trim()})}
 return <BottomSheet open mobileTall title={current?"Edit Work Activity":"Add Work Activity"} description="Record today's site progress." onClose={onClose} footer={<SheetFormFooter formId="work-activity-form" label={current?"Save Changes":"Add Activity"} onDelete={onDelete} deleteLabel="Delete activity"/>}><form id="work-activity-form" onSubmit={save} noValidate className="min-w-0 px-5 py-5">
  <div className="block min-w-0"><span className="mb-2 block text-[14px] font-bold">What work was done? <span className="text-[#e14d48]">*</span></span><MobileOptionPicker label="Activity" value={activity} options={Object.keys(activities)} onChange={changeActivity} error={errors.activity} icon={<BriefcaseBusiness size={19} className="text-[#e44f49]"/>}/>{errors.activity&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.activity}</span>}</div>
  {activity==="Other"&&<label className="mt-4 block"><span className="mb-2 block text-[13px] font-semibold">Activity name <span className="text-[#e14d48]">*</span></span><input ref={customRef} value={custom} onChange={e=>{setCustom(e.target.value);clearError("activity")}} onKeyDown={e=>nextOnEnter(e,locationRef)} enterKeyHint="next" placeholder="Describe the activity" className="h-13 w-full min-w-0 rounded-[14px] border border-[#dfe2e8] px-4 text-[15px] outline-none transition-colors focus:border-[#e14d48]"/></label>}
  <label className="mt-5 block"><span className="mb-2 block text-[14px] font-bold">Where? <span className="font-medium text-[#858a97]">(optional)</span></span><span className="relative block"><MapPin size={18} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-[#858b99]"/><input ref={locationRef} value={location} onChange={e=>setLocation(e.target.value)} onKeyDown={e=>nextOnEnter(e,plannedRef)} enterKeyHint="next" placeholder="e.g. 3rd Floor, East Wing" className="h-13 w-full min-w-0 rounded-[14px] border border-[#dfe2e8] pl-11 pr-4 text-[15px] outline-none transition-colors focus:border-[#e14d48]"/></span></label>
  <fieldset className="mt-5 min-w-0"><legend className="text-[14px] font-bold">Quantity</legend><div className="mt-2 grid min-w-0 grid-cols-[minmax(0,1fr)_106px] gap-2.5"><label className="min-w-0"><span className="mb-2 block text-[12px] font-semibold text-[#676d7a]">Planned <span className="text-[#e14d48]">*</span></span><input ref={plannedRef} value={planned} onChange={e=>{setPlanned(e.target.value);clearError("planned")}} onKeyDown={e=>nextOnEnter(e,achievedRef)} enterKeyHint="next" inputMode="decimal" type="number" min="0" placeholder="0" className={`h-14 w-full min-w-0 rounded-[14px] border px-4 text-[19px] font-bold outline-none transition-colors focus:border-[#e14d48] ${errors.planned?"border-[#dc4742]":"border-[#dfe2e8]"}`}/></label><label className="min-w-0"><span className="mb-2 block text-[12px] font-semibold text-[#676d7a]">Unit <span className="text-[#e14d48]">*</span></span><span className="relative block"><select value={unit} onChange={e=>{setUnit(e.target.value);clearError("unit")}} className={`h-14 w-full min-w-0 appearance-none rounded-[14px] border bg-white px-3 pr-8 text-[15px] font-bold outline-none focus:border-[#e14d48] ${errors.unit?"border-[#dc4742]":"border-[#dfe2e8]"}`}>{workUnits.map(option=><option key={option} value={option}>{option}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 text-[#687080]"/></span></label></div>{errors.planned&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.planned}</span>}
   <label className="mt-4 block"><span className="mb-2 block text-[12px] font-semibold text-[#676d7a]">Achieved <span className="text-[#e14d48]">*</span></span><input ref={achievedRef} value={achieved} onChange={e=>{setAchieved(e.target.value);clearError("achieved")}} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();noteRef.current?.focus()}}} enterKeyHint="next" inputMode="decimal" type="number" min="0" placeholder="0" className={`h-14 w-full min-w-0 rounded-[14px] border px-4 text-[19px] font-bold outline-none transition-colors focus:border-[#e14d48] ${errors.achieved?"border-[#dc4742]":"border-[#dfe2e8]"}`}/>{errors.achieved&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.achieved}</span>}</label>
  </fieldset>
  {plannedNumber>0&&<section aria-live="polite" className="mt-5 rounded-[16px] bg-[#f4f8fc] p-4"><div className="flex items-center justify-between gap-3"><span><strong className="block text-[14px]">{achieved===""?"0":achieved} / {planned} {unit}</strong><span className="mt-0.5 block text-[12px] text-[#747b89]">{status}</span></span><strong className={`text-[22px] tracking-[-.04em] ${status==="Completed"?"text-[#29966b]":"text-[#3387d2]"}`}>{progress}%</strong></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-[#e1e5eb]"><motion.div animate={{width:`${progress}%`}} transition={{duration:.25,ease:[.22,1,.36,1]}} className={`h-full rounded-full ${status==="Completed"?"bg-[#35ad7a]":"bg-[#3b91df]"}`}/></div></section>}
  <label className="mt-5 block"><span className="mb-2 block text-[14px] font-bold">Add a note <span className="font-medium text-[#858a97]">(optional)</span></span><textarea ref={noteRef} value={remarks} maxLength={500} onChange={e=>setRemarks(e.target.value)} enterKeyHint="done" rows={3} placeholder="e.g. Installation completed up to Grid B4" className="w-full min-w-0 resize-none rounded-[14px] border border-[#dfe2e8] p-4 text-[15px] leading-6 outline-none transition-colors focus:border-[#e14d48]"/><span className="mt-1 block text-right text-[11px] text-[#8b909d]">{remarks.length}/500</span></label>
 </form></BottomSheet>
}
function ManpowerForm({current,onSave,onDelete,onClose}:FormProps<DPRManpower>){
 const knownRole=current&&roles.includes(current.role)?current.role:"Other";const[role,setRole]=useState(current?knownRole:roles[0]);const[customRole,setCustomRole]=useState(current&&knownRole==="Other"&&current.role!=="Other"?current.role:"");const[inHouse,setInHouse]=useState(current?.inHouse??1);const[subcontractor,setSubcontractor]=useState(current?.subcontractor??0);const[workforce,setWorkforce]=useState<"inHouse"|"subcontractor">(current?.subcontractor&&current.inHouse===0?"subcontractor":"inHouse");const[name,setName]=useState(current?.subcontractorName??"");const[remarks,setRemarks]=useState(current?.remarks??"");const[errors,setErrors]=useState<Record<string,string>>({});
 const customRef=useRef<HTMLInputElement>(null),countRef=useRef<HTMLInputElement>(null),contractorRef=useRef<HTMLInputElement>(null),remarksRef=useRef<HTMLTextAreaElement>(null);const activeCount=workforce==="inHouse"?inHouse:subcontractor;const total=inHouse+subcontractor;
 const clearError=(key:string)=>setErrors(value=>{if(!value[key])return value;const next={...value};delete next[key];return next});const setActiveCount=(value:number)=>{const safe=Math.max(0,Math.floor(Number.isFinite(value)?value:0));if(workforce==="inHouse")setInHouse(safe);else setSubcontractor(safe);clearError("count")};
 const selectWorkforce=(next:"inHouse"|"subcontractor")=>{if(next===workforce)return;if(!current||inHouse===0||subcontractor===0){const transfer=Math.max(1,activeCount);if(next==="inHouse"){setInHouse(transfer);setSubcontractor(0)}else{setSubcontractor(transfer);setInHouse(0)}}setWorkforce(next);clearError("count")};
 const nextOnEnter=(event:React.KeyboardEvent<HTMLInputElement|HTMLSelectElement>,target:React.RefObject<HTMLInputElement|null>)=>{if(event.key!=="Enter")return;event.preventDefault();target.current?.focus()};
 function save(event:FormEvent){event.preventDefault();const nextErrors:Record<string,string>={};const roleName=role==="Other"?(customRole.trim()||"Other"):role;if(!roleName)nextErrors.role="Trade or role is required";if(total<1)nextErrors.count="Add at least one worker";setErrors(nextErrors);if(Object.keys(nextErrors).length)return;onSave({id:current?.id??id(),role:roleName,inHouse,subcontractor,subcontractorName:subcontractor>0?name.trim():"",remarks:remarks.trim()})}
 return <BottomSheet open mobileTall title={current?"Edit Manpower":"Add Manpower"} description="Record today's workforce." onClose={onClose} footer={<SheetFormFooter formId="manpower-form" label={current?"Save Changes":"Add Manpower"} onDelete={onDelete} deleteLabel="Delete manpower entry"/>}><form id="manpower-form" onSubmit={save} noValidate className="min-w-0 px-5 py-5">
  <div className="block min-w-0"><span className="mb-2 block text-[14px] font-bold">Trade / Role <span className="text-[#e14d48]">*</span></span><MobileOptionPicker label="Trade or role" value={role} options={roles} onChange={value=>{setRole(value);clearError("role")}} error={errors.role} icon={<UsersRound size={19} className="text-[#d94d85]"/>}/>{errors.role&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.role}</span>}</div>
  {role==="Other"&&<label className="mt-4 block"><span className="mb-2 block text-[13px] font-semibold">Custom trade / role</span><input ref={customRef} value={customRole} onChange={e=>setCustomRole(e.target.value)} onKeyDown={e=>nextOnEnter(e,countRef)} enterKeyHint="next" placeholder="e.g. Safety Officer" className="h-13 w-full min-w-0 rounded-[14px] border border-[#dfe2e8] px-4 text-[15px] outline-none transition-colors focus:border-[#e14d48]"/></label>}
  <fieldset className="mt-5 min-w-0"><legend className="text-[14px] font-bold">Workforce type</legend><div className="mt-2 grid min-w-0 grid-cols-2 gap-2.5"><WorkforceOption active={workforce==="inHouse"} icon={<House size={19}/>} title="In-house" supporting="Company team" onClick={()=>selectWorkforce("inHouse")}/><WorkforceOption active={workforce==="subcontractor"} icon={<Building2 size={19}/>} title="Subcontractor" supporting="External team" onClick={()=>selectWorkforce("subcontractor")}/></div></fieldset>
  <fieldset className="mt-5 min-w-0"><legend className="text-[14px] font-bold">Number of workers <span className="text-[#e14d48]">*</span></legend><div className={`mt-2 flex min-w-0 items-center justify-between gap-3 rounded-[16px] border p-2 ${errors.count?"border-[#dc4742]":"border-[#dfe2e8]"}`}><button type="button" onClick={()=>setActiveCount(activeCount-1)} disabled={activeCount===0} className="grid size-12 shrink-0 place-items-center rounded-[13px] bg-[#f1f3f6] text-[#616978] disabled:opacity-40" aria-label="Decrease worker count"><Minus size={20}/></button><input ref={countRef} value={activeCount} onChange={e=>setActiveCount(Number(e.target.value))} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();(subcontractor>0?contractorRef:remarksRef).current?.focus()}}} enterKeyHint="next" inputMode="numeric" type="number" min="0" aria-label={`${workforce==="inHouse"?"In-house":"Subcontractor"} worker count`} className="h-12 min-w-0 flex-1 [appearance:textfield] bg-transparent text-center text-[28px] font-bold tracking-[-.04em] outline-none [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none"/><button type="button" onClick={()=>setActiveCount(activeCount+1)} className="grid size-12 shrink-0 place-items-center rounded-[13px] bg-[#fff0ef] text-[#e34c47]" aria-label="Increase worker count"><Plus size={21}/></button></div>{errors.count&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.count}</span>}{inHouse>0&&subcontractor>0&&<p className="mt-2 text-[12px] text-[#777d8c]">Combined entry: {inHouse} in-house + {subcontractor} subcontractor</p>}</fieldset>
  {subcontractor>0&&<motion.label initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} className="mt-5 block"><span className="mb-2 block text-[14px] font-bold">Contractor / Agency <span className="font-medium text-[#858a97]">(optional)</span></span><input ref={contractorRef} value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>nextOnEnter(e,remarksRef as React.RefObject<HTMLInputElement|null>)} enterKeyHint="next" placeholder="e.g. ABC Electricals" className="h-13 w-full min-w-0 rounded-[14px] border border-[#dfe2e8] px-4 text-[15px] outline-none transition-colors focus:border-[#e14d48]"/></motion.label>}
  <label className="mt-5 block"><span className="mb-2 block text-[14px] font-bold">Remarks <span className="font-medium text-[#858a97]">(optional)</span></span><textarea ref={remarksRef} value={remarks} maxLength={200} onChange={e=>setRemarks(e.target.value)} enterKeyHint="done" rows={3} placeholder="e.g. Additional crew deployed after lunch" className="w-full min-w-0 resize-none rounded-[14px] border border-[#dfe2e8] p-4 text-[15px] leading-6 outline-none transition-colors focus:border-[#e14d48]"/><span className="mt-1 block text-right text-[11px] text-[#8b909d]">{remarks.length}/200</span></label>
  {total>0&&<div className="mt-3 flex min-w-0 items-center gap-3 rounded-[15px] bg-[#f5f7fa] p-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-[#687080]"><UsersRound size={18}/></span><span className="min-w-0"><strong className="block truncate text-[14px]">{total} {role==="Other"?(customRole||"workers"):role}{total===1?"":"s"}</strong><span className="mt-0.5 block truncate text-[11px] text-[#7d8391]">{inHouse>0&&subcontractor>0?"Mixed workforce":subcontractor>0?`Subcontractor${name?` · ${name}`:""}`:"In-house"}</span></span></div>}
 </form></BottomSheet>
}
function WorkforceOption({active,icon,title,supporting,onClick}:{active:boolean;icon:React.ReactNode;title:string;supporting:string;onClick:()=>void}){return <button type="button" onClick={onClick} aria-pressed={active} className={`relative flex min-h-[82px] min-w-0 items-center gap-2.5 rounded-[15px] border p-3 text-left transition-colors ${active?"border-[#ed4f49] bg-[#fff8f7]":"border-[#dfe2e8] bg-white"}`}><span className={`grid size-10 shrink-0 place-items-center rounded-[12px] ${active?"bg-[#ffebe9] text-[#e34c47]":"bg-[#edf3ff] text-[#4e78cb]"}`}>{icon}</span><span className="min-w-0"><strong className="block truncate text-[13px] sm:text-[14px]">{title}</strong><span className="mt-0.5 block truncate text-[10px] text-[#7d8391] sm:text-[11px]">{supporting}</span></span><span className={`absolute right-2.5 top-2.5 size-4 rounded-full border-2 ${active?"border-[#ed4f49] bg-[#ed4f49] shadow-[inset_0_0_0_3px_white]":"border-[#aeb3bf]"}`}/></button>}
function MaterialForm({current,onSave,onDelete,onClose}:FormProps<DPRMaterial>){
 const materialOptions=Object.keys(materialUnits);const knownMaterial=current&&materialOptions.includes(current.material)?current.material:"Other";const[material,setMaterial]=useState(current?knownMaterial:materialOptions[0]);const[customMaterial,setCustomMaterial]=useState(current&&knownMaterial==="Other"&&current.material!=="Other"?current.material:"");const[quantity,setQuantity]=useState(current?String(current.quantity):"");const[unit,setUnit]=useState(current?.unit??materialUnits[material]??"");const[remarks,setRemarks]=useState(current?.remarks??"");const[errors,setErrors]=useState<Record<string,string>>({});
 const customRef=useRef<HTMLInputElement>(null),quantityRef=useRef<HTMLInputElement>(null),unitRef=useRef<HTMLSelectElement>(null),remarksRef=useRef<HTMLTextAreaElement>(null);const materialName=material==="Other"?customMaterial.trim():material;const quantityNumber=Number(quantity);const unitOptions=Array.from(new Set([...Object.values(materialUnits),current?.unit].filter((value):value is string=>Boolean(value))));
 const clearError=(key:string)=>setErrors(value=>{if(!value[key])return value;const next={...value};delete next[key];return next});const changeMaterial=(next:string)=>{setMaterial(next);if(next!=="Other"){setUnit(materialUnits[next]??"");clearError("material");clearError("unit")}else setUnit(current?.material===materialName?current.unit:"")};
 function save(event:FormEvent){event.preventDefault();const nextErrors:Record<string,string>={};if(!materialName)nextErrors.material="Material is required";if(quantity===""||!Number.isFinite(quantityNumber)||quantityNumber<=0)nextErrors.quantity="Enter a quantity greater than 0";if(!unit)nextErrors.unit="Unit is required";setErrors(nextErrors);if(Object.keys(nextErrors).length)return;onSave({id:current?.id??id(),material:materialName,unit,quantity:quantityNumber,remarks:remarks.trim()})}
 return <BottomSheet open mobileTall title={current?"Edit Material":"Add Material"} description="Record material used today." onClose={onClose} footer={<SheetFormFooter formId="material-form" label={current?"Save Changes":"Add Material"} onDelete={onDelete} deleteLabel="Delete material"/>}><form id="material-form" onSubmit={save} noValidate className="min-w-0 px-5 py-5">
  <div className="block min-w-0"><span className="mb-2 block text-[14px] font-bold">Material <span className="text-[#e14d48]">*</span></span><MobileOptionPicker label="Material" value={material} options={materialOptions} onChange={changeMaterial} error={errors.material} icon={<Package size={19} className="text-[#25a87b]"/>}/></div>
  {material==="Other"&&<motion.label initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} className="mt-4 block"><span className="mb-2 block text-[13px] font-semibold">Material name <span className="text-[#e14d48]">*</span></span><input ref={customRef} value={customMaterial} onChange={event=>{setCustomMaterial(event.target.value);clearError("material")}} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();quantityRef.current?.focus()}}} enterKeyHint="next" placeholder="e.g. 20mm Conduit Pipe" className={`h-13 w-full min-w-0 rounded-[14px] border px-4 text-[15px] outline-none transition-colors focus:border-[#e14d48] ${errors.material?"border-[#dc4742]":"border-[#dfe2e8]"}`}/>{errors.material&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.material}</span>}</motion.label>}
  <fieldset className="mt-5 min-w-0"><legend className="text-[14px] font-bold">Quantity used</legend><div className="mt-2 grid min-w-0 grid-cols-[minmax(0,1fr)_112px] gap-2.5"><label className="min-w-0"><span className="mb-2 block text-[12px] font-semibold text-[#676d7a]">Quantity <span className="text-[#e14d48]">*</span></span><input ref={quantityRef} value={quantity} onChange={event=>{setQuantity(event.target.value);clearError("quantity")}} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();unitRef.current?.focus()}}} enterKeyHint="next" inputMode="decimal" type="number" min="0" step="any" placeholder="0" className={`h-14 w-full min-w-0 rounded-[14px] border px-4 text-[21px] font-bold outline-none transition-colors focus:border-[#e14d48] [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none ${errors.quantity?"border-[#dc4742]":"border-[#dfe2e8]"}`}/></label><label className="min-w-0"><span className="mb-2 block text-[12px] font-semibold text-[#676d7a]">Unit <span className="text-[#e14d48]">*</span></span><span className="relative block"><select ref={unitRef} value={unit} onChange={event=>{setUnit(event.target.value);clearError("unit")}} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();remarksRef.current?.focus()}}} className={`h-14 w-full min-w-0 appearance-none rounded-[14px] border bg-white px-3 pr-8 text-[15px] font-bold outline-none focus:border-[#e14d48] ${errors.unit?"border-[#dc4742]":"border-[#dfe2e8]"}`}><option value="">Select</option>{unitOptions.map(option=><option key={option}>{option}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 text-[#687080]"/></span></label></div>{errors.quantity&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.quantity}</span>}{errors.unit&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.unit}</span>}</fieldset>
  <label className="mt-5 block"><span className="mb-2 block text-[14px] font-bold">Remarks <span className="font-medium text-[#858a97]">(optional)</span></span><textarea ref={remarksRef} value={remarks} maxLength={200} onChange={event=>setRemarks(event.target.value)} enterKeyHint="done" rows={2} placeholder="e.g. Used for cable pulling work" className="w-full min-w-0 resize-none rounded-[14px] border border-[#dfe2e8] p-4 text-[15px] leading-6 outline-none transition-colors focus:border-[#e14d48]"/><span className="mt-1 block text-right text-[11px] text-[#8b909d]">{remarks.length}/200</span></label>
  {materialName&&quantityNumber>0&&unit&&<motion.section initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} aria-live="polite" className="mt-3 flex min-w-0 items-center gap-3 rounded-[15px] bg-[#f4f7f8] p-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-[#25a87b]"><Package size={18}/></span><span className="min-w-0"><strong className="block truncate text-[14px]">{materialName}</strong><span className="mt-0.5 block truncate text-[12px] font-semibold text-[#687080]">{quantityNumber} {unit}</span>{remarks.trim()&&<span className="mt-0.5 block truncate text-[11px] text-[#8b909d]">{remarks.trim()}</span>}</span></motion.section>}
 </form></BottomSheet>
}
function VisitForm({current,onSave,onDelete,onClose}:FormProps<SiteVisit>){return <SiteVisitForm open current={current} onSave={onSave} onDelete={onDelete} onClose={onClose}/>}
function PlanForm({current,onSave,onDelete,onClose}:FormProps<TomorrowActivity>){const[activity,setActivity]=useState(current?.activity??"Cable Pulling");const[planned,setPlanned]=useState(current?.planned??0);const[remarks,setRemarks]=useState(current?.remarks??"");const unit=activities[activity]??"";function save(e:FormEvent){e.preventDefault();onSave({id:current?.id??id(),activity,unit,planned,remarks})}return <BottomSheet open title={current?"Edit Planned Work":"Add Planned Work"} onClose={onClose} footer={<SheetFormFooter formId="legacy-plan-form" label={current?"Save Changes":"Add Planned Work"} onDelete={onDelete}/>}><form id="legacy-plan-form" onSubmit={save} className="p-5"><Select labelText="Activity" value={activity} onChange={setActivity} options={Object.keys(activities)}/><NumberField labelText={`Planned quantity (${unit||"unit"})`} value={planned} onChange={setPlanned}/><Field labelText="Remarks — optional" value={remarks} onChange={setRemarks}/></form></BottomSheet>}
function Select({labelText,value,onChange,options}:{labelText:string;value:string;onChange:(v:string)=>void;options:string[]}){return <div className="block"><span className={label}>{labelText}</span><MobileOptionPicker label={labelText} value={value} onChange={onChange} options={options}/></div>}
function Field({labelText,value,onChange,required}:{labelText:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label className="mt-4 block"><span className={label}>{labelText}</span><input required={required} value={value} onChange={e=>onChange(e.target.value)} className={field}/></label>}
function NumberField({labelText,value,onChange}:{labelText:string;value:number;onChange:(v:number)=>void}){return <label className="mt-4 block"><span className={label}>{labelText}</span><input required min="0" inputMode="decimal" type="number" value={value} onChange={e=>onChange(Number(e.target.value))} className={field}/></label>}

function Review({dpr,missing,totalManpower,onBack,onEdit,onSubmit}:{dpr:DPR;missing:string[];totalManpower:number;onBack:()=>void;onEdit:(s:string)=>void;onSubmit:()=>void}){
 const[attempted,setAttempted]=useState(false);const noticeRef=useRef<HTMLElement>(null);const rows=[{id:"work",name:"Work Done",summary:`${dpr.work.length} activities`},{id:"manpower",name:"Manpower",summary:`${totalManpower} people`},{id:"materials",name:"Materials Used",summary:`${dpr.materials.length} materials`},{id:"photos",name:"Site Photos",summary:`${dpr.photos.length} photos`},{id:"visit",name:"Site Visit / Feedback",summary:dpr.siteVisits.length?`${dpr.siteVisits.length} recorded`:"Not added · Optional"},{id:"tomorrow",name:"Tomorrow's Plan",summary:`${dpr.tomorrowPlan.length} activities`},{id:"remarks",name:"General Remarks",summary:dpr.generalRemarks||"Not added · Optional"}];const map:Record<string,string>={work:"work",manpower:"manpower",materials:"materials",photos:"photos",tomorrowPlan:"tomorrow"};
 const requestSubmit=()=>{if(!missing.length){onSubmit();return}setAttempted(true);window.setTimeout(()=>{noticeRef.current?.scrollIntoView({behavior:"smooth",block:"center"});noticeRef.current?.focus({preventScroll:true})},0)};
 return <main className="mx-auto min-h-dvh max-w-[760px] px-4 pb-12 pt-5 sm:px-6"><button onClick={onBack} className="flex h-11 items-center gap-2 text-[14px] font-semibold"><ArrowLeft size={18}/>Back to DPR</button><div className="mt-4"><h1 className="text-[26px] font-semibold tracking-[-.03em]">Review today&apos;s DPR</h1><p className="mt-2 text-[14px] text-[#71717a]">Commercial Tower · {formatDPRDate(dpr.date)}</p></div>{missing.length>0&&<section ref={noticeRef} tabIndex={-1} role={attempted?"alert":undefined} className={`mt-6 rounded-2xl border bg-[#fff5e5] p-5 outline-none transition-shadow ${attempted?"border-[#df9b3f] shadow-[0_0_0_3px_rgba(223,155,63,.16)]":"border-[#f0d7b4]"}`}><h2 className="text-[16px] font-semibold">{missing.length} required {missing.length===1?"section":"sections"} remaining</h2><p className="mt-1 text-[13px] text-[#76572f]">Complete each section below before submitting.</p><div className="mt-3 space-y-2">{missing.map(key=><button key={key} onClick={()=>onEdit(map[key])} className="flex min-h-12 w-full items-center justify-between rounded-[10px] bg-white/80 p-3 text-left"><span><strong className="block text-[13px]">{key==="materials"?"Materials Used":key==="photos"?"Site Photos":key==="tomorrowPlan"?"Tomorrow's Plan":key==="work"?"Work Done":"Manpower"}</strong><span className="text-[12px] text-[#71717a]">Add at least one valid entry</span></span><ChevronRight size={16}/></button>)}</div></section>}<section className="mt-6 divide-y divide-[#e4e4e7] rounded-2xl border border-[#e4e4e7] bg-white px-5">{rows.map(row=><div key={row.id} className="flex min-h-[72px] items-center justify-between gap-4"><span><strong className="block text-[14px]">{row.name}</strong><span className="mt-1 block max-w-[440px] truncate text-[12px] text-[#71717a]">{row.summary}</span></span><button onClick={()=>onEdit(row.id)} className="h-10 px-2 text-[13px] font-semibold text-[#e14d48]">Edit</button></div>)}</section><button onClick={requestSubmit} className={`mt-6 h-[52px] w-full rounded-[11px] text-[15px] font-semibold ${missing.length?"border border-[#e14d48] bg-white text-[#d94742]":"bg-[#e14d48] text-white"}`}>Submit DPR</button></main>
}
function Success({date,onDone}:{date:string;onDone:()=>void}){return <motion.main initial={{opacity:0}} animate={{opacity:1}} className="grid min-h-dvh place-items-center px-5"><div className="max-w-md text-center"><motion.span initial={{scale:.7,opacity:0}} animate={{scale:1,opacity:1}} transition={{duration:.65,ease:[.22,1,.36,1]}} className="mx-auto grid size-16 place-items-center rounded-full bg-[#eaf5ef] text-[#3f8f6b]"><Check size={30} strokeWidth={2.5}/></motion.span><h1 className="mt-6 text-[26px] font-semibold">DPR submitted</h1><p className="mt-3 text-[15px] font-medium">Commercial Tower</p><p className="mt-1 text-[13px] text-[#71717a]">{formatDPRDate(date)}</p><p className="mt-5 text-[14px] leading-6 text-[#71717a]">Today&apos;s site record has been submitted successfully.</p><div className="mt-7 grid grid-cols-2 gap-3"><Link href={`/dpr/today?project=commercial-tower&date=${date}`} className="grid h-12 place-items-center rounded-[10px] border border-[#e4e4e7] text-[14px] font-semibold">View DPR</Link><button onClick={onDone} className="h-12 rounded-[10px] bg-[#18181b] text-[14px] font-semibold text-white">Done</button></div></div></motion.main>}
function SaveErrorNotice(){return <div role="alert" className="fixed inset-x-4 top-[76px] z-[65] mx-auto max-w-md rounded-[13px] border border-[#f0cbc8] bg-[#fff4f3] px-4 py-3 text-center text-[12px] font-semibold text-[#b53f3a] shadow-[0_8px_24px_rgba(80,30,28,.1)]">Couldn&apos;t save changes. Keep this page open and try another edit.</div>}
function ReadOnlyDPR({dpr,onDeleted}:{dpr:DPR;onDeleted:()=>void}){const total=dpr.manpower.reduce((sum,row)=>sum+row.inHouse+row.subcontractor,0);const rows=[["Work Done",`${dpr.work.length} activities`],["Manpower",`${total} people`],["Materials Used",`${dpr.materials.length} materials`],["Site Photos",`${dpr.photos.length} photos`],["Site Visit / Feedback",dpr.siteVisits.length?`${dpr.siteVisits.length} recorded`:"Not recorded · Optional"],["Tomorrow's Plan",`${dpr.tomorrowPlan.length} activities`],["General Remarks",dpr.generalRemarks||"Not added · Optional"]];return <main className="mx-auto min-h-dvh max-w-[800px] px-4 py-5 sm:px-6 lg:py-8"><div className="flex items-center justify-between"><Link href="/today" className="flex h-11 items-center gap-2 text-[14px] font-semibold"><ArrowLeft size={18}/>Back</Link><DPRDeleteMenu dpr={dpr} onDeleted={onDeleted}/></div><div className="mt-4 flex items-start justify-between gap-4"><div><h1 className="text-[24px] font-semibold">Today&apos;s DPR</h1><p className="mt-1 text-[14px] text-[#71717a]">Commercial Tower · {formatDPRDate(dpr.date)}</p></div><span className="rounded-full bg-[#eaf5ef] px-3 py-1.5 text-[11px] font-semibold text-[#3f8f6b]">Submitted ✓</span></div><section className="mt-6 divide-y divide-[#e4e4e7] rounded-2xl border border-[#e4e4e7] bg-white px-5">{rows.map(([name,value])=><div key={name} className="flex min-h-[70px] items-center justify-between gap-4"><strong className="text-[14px]">{name}</strong><span className="text-right text-[13px] text-[#71717a]">{value}</span></div>)}</section><p className="mt-4 text-center text-[12px] text-[#71717a]">Submitted DPRs are read-only.</p></main>}
function PhotoViewer({photo,onClose,onRemove}:{photo:DPRPhoto;onClose:()=>void;onRemove:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} className="fixed inset-0 z-[80] flex flex-col bg-[#18181b]"><div className="flex h-16 items-center justify-between px-4 text-white"><span className="text-[13px]">{photo.caption||photo.name}</span><button onClick={onClose} className="grid size-11 place-items-center" aria-label="Close viewer"><X/></button></div><div className="flex min-h-0 flex-1 items-center justify-center p-4"><StoredPhoto src={photo.src} alt={photo.caption||"Site photo"} className="max-h-full max-w-full object-contain"/></div><div className="flex justify-end p-4 pb-[calc(16px+env(safe-area-inset-bottom))]"><button onClick={onRemove} className="flex h-11 items-center gap-2 rounded-[10px] bg-white/10 px-4 text-[13px] font-semibold text-white"><Trash2 size={15}/>Remove</button></div></motion.div>}
