"use client";

import {ArrowLeft} from "lucide-react";
import Link from "next/link";
import {useEffect,useState} from "react";
import {StoredPhoto} from "@/components/dpr/stored-photo";
import {ReportActions} from "@/components/dpr/report-actions";
import {user} from "@/data/mock-data";
import {formatDPRDate,getDPR} from "@/lib/dpr";
import {buildDPRReportData,workProgress} from "@/lib/dpr-report";
import {resolveProject} from "@/lib/projects";
import type {DPR} from "@/types";

export function DPRReport({projectId,date}:{projectId:string;date:string}){const[dpr,setDpr]=useState<DPR|null|undefined>(undefined);useEffect(()=>{const timer=window.setTimeout(()=>setDpr(getDPR(projectId,date)),0);return()=>window.clearTimeout(timer)},[projectId,date]);if(dpr===undefined)return <ReportMessage>Preparing report…</ReportMessage>;if(!dpr)return <ReportMessage title="DPR not found">No DPR exists for this project and date.</ReportMessage>;if(dpr.status!=="submitted")return <ReportMessage title="Report unavailable">Submit this DPR before opening its professional report.</ReportMessage>;return <SubmittedReport dpr={dpr}/>}

function SubmittedReport({dpr}:{dpr:DPR}){const report=buildDPRReportData(dpr,resolveProject(dpr.projectId));const submittedAt=formatTimestamp(dpr.updatedAt);return <div className="dpr-report-workspace min-h-dvh bg-[#eceef2] pb-10 text-[#20232b]">
 <div className="report-toolbar sticky top-0 z-30 border-b border-black/[.08] bg-white/94 backdrop-blur-xl"><nav aria-label="Report navigation" className="mx-auto flex h-16 max-w-[940px] items-center justify-between px-4 sm:px-6"><Link href={`/dpr/today?project=${dpr.projectId}&date=${dpr.date}`} className="focus-ring flex min-h-11 items-center gap-2 rounded-xl pr-3 text-[14px] font-bold"><ArrowLeft size={18}/>Back to DPR</Link><strong className="text-[15px]">DPR Report</strong></nav><div className="mx-auto max-w-[794px] border-t border-black/[.06] px-3 py-2 sm:px-6"><ReportActions dpr={dpr} project={report.project}/></div></div>
 <main className="dpr-report mx-auto mt-5 w-[calc(100%-24px)] max-w-[794px] bg-white px-5 py-7 shadow-[0_18px_54px_rgba(31,35,45,.12)] sm:mt-8 sm:px-10 sm:py-10 lg:px-12">
  <header className="report-header border-b-2 border-[#252832] pb-6"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-[#df4d48]">Digital DPR</p><h1 className="mt-2 text-[25px] font-bold uppercase leading-tight tracking-[-.035em] sm:text-[31px]">Daily Progress Report</h1><p className="mt-4 text-[19px] font-bold">{report.project.name}</p><p className="mt-1 text-[13px] text-[#676d78]">{report.project.workType}</p></div><span className="shrink-0 border border-[#bfe3d4] bg-[#edf8f3] px-3 py-2 text-[11px] font-bold uppercase tracking-[.08em] text-[#277e60]">Submitted</span></div><dl className="mt-6 grid grid-cols-2 gap-x-6 gap-y-4 border-t border-[#dfe2e7] pt-5 sm:grid-cols-4"><Meta label="DPR Date" value={formatDPRDate(dpr.date)}/><Meta label="Prepared by" value={user.name}/><Meta label="Status" value="Submitted"/><Meta label="Submitted" value={submittedAt}/></dl></header>
  <section aria-labelledby="report-summary" className="report-section py-6"><h2 id="report-summary" className="report-kicker">Summary</h2><dl className="mt-3 grid grid-cols-2 border border-[#dde0e5] sm:grid-cols-3">{report.summary.map(item=><div key={item.label} className="border-b border-r border-[#e4e6ea] px-3 py-3 last:border-b-0 sm:px-4"><dt className="text-[10px] font-semibold uppercase tracking-[.06em] text-[#727885]">{item.label}</dt><dd className="mt-1 text-[21px] font-bold">{item.value}</dd></div>)}</dl></section>
  <ReportSection number="01" title="Work Done"><div className="hidden sm:block"><table className="report-table"><thead><tr><th>Activity</th><th>Location</th><th>Planned</th><th>Achieved</th><th>Progress</th></tr></thead><tbody>{dpr.work.map(row=>{const progress=workProgress(row.planned,row.achieved);return <tr key={row.id}><td><strong>{row.activity}</strong>{row.remarks&&<small>{row.remarks}</small>}</td><td>{row.location||"—"}</td><td>{row.planned} {row.unit}</td><td>{row.achieved===null?"—":`${row.achieved} ${row.unit}`}</td><td>{progress===null?"—":`${progress}%`}</td></tr>})}</tbody></table></div><div className="space-y-3 sm:hidden">{dpr.work.map(row=><MobileWork key={row.id} row={row}/>)}</div></ReportSection>
  <ReportSection number="02" title="Manpower"><div className="hidden sm:block"><table className="report-table"><thead><tr><th>Trade / Role</th><th className="text-right">In-house</th><th className="text-right">Subcontractor</th><th className="text-right">Total</th></tr></thead><tbody>{dpr.manpower.map(row=><tr key={row.id}><td><strong>{row.role}</strong>{row.subcontractorName&&<small>{row.subcontractorName}</small>}</td><td className="text-right">{row.inHouse}</td><td className="text-right">{row.subcontractor}</td><td className="text-right font-bold">{row.inHouse+row.subcontractor}</td></tr>)}</tbody><tfoot><tr><th>Total</th><th className="text-right">{report.manpower.inHouse}</th><th className="text-right">{report.manpower.subcontractor}</th><th className="text-right">{report.manpower.total}</th></tr></tfoot></table></div><div className="space-y-2 sm:hidden">{dpr.manpower.map(row=><article key={row.id} className="report-unit border border-[#e0e3e8] p-3"><div className="flex justify-between gap-3"><strong className="text-[13px]">{row.role}</strong><strong>{row.inHouse+row.subcontractor}</strong></div><p className="mt-2 text-[11px] text-[#69707c]">In-house {row.inHouse} · Subcontractor {row.subcontractor}</p></article>)}<p className="border-t-2 border-[#343841] pt-3 text-right text-[13px] font-bold">Total workforce: {report.manpower.total}</p></div></ReportSection>
  <ReportSection number="03" title="Materials Used"><table className="report-table"><thead><tr><th>Material</th><th>Quantity</th><th>Remarks</th></tr></thead><tbody>{dpr.materials.map(row=><tr key={row.id}><td><strong>{row.material}</strong></td><td>{row.quantity} {row.unit}</td><td>{row.remarks||"—"}</td></tr>)}</tbody></table></ReportSection>
  <ReportSection number="04" title="Site Photos"><div className="report-photo-grid grid grid-cols-1 gap-4 sm:grid-cols-2">{dpr.photos.map((photo,index)=><figure key={photo.id} className="report-photo report-unit border border-[#dde0e5] bg-[#fafafa] p-2"><StoredPhoto src={photo.src} alt={photo.caption||photo.name||`Site photo ${index+1}`} className="aspect-[4/3] w-full object-cover"/><figcaption className="px-1 pb-1 pt-2"><strong className="block text-[10px] uppercase tracking-[.08em] text-[#747a85]">Photo {String(index+1).padStart(2,"0")}</strong>{(photo.caption||photo.name)&&<span className="mt-1 block text-[12px] leading-4">{photo.caption||photo.name}</span>}</figcaption></figure>)}</div></ReportSection>
  {dpr.siteVisits.length>0&&<ReportSection number="05" title="Site Visit / Feedback"><div className="space-y-3">{dpr.siteVisits.map(visit=><article key={visit.id} className="report-unit border-l-2 border-[#df4d48] bg-[#f8f8f9] px-4 py-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="text-[13px]">{visit.visitorName}</strong>{visit.designation&&<span className="ml-2 text-[11px] text-[#68707c]">{visit.designation}</span>}</div><span className="text-[11px] font-semibold text-[#68707c]">{formatTime(visit.visitTime)}</span></div><p className="mt-2 text-[12px] leading-5">{visit.feedback}</p><div className="mt-2 flex flex-wrap gap-2 text-[10px] font-semibold text-[#676e79]">{visit.actionRequired&&<span className="bg-[#fff0dc] px-2 py-1 text-[#9b6417]">Action required</span>}{visit.audioId&&<span className="voice-note-available bg-[#eceef2] px-2 py-1">Voice note available</span>}</div></article>)}</div></ReportSection>}
  {dpr.tomorrowPlan.length>0&&<ReportSection number="06" title="Tomorrow's Plan"><table className="report-table"><thead><tr><th>Activity</th><th>Target</th><th>Notes</th></tr></thead><tbody>{dpr.tomorrowPlan.map(row=><tr key={row.id}><td><strong>{row.activity}</strong></td><td>{row.planned} {row.unit}</td><td>{row.remarks||"—"}</td></tr>)}</tbody></table></ReportSection>}
  {dpr.generalRemarks.trim()&&<section className="report-section report-unit border-t border-[#cfd3da] py-6"><h2 className="report-kicker">General Remarks</h2><p className="mt-3 whitespace-pre-wrap text-[12px] leading-5 text-[#3d424b]">{dpr.generalRemarks}</p></section>}
  <footer className="report-footer mt-4 flex flex-wrap items-center justify-between gap-2 border-t border-[#bfc4cc] pt-3 text-[9px] uppercase tracking-[.06em] text-[#747a85]"><span>Digital DPR</span><span>{report.project.name} · {formatDPRDate(dpr.date,{day:"numeric",month:"short",year:"numeric"})}</span></footer>
 </main>
 </div>}

function ReportSection({number,title,children}:{number:string;title:string;children:React.ReactNode}){return <section className="report-section border-t border-[#cfd3da] py-6"><h2 className="report-heading flex items-baseline gap-2 text-[15px] font-bold uppercase tracking-[.06em]"><span className="text-[#df4d48]">{number}</span><span>{title}</span></h2><div className="mt-4">{children}</div></section>}
function Meta({label,value}:{label:string;value:string}){return <div><dt className="text-[9px] font-bold uppercase tracking-[.08em] text-[#7a808b]">{label}</dt><dd className="mt-1 text-[11px] font-semibold leading-4">{value}</dd></div>}
function MobileWork({row}:{row:DPR["work"][number]}){const progress=workProgress(row.planned,row.achieved);return <article className="report-unit border border-[#e0e3e8] p-3"><strong className="text-[13px]">{row.activity}</strong>{row.location&&<p className="mt-1 text-[11px] text-[#69707c]">{row.location}</p>}<dl className="mt-3 grid grid-cols-3 gap-2 text-[10px]"><div><dt className="text-[#7a808b]">Planned</dt><dd className="mt-1 font-bold">{row.planned} {row.unit}</dd></div><div><dt className="text-[#7a808b]">Achieved</dt><dd className="mt-1 font-bold">{row.achieved===null?"—":`${row.achieved} ${row.unit}`}</dd></div><div><dt className="text-[#7a808b]">Progress</dt><dd className="mt-1 font-bold">{progress===null?"—":`${progress}%`}</dd></div></dl>{row.remarks&&<p className="mt-3 border-t border-[#e7e9ed] pt-2 text-[11px] leading-4">{row.remarks}</p>}</article>}
function ReportMessage({title="DPR Report",children}:{title?:string;children:React.ReactNode}){return <main className="grid min-h-dvh place-items-center bg-[#f3f4f6] px-5"><div className="max-w-sm text-center"><h1 className="text-[22px] font-bold">{title}</h1><p className="mt-2 text-[14px] leading-6 text-[#717784]">{children}</p><Link href="/calendar" className="mt-5 inline-grid h-11 place-items-center rounded-xl bg-[#242832] px-5 text-[13px] font-bold text-white">Back to calendar</Link></div></main>}
function formatTimestamp(value:string){const date=new Date(value);if(Number.isNaN(date.getTime()))return "Submitted";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(date)}
function formatTime(value:string){const[hours,minutes]=value.split(":").map(Number);if(!Number.isFinite(hours))return value;return `${hours%12||12}:${String(minutes||0).padStart(2,"0")} ${hours>=12?"PM":"AM"}`}
