"use client";

import {Building2,House,Minus,Plus,UsersRound} from "lucide-react";
import {FormEvent,useMemo,useState} from "react";
import {BottomSheet} from "@/components/dpr/bottom-sheet";
import type {DPRManpower} from "@/types";

export const manpowerRoles=["Electrician","Helper","Supervisor","Technician","Welder","Plumber"] as const;
type BatchRow={id:string;role:string;inHouse:string;subcontractor:string;subcontractorName?:string;remarks?:string};

const cleanCount=(value:string)=>value.replace(/\D/g,"").replace(/^0+(?=\d)/,"");
const count=(value:string)=>Math.max(0,Number.parseInt(value||"0",10)||0);
const roleKey=(value:string)=>value.trim().toLocaleLowerCase();

function initialRows(existing:DPRManpower[]):BatchRow[]{
 const grouped=new Map<string,BatchRow>();
 for(const row of existing){const key=roleKey(row.role);const found=grouped.get(key);if(found){found.inHouse=String(count(found.inHouse)+row.inHouse);found.subcontractor=String(count(found.subcontractor)+row.subcontractor);continue}grouped.set(key,{id:row.id,role:row.role.trim(),inHouse:String(row.inHouse),subcontractor:String(row.subcontractor),subcontractorName:row.subcontractorName,remarks:row.remarks})}
 return [...manpowerRoles.map(role=>grouped.get(roleKey(role))??{id:crypto.randomUUID(),role,inHouse:"0",subcontractor:"0"}),...Array.from(grouped.values()).filter(row=>!manpowerRoles.some(role=>roleKey(role)===roleKey(row.role)))];
}

export function ManpowerBatchForm({existing,onSave,onClose}:{existing:DPRManpower[];onSave:(rows:DPRManpower[])=>void;onClose:()=>void}){
 const[rows,setRows]=useState<BatchRow[]>(()=>initialRows(existing));const[addOpen,setAddOpen]=useState(false);const[tradeChoice,setTradeChoice]=useState<string>(manpowerRoles[0]);const[customTrade,setCustomTrade]=useState("");const[highlight,setHighlight]=useState<string|null>(null);const[error,setError]=useState("");
 const totals=useMemo(()=>rows.reduce((result,row)=>{const inHouse=count(row.inHouse),subcontractor=count(row.subcontractor);result.inHouse+=inHouse;result.subcontractor+=subcontractor;if(inHouse+subcontractor>0)result.trades+=1;return result},{inHouse:0,subcontractor:0,trades:0}),[rows]);const totalWorkers=totals.inHouse+totals.subcontractor;
 const update=(key:string,field:"inHouse"|"subcontractor",value:string)=>setRows(current=>current.map(row=>roleKey(row.role)===key?{...row,[field]:cleanCount(value)}:row));
 const adjust=(key:string,field:"inHouse"|"subcontractor",delta:number)=>setRows(current=>current.map(row=>roleKey(row.role)===key?{...row,[field]:String(Math.max(0,count(row[field])+delta))}:row));
 const reveal=(role:string)=>{const key=roleKey(role);setHighlight(key);document.getElementById(`batch-trade-${key.replace(/[^a-z0-9]+/g,"-")}`)?.scrollIntoView({behavior:"smooth",block:"center"});window.setTimeout(()=>setHighlight(null),1200)};
 const addTrade=()=>{const role=tradeChoice==="Other"?customTrade.trim():tradeChoice;if(!role){setError("Enter a trade or role");return}const existingRow=rows.find(row=>roleKey(row.role)===roleKey(role));if(existingRow){setError(`${existingRow.role} is already in this batch`);reveal(existingRow.role);return}setRows(current=>[...current,{id:crypto.randomUUID(),role,inHouse:"0",subcontractor:"0"}]);setTradeChoice(manpowerRoles[0]);setCustomTrade("");setAddOpen(false);setError("");window.setTimeout(()=>reveal(role),0)};
 const save=(event:FormEvent)=>{event.preventDefault();const active=rows.filter(row=>count(row.inHouse)+count(row.subcontractor)>0).map(row=>({id:row.id,role:row.role,inHouse:count(row.inHouse),subcontractor:count(row.subcontractor),subcontractorName:row.subcontractorName,remarks:row.remarks}));if(active.length===0){setError("Add at least one worker before saving");return}onSave(active)};
 return <BottomSheet open mobileTall guardDirty title="Add Manpower" description="Add all manpower types for today" onClose={onClose} footer={<button form="manpower-batch-form" type="submit" className="h-[54px] w-full rounded-[14px] bg-[#ed4f49] text-[16px] font-bold text-white shadow-[0_8px_18px_rgba(237,79,73,.18)] active:scale-[.99]">Save Manpower{totalWorkers>0?` · ${totalWorkers} workers`:""}</button>}>
  <form id="manpower-batch-form" onSubmit={save} className="min-w-0 px-4 py-4 sm:px-5">
   <section aria-label="Live manpower summary" aria-live="polite" className="grid grid-cols-4 gap-1.5 rounded-[18px] bg-[#f4f6f9] p-2.5 sm:gap-3 sm:p-3"><Summary value={totalWorkers} label="Total workers" icon={<UsersRound size={16}/>}/><Summary value={totals.inHouse} label="In-house" icon={<House size={16}/>}/><Summary value={totals.subcontractor} label="Subcontractor" icon={<Building2 size={16}/>}/><Summary value={totals.trades} label="Trades" icon={<UsersRound size={16}/>}/></section>
   <div className="mt-4 space-y-3">{rows.map(row=>{const key=roleKey(row.role),rowTotal=count(row.inHouse)+count(row.subcontractor);return <article id={`batch-trade-${key.replace(/[^a-z0-9]+/g,"-")}`} key={key} className={`scroll-m-24 rounded-[17px] border bg-white p-3 transition-all sm:p-4 ${highlight===key?"border-[#ed4f49] ring-2 ring-[#ed4f49]/15":"border-black/[.07]"}`}><div className="flex items-center justify-between gap-3"><h3 className="truncate text-[15px] font-bold">{row.role}</h3><span className="shrink-0 rounded-full bg-[#f3f4f6] px-2.5 py-1 text-[11px] font-bold text-[#636a78]">Total {rowTotal}</span></div><div className="mt-3 grid grid-cols-2 gap-2.5"><Counter label="In-house" value={row.inHouse} onChange={value=>update(key,"inHouse",value)} onMinus={()=>adjust(key,"inHouse",-1)} onPlus={()=>adjust(key,"inHouse",1)}/><Counter label="Subcontractor" value={row.subcontractor} onChange={value=>update(key,"subcontractor",value)} onMinus={()=>adjust(key,"subcontractor",-1)} onPlus={()=>adjust(key,"subcontractor",1)}/></div></article>})}</div>
   <section className="mt-4 rounded-[17px] border border-dashed border-[#cfd3dc] bg-[#fafbfc] p-3 sm:p-4">{!addOpen?<button type="button" onClick={()=>setAddOpen(true)} className="flex min-h-11 w-full items-center justify-center gap-2 text-[14px] font-bold text-[#596273]"><Plus size={18}/>Add another trade</button>:<><div className="grid min-w-0 gap-2 sm:grid-cols-2"><label className="min-w-0"><span className="mb-1.5 block text-[12px] font-semibold text-[#676d7a]">Trade / Role</span><select value={tradeChoice} onChange={event=>{setTradeChoice(event.target.value);setError("")}} className="h-12 w-full min-w-0 rounded-[12px] border border-[#dfe2e8] bg-white px-3 text-[14px] font-semibold outline-none focus:border-[#ed4f49]">{manpowerRoles.map(role=><option key={role}>{role}</option>)}<option>Other</option></select></label>{tradeChoice==="Other"&&<label className="min-w-0"><span className="mb-1.5 block text-[12px] font-semibold text-[#676d7a]">Custom trade</span><input value={customTrade} maxLength={60} onChange={event=>{setCustomTrade(event.target.value);setError("")}} placeholder="e.g. Carpenter" className="h-12 w-full min-w-0 rounded-[12px] border border-[#dfe2e8] px-3 text-[14px] outline-none focus:border-[#ed4f49]"/></label>}</div>{error&&<p role="alert" className="mt-2 text-[12px] font-semibold text-[#c8403b]">{error}</p>}<div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>{setAddOpen(false);setError("")}} className="min-h-11 rounded-[12px] border border-black/[.08] text-[13px] font-semibold">Cancel</button><button type="button" onClick={addTrade} className="min-h-11 rounded-[12px] bg-[#242833] text-[13px] font-bold text-white">Add Trade</button></div></>}</section>
   {!addOpen&&error&&<p role="alert" className="mt-3 text-center text-[12px] font-semibold text-[#c8403b]">{error}</p>}
  </form>
 </BottomSheet>
}

function Summary({value,label,icon}:{value:number;label:string;icon:React.ReactNode}){return <span className="min-w-0 rounded-[13px] bg-white px-1.5 py-2 text-center shadow-[0_3px_10px_rgba(20,25,35,.025)]"><span className="mx-auto flex w-fit items-center gap-1 text-[#747c8b]">{icon}<strong className="text-[16px] text-[#242833]">{value}</strong></span><span className="mt-1 block text-[9px] font-semibold leading-3 text-[#7d8391] sm:text-[10px]">{label}</span></span>}
function Counter({label,value,onChange,onMinus,onPlus}:{label:string;value:string;onChange:(value:string)=>void;onMinus:()=>void;onPlus:()=>void}){const numeric=count(value);return <fieldset className="min-w-0"><legend className="mb-1.5 text-[11px] font-semibold text-[#747b89] sm:text-[12px]">{label}</legend><div className="grid min-w-0 grid-cols-[44px_minmax(36px,1fr)_44px] items-center overflow-hidden rounded-[13px] border border-[#dfe2e8]"><button type="button" onClick={onMinus} disabled={numeric===0} aria-label={`Decrease ${label}`} className="grid size-11 place-items-center bg-[#f3f4f6] text-[#626a79] disabled:opacity-35"><Minus size={17}/></button><input value={value} onChange={event=>onChange(event.target.value)} onFocus={event=>event.currentTarget.select()} inputMode="numeric" pattern="[0-9]*" aria-label={`${label} count`} className="h-11 w-full min-w-0 [appearance:textfield] bg-white text-center text-[17px] font-bold outline-none [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none"/><button type="button" onClick={onPlus} aria-label={`Increase ${label}`} className="grid size-11 place-items-center bg-[#fff0ef] text-[#e34c47]"><Plus size={18}/></button></div></fieldset>}
