"use client";

import {ArrowLeft,ArrowRight,Check,Copy,EllipsisVertical,Layers3,PackageOpen,Pencil,Plus,Ruler,Trash2} from "lucide-react";
import {AnimatePresence,motion,useReducedMotion} from "motion/react";
import Link from "next/link";
import {useState} from "react";
import {BottomSheet} from "@/components/dpr/bottom-sheet";
import {DPRDeleteMenu} from "@/components/dpr/dpr-delete-menu";
import {formatDPRDate,sectionComplete} from "@/lib/dpr";
import {ease,transitions} from "@/lib/motion";
import type {DPR,DPRMaterial} from "@/types";

type Props={dpr:DPR;saveState:"saving"|"saved"|"error";completed:number;percent:number;onAdd:()=>void;onEdit:(id:string)=>void;onDuplicate:(row:DPRMaterial)=>void;onDelete:(id:string)=>void;onNext:()=>void;onDprDeleted:()=>void};
const steps=["Work","Manpower","Materials","Photos","Tomorrow"];
const tileTones=["bg-[#e9f8f3] text-[#27966e]","bg-[#edf3ff] text-[#4675d1]","bg-[#f0efff] text-[#6b58ce]"];

export function MaterialsScreen({dpr,saveState,completed,percent,onAdd,onEdit,onDuplicate,onDelete,onNext,onDprDeleted}:Props){
 const reduce=useReducedMotion();const[menuId,setMenuId]=useState<string|null>(null);const[deleteTarget,setDeleteTarget]=useState<DPRMaterial|null>(null);
 const materialTypes=new Set(dpr.materials.map(row=>row.material.trim()).filter(Boolean)).size;const units=new Set(dpr.materials.map(row=>row.unit).filter(Boolean)).size;const materialsComplete=sectionComplete(dpr,"materials");
 const requestDelete=(row:DPRMaterial)=>{setMenuId(null);setDeleteTarget(row)};const confirmDelete=()=>{if(!deleteTarget)return;onDelete(deleteTarget.id);setDeleteTarget(null)};
 return <motion.div initial={reduce?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={transitions.page} className="min-h-dvh overflow-x-clip bg-[#f6f7f9] pb-[calc(104px+env(safe-area-inset-bottom))] lg:pb-12">
  <header className="sticky top-0 z-40 border-b border-black/[.06] bg-[#f6f7f9]/92 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[980px] items-center justify-between px-4 sm:px-6"><Link href="/today" className="focus-ring grid size-11 place-items-center rounded-xl" aria-label="Back to Today"><ArrowLeft size={23}/></Link><h1 className="absolute left-1/2 -translate-x-1/2 text-[18px] font-bold tracking-[-.03em]">Materials Used</h1><div className="flex items-center gap-1"><motion.span key={saveState} initial={{opacity:0,y:2}} animate={{opacity:1,y:0}} className={`hidden text-[13px] font-semibold min-[360px]:block ${saveState==="saved"?"text-[#25a46f]":"text-[#777b88]"}`}>{saveState==="saving"?"Saving…":"Saved ✓"}</motion.span><DPRDeleteMenu dpr={dpr} onDeleted={onDprDeleted}/></div></div></header>
  <main className="mx-auto w-full min-w-0 max-w-[980px] px-4 pb-4 pt-5 sm:px-6 lg:pt-8">
   <section className="flex min-w-0 items-center justify-between gap-4"><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><h2 className="truncate text-[24px] font-bold tracking-[-.04em]">Commercial Tower</h2><span className="shrink-0 rounded-lg bg-[#ffebe9] px-2.5 py-1 text-[11px] font-bold text-[#df4b46]">Draft</span></div><p className="mt-1.5 text-[13px] text-[#7b8090]">MEP Works</p><p className="mt-1 text-[13px] text-[#7b8090]">Today&apos;s DPR <span className="px-1">•</span> {formatDPRDate(dpr.date)}</p></div><ProgressRing percent={percent} completed={completed} reduce={Boolean(reduce)}/></section>
   <nav aria-label="DPR sections" className="mt-7 grid grid-cols-5 gap-1">{steps.map((step,index)=>{const done=(index===0&&sectionComplete(dpr,"work"))||(index===1&&sectionComplete(dpr,"manpower"));const active=index===2;return <div key={step} aria-current={active?"step":undefined} className="relative flex min-w-0 flex-col items-center gap-2"><span className={`relative z-10 grid size-9 place-items-center rounded-full text-[13px] font-bold ${done?"bg-[#34ae79] text-white":active?"bg-[#242833] text-white":"bg-[#eceef2] text-[#7e8493]"}`}>{done?<Check size={17} strokeWidth={2.8}/>:index+1}</span>{index<steps.length-1&&<span className="absolute left-[calc(50%+22px)] top-[17px] h-px w-[calc(100%-36px)] bg-[#dfe2e8]"/>}<span className={`w-full truncate text-[11px] font-semibold sm:text-[12px] ${active?"text-[#20232d]":"text-[#858b9b]"}`}>{step}</span></div>})}</nav>
   <section className="mt-7"><div className="flex items-start justify-between gap-4"><div><h2 className="text-[22px] font-bold tracking-[-.035em]">Materials used today</h2><p className="mt-1.5 max-w-xl text-[14px] leading-5 text-[#777d8d]">Record materials consumed on site today.</p></div><button onClick={onAdd} className="hidden min-h-12 shrink-0 items-center gap-2 rounded-[13px] bg-[#fff0ef] px-4 text-[14px] font-bold text-[#e34c47] transition-transform active:scale-[.98] sm:flex"><Plus size={18}/>Add Material</button></div>
    <div className="mt-5 rounded-[20px] border border-black/[.05] bg-white p-4 shadow-[0_7px_22px_rgba(20,25,35,.035)]"><div className="flex items-end justify-between gap-4"><span><span className="block text-[12px] font-semibold text-[#777d8c]">Material entries</span><motion.strong key={dpr.materials.length} initial={reduce?false:{opacity:0,y:3}} animate={{opacity:1,y:0}} className="mt-1 block text-[34px] leading-none tracking-[-.05em]">{dpr.materials.length}</motion.strong></span><span className={`rounded-full px-3 py-1.5 text-[11px] font-bold ${materialsComplete?"bg-[#e8f7f0] text-[#29966f]":"bg-[#f1f2f4] text-[#777d89]"}`}>{materialsComplete?"Section complete":"Not recorded"}</span></div><div className="mt-5 grid grid-cols-3 divide-x divide-black/[.07]"><Metric icon={<PackageOpen size={16}/>} value={dpr.materials.length} label="Entries"/><Metric icon={<Layers3 size={16}/>} value={materialTypes} label="Material types"/><Metric icon={<Ruler size={16}/>} value={units} label={units===1?"Unit":"Units"}/></div></div>
   </section>
   <section className="mt-6" aria-labelledby="materials-list-title"><div className="mb-3 flex items-center justify-between"><h3 id="materials-list-title" className="text-[17px] font-bold">Materials added</h3>{dpr.materials.length>0&&<span className="text-[12px] font-semibold text-[#858b99]">{dpr.materials.length} {dpr.materials.length===1?"entry":"entries"}</span>}</div><div className="space-y-3">{dpr.materials.length===0?<MaterialsEmptyState onAdd={onAdd}/>:<AnimatePresence initial={false}>{dpr.materials.map((row,index)=><MaterialEntryCard key={row.id} row={row} index={index} menuOpen={menuId===row.id} onToggleMenu={()=>setMenuId(menuId===row.id?null:row.id)} onCloseMenu={()=>setMenuId(null)} onEdit={()=>{setMenuId(null);onEdit(row.id)}} onDuplicate={()=>{setMenuId(null);onDuplicate(row)}} onDelete={()=>requestDelete(row)} reduce={Boolean(reduce)}/>)}</AnimatePresence>}</div></section>
   {dpr.materials.length>0&&<button onClick={onAdd} className="mt-4 flex min-h-[72px] w-full items-center justify-center gap-2 rounded-[18px] border border-dashed border-[#cfd3dc] bg-white/55 text-[14px] font-bold text-[#687080] transition-colors hover:bg-white active:scale-[.99]"><Plus size={20}/>Add another material</button>}
  </main>
  <div className="fixed inset-x-0 bottom-0 z-30 border-t border-black/[.06] bg-white/94 px-4 pb-[calc(12px+env(safe-area-inset-bottom))] pt-3 shadow-[0_-8px_24px_rgba(24,24,27,.045)] backdrop-blur-xl lg:static lg:mx-auto lg:mt-5 lg:max-w-[980px] lg:border-0 lg:bg-transparent lg:px-6 lg:shadow-none"><div className="mx-auto flex max-w-[680px] gap-3"><Link href="/today" className="grid min-h-[54px] flex-1 place-items-center rounded-[14px] border border-black/[.08] bg-white text-[14px] font-bold">Back to DPR</Link><button onClick={onNext} className="flex min-h-[54px] flex-[1.45] items-center justify-center gap-2 rounded-[14px] bg-[#ed4f49] text-[15px] font-bold text-white shadow-[0_8px_18px_rgba(237,79,73,.18)] active:scale-[.98]">Save &amp; Continue <ArrowRight size={18}/></button></div></div>
  <BottomSheet open={Boolean(deleteTarget)} title="Delete material?" onClose={()=>setDeleteTarget(null)}><div className="p-5"><p className="text-[15px] font-semibold text-[#202127]">{deleteTarget?.material} — {deleteTarget?.quantity} {deleteTarget?.unit}</p><p className="mt-2 text-[14px] leading-6 text-[#717784]">This material will be removed from today&apos;s DPR.</p><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={()=>setDeleteTarget(null)} className="h-12 rounded-[12px] border border-black/[.08] font-semibold">Cancel</button><button onClick={confirmDelete} className="h-12 rounded-[12px] bg-[#dc3f3a] font-semibold text-white">Delete</button></div></div></BottomSheet>
 </motion.div>
}

function ProgressRing({percent,completed,reduce}:{percent:number;completed:number;reduce:boolean}){const circumference=2*Math.PI*27;return <div className="relative grid size-[76px] shrink-0 place-items-center"><svg viewBox="0 0 68 68" className="size-[76px] -rotate-90" aria-hidden="true"><circle cx="34" cy="34" r="27" fill="none" stroke="#e5e8ed" strokeWidth="6"/><motion.circle cx="34" cy="34" r="27" fill="none" stroke="#ed4f49" strokeWidth="6" strokeLinecap="round" strokeDasharray={circumference} initial={reduce?false:{strokeDashoffset:circumference}} animate={{strokeDashoffset:circumference*(1-percent/100)}} transition={{duration:reduce?0:.7,ease}}/></svg><span className="absolute text-center"><strong className="block text-[16px] leading-none">{percent}%</strong><span className="mt-1 block text-[9px] text-[#7d8290]">{completed} of 5</span></span></div>}
function Metric({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <span className="min-w-0 px-2 text-center first:pl-0 last:pr-0"><span className="mx-auto flex w-fit items-center gap-1.5"><span className="text-[#778091]">{icon}</span><strong className="text-[18px]">{value}</strong></span><span className="mt-1 block truncate text-[10px] font-medium text-[#858b99] sm:text-[11px]">{label}</span></span>}

function MaterialEntryCard({row,index,menuOpen,onToggleMenu,onCloseMenu,onEdit,onDuplicate,onDelete,reduce}:{row:DPRMaterial;index:number;menuOpen:boolean;onToggleMenu:()=>void;onCloseMenu:()=>void;onEdit:()=>void;onDuplicate:()=>void;onDelete:()=>void;reduce:boolean}){const tone=tileTones[index%tileTones.length];return <motion.article layout initial={reduce?false:{opacity:0,y:7}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:.98}} transition={{...transitions.reveal,delay:reduce?0:index*.035}} className="relative min-w-0 rounded-[18px] border border-black/[.055] bg-white p-4 shadow-[0_7px_22px_rgba(20,25,35,.035)]"><button onClick={onEdit} className="flex w-full min-w-0 items-center gap-3 pr-10 text-left"><span className={`grid size-12 shrink-0 place-items-center rounded-[15px] ${tone}`}><PackageOpen size={21}/></span><span className="min-w-0 flex-1"><strong className="block truncate text-[16px] tracking-[-.02em]">{row.material}</strong><span className="mt-1 block truncate text-[12px] text-[#7d8391]">Material used on site</span>{row.remarks&&<span className="mt-1 block truncate text-[11px] text-[#979ba6]">{row.remarks}</span>}</span><span className="shrink-0 text-right"><strong className="block max-w-24 truncate text-[21px] tracking-[-.04em]">{row.quantity}</strong><span className="text-[11px] font-semibold text-[#737987]">{row.unit}</span></span></button><button onClick={onToggleMenu} aria-label={`Options for ${row.material}`} aria-expanded={menuOpen} className="absolute right-1.5 top-1.5 grid size-11 place-items-center rounded-xl text-[#737a89]"><EllipsisVertical size={20}/></button>{menuOpen&&<><button aria-label="Close material menu" onClick={onCloseMenu} className="fixed inset-0 z-40 cursor-default"/><div className="absolute right-3 top-12 z-50 w-40 rounded-[14px] border border-black/[.07] bg-white p-1.5 shadow-[0_12px_28px_rgba(24,24,27,.12)]"><MenuAction icon={<Pencil size={15}/>} label="Edit" onClick={onEdit}/><MenuAction icon={<Copy size={15}/>} label="Duplicate" onClick={onDuplicate}/><MenuAction icon={<Trash2 size={15}/>} label="Delete" onClick={onDelete} destructive/></div></>}</motion.article>}
function MenuAction({icon,label,onClick,destructive}:{icon:React.ReactNode;label:string;onClick:()=>void;destructive?:boolean}){return <button onClick={onClick} className={`flex h-10 w-full items-center gap-2 rounded-[10px] px-3 text-left text-[13px] font-semibold ${destructive?"text-[#d9423d] hover:bg-[#fff0ef]":"text-[#363a44] hover:bg-[#f5f6f8]"}`}>{icon}{label}</button>}
function MaterialsEmptyState({onAdd}:{onAdd:()=>void}){return <div className="rounded-[20px] border border-dashed border-[#cfd3dc] bg-white p-5 text-center shadow-[0_6px_20px_rgba(20,25,35,.025)]"><span className="mx-auto grid size-12 place-items-center rounded-[15px] bg-[#e9f8f3] text-[#27966e]"><PackageOpen size={22}/></span><h3 className="mt-4 text-[17px] font-bold">No materials recorded yet</h3><p className="mx-auto mt-1.5 max-w-xs text-[13px] leading-5 text-[#7b8190]">Add materials used for today&apos;s site activities.</p><button onClick={onAdd} className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-[13px] bg-[#ed4f49] px-5 text-[14px] font-bold text-white active:scale-[.98]"><Plus size={18}/>Add Material</button></div>}
