"use client";

import {Download,Printer,Share2} from "lucide-react";
import {useRef,useState} from "react";
import {generateDPRPdf,type GeneratedDPRPdf} from "@/lib/dpr-pdf";
import {downloadDPRPdf,fileShareAvailable,shareDPRPdf} from "@/lib/dpr-share";
import type {DPR,Project} from "@/types";

export function ReportActions({dpr,project,showPrint=true,compact=false}:{dpr:DPR;project:Project;showPrint?:boolean;compact?:boolean}){const[active,setActive]=useState<"download"|"share"|null>(null);const[message,setMessage]=useState("");const[unsupported,setUnsupported]=useState(false);const generated=useRef<Promise<GeneratedDPRPdf>|null>(null);const pdf=()=>generated.current??(generated.current=generateDPRPdf(dpr,project).catch(error=>{generated.current=null;throw error}));const fail=()=>setMessage("Couldn’t generate the report. Please try again.");
 const download=async()=>{if(active)return;setActive("download");setMessage("");try{downloadDPRPdf(await pdf());setMessage("PDF downloaded.")}catch(error){console.error("Could not generate DPR PDF",error);fail()}finally{setActive(null)}};
 const share=async()=>{if(active)return;setMessage("");setUnsupported(false);if(!fileShareAvailable()){setUnsupported(true);return}setActive("share");try{const result=await shareDPRPdf(await pdf(),dpr,project);if(result==="unsupported")setUnsupported(true)}catch(error){console.error("Could not share DPR PDF",error);fail()}finally{setActive(null)}};
 return <div className={compact?"w-full":"flex items-center gap-2"}><div className={`${compact?"grid grid-cols-2 gap-2":"flex items-center gap-2"}`}><button type="button" onClick={download} disabled={Boolean(active)} aria-label="Download DPR as PDF" aria-busy={active==="download"} className={`${compact?"h-12":"min-h-11"} flex items-center justify-center gap-2 rounded-xl bg-[#ed4f49] px-3 text-[12px] font-bold text-white disabled:opacity-60`}><Download size={16}/>{active==="download"?"Generating…":"Download PDF"}</button><button type="button" onClick={share} disabled={Boolean(active)} aria-label="Share DPR report" aria-busy={active==="share"} className={`${compact?"h-12":"min-h-11"} flex items-center justify-center gap-2 rounded-xl border border-[#d7dae0] bg-white px-3 text-[12px] font-bold disabled:opacity-60`}><Share2 size={16}/>{active==="share"?"Preparing…":"Share Report"}</button>{showPrint&&<button type="button" onClick={()=>window.print()} disabled={Boolean(active)} aria-label="Print DPR report" className="hidden min-h-11 items-center justify-center gap-2 rounded-xl bg-[#252832] px-3 text-[12px] font-bold text-white sm:flex"><Printer size={16}/>Print</button>}</div>{message&&<p role="status" aria-live="polite" className={`${compact?"mt-2":"absolute right-4 top-[60px]"} text-[11px] font-semibold text-[#4b5664]`}>{message}</p>}{unsupported&&<div role="status" className={`${compact?"mt-3":"absolute right-4 top-[60px] max-w-xs"} rounded-xl border border-[#dedfe3] bg-white p-3 text-[11px] leading-4 text-[#626975] shadow-sm`}>File sharing isn&apos;t supported in this browser. Download the PDF to share it manually.<button type="button" onClick={download} className="mt-2 block min-h-11 w-full rounded-lg bg-[#252832] px-3 font-bold text-white">Download PDF</button></div>}</div>}
