"use client";

import {ArrowLeft,ArrowRight,Camera,Check,Images,Plus,Trash2,X} from "lucide-react";
import {AnimatePresence,motion,useReducedMotion} from "motion/react";
import Link from "next/link";
import {ChangeEvent,useRef,useState} from "react";
import {BottomSheet} from "@/components/dpr/bottom-sheet";
import {DPRDeleteMenu} from "@/components/dpr/dpr-delete-menu";
import {StoredPhoto} from "@/components/dpr/stored-photo";
import {formatDPRDate,sectionComplete} from "@/lib/dpr";
import {ease,transitions} from "@/lib/motion";
import {deleteStoredPhoto,deleteStoredPhotoIfUnreferenced,savePhotoDataUrl} from "@/lib/photo-store";
import type {DPR,DPRPhoto} from "@/types";

type Props={dpr:DPR;saveState:"saving"|"saved"|"error";completed:number;percent:number;onAdd:(photos:DPRPhoto[])=>void;onCaption:(id:string,caption:string)=>void;onDelete:(id:string)=>void;onNext:()=>void;onDprDeleted:()=>void};
const steps=["Work","Manpower","Materials","Photos","Tomorrow"];
const supportedTypes=new Set(["image/jpeg","image/png","image/webp","image/heic","image/heif"]);

export function SitePhotosScreen({dpr,saveState,completed,percent,onAdd,onCaption,onDelete,onNext,onDprDeleted}:Props){
 const reduce=useReducedMotion();const cameraRef=useRef<HTMLInputElement>(null),galleryRef=useRef<HTMLInputElement>(null);const[processing,setProcessing]=useState(false);const[error,setError]=useState("");const[viewer,setViewer]=useState<DPRPhoto|null>(null);const[deleteTarget,setDeleteTarget]=useState<DPRPhoto|null>(null);
 const addFiles=async(event:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files??[]);event.target.value="";if(!files.length)return;setError("");setProcessing(true);const photos:DPRPhoto[]=[];try{for(const file of files){if(!supportedTypes.has(file.type)&&!file.type.startsWith("image/"))throw new Error("unsupported");const photoId=crypto.randomUUID();const resized=await resizeImage(file);photos.push({id:photoId,src:await savePhotoDataUrl(photoId,resized),name:file.name})}onAdd(photos)}catch{await Promise.all(photos.map(photo=>deleteStoredPhoto(photo.src).catch(()=>{})));setError("Couldn’t add this photo. Choose a supported JPG, PNG, HEIC or WebP image and try again.")}finally{setProcessing(false)}};
 const requestDelete=(photo:DPRPhoto)=>{setViewer(null);setDeleteTarget(photo)};const confirmDelete=()=>{if(!deleteTarget)return;const src=deleteTarget.src;onDelete(deleteTarget.id);setDeleteTarget(null);window.setTimeout(()=>void deleteStoredPhotoIfUnreferenced(src),700)};
 return <motion.div initial={reduce?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={transitions.page} className="min-h-dvh overflow-x-clip bg-[#f6f7f9] pb-[calc(104px+env(safe-area-inset-bottom))] lg:pb-12">
  <header className="sticky top-0 z-40 border-b border-black/[.06] bg-[#f6f7f9]/92 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[980px] items-center justify-between px-4 sm:px-6"><Link href="/today" className="focus-ring grid size-11 place-items-center rounded-xl" aria-label="Back to Today"><ArrowLeft size={23}/></Link><h1 className="absolute left-1/2 -translate-x-1/2 text-[18px] font-bold tracking-[-.03em]">Site Photos</h1><div className="flex items-center gap-1"><motion.span key={saveState} initial={{opacity:0,y:2}} animate={{opacity:1,y:0}} className={`hidden text-[13px] font-semibold min-[360px]:block ${saveState==="saved"?"text-[#25a46f]":"text-[#777b88]"}`}>{saveState==="saving"?"Saving…":"Saved ✓"}</motion.span><DPRDeleteMenu dpr={dpr} onDeleted={onDprDeleted}/></div></div></header>
  <main className="mx-auto w-full min-w-0 max-w-[980px] px-4 pb-5 pt-5 sm:px-6 lg:pt-8">
   <section className="flex min-w-0 items-center justify-between gap-4"><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><h2 className="truncate text-[24px] font-bold tracking-[-.04em]">Commercial Tower</h2><span className="shrink-0 rounded-lg bg-[#ffebe9] px-2.5 py-1 text-[11px] font-bold text-[#df4b46]">Draft</span></div><p className="mt-1.5 text-[13px] text-[#7b8090]">MEP Works</p><p className="mt-1 text-[13px] text-[#7b8090]">Today&apos;s DPR <span className="px-1">•</span> {formatDPRDate(dpr.date)}</p></div><ProgressRing percent={percent} completed={completed} reduce={Boolean(reduce)}/></section>
   <nav aria-label="DPR sections" className="mt-7 grid grid-cols-5 gap-1">{steps.map((step,index)=>{const done=(index===0&&sectionComplete(dpr,"work"))||(index===1&&sectionComplete(dpr,"manpower"))||(index===2&&sectionComplete(dpr,"materials"));const active=index===3;return <div key={step} aria-current={active?"step":undefined} className="relative flex min-w-0 flex-col items-center gap-2"><span className={`relative z-10 grid size-9 place-items-center rounded-full text-[13px] font-bold ${done?"bg-[#34ae79] text-white":active?"bg-[#242833] text-white":"bg-[#eceef2] text-[#7e8493]"}`}>{done?<Check size={17} strokeWidth={2.8}/>:index+1}</span>{index<steps.length-1&&<span className="absolute left-[calc(50%+22px)] top-[17px] h-px w-[calc(100%-36px)] bg-[#dfe2e8]"/>}<span className={`w-full truncate text-[11px] font-semibold sm:text-[12px] ${active?"text-[#20232d]":"text-[#858b9b]"}`}>{step}</span></div>})}</nav>
   <section className="mt-7"><div className="flex min-w-0 items-start justify-between gap-4"><div className="min-w-0"><h2 className="text-[22px] font-bold tracking-[-.035em]">Show today&apos;s site progress</h2><p className="mt-1.5 text-[14px] leading-5 text-[#777d8d]">Capture completed work, progress and site conditions.</p></div><span className="shrink-0 rounded-full bg-[#fff4e2] px-3 py-1.5 text-[11px] font-bold text-[#b77716]">{dpr.photos.length} {dpr.photos.length===1?"photo":"photos"}</span></div>
    <input ref={cameraRef} className="hidden" type="file" accept="image/*" capture="environment" onChange={addFiles}/><input ref={galleryRef} className="hidden" type="file" accept="image/*" multiple onChange={addFiles}/>
    <div className="mt-5 grid min-w-0 grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)] gap-3"><button disabled={processing} onClick={()=>cameraRef.current?.click()} className="flex min-h-[64px] min-w-0 items-center justify-center gap-2 rounded-[16px] bg-[#ed4f49] px-3 text-[15px] font-bold text-white shadow-[0_8px_18px_rgba(237,79,73,.18)] transition-transform active:scale-[.98] disabled:opacity-60"><Camera size={21}/>{processing?"Processing…":"Take Photo"}</button><button disabled={processing} onClick={()=>galleryRef.current?.click()} className="flex min-h-[64px] min-w-0 items-center justify-center gap-2 rounded-[16px] border border-black/[.08] bg-white px-2 text-center text-[13px] font-bold text-[#4f5664] transition-transform active:scale-[.98] disabled:opacity-60"><Images size={19}/>Choose Gallery</button></div>
    {error&&<p role="alert" className="mt-3 rounded-[13px] bg-[#fff0ef] px-3.5 py-3 text-[12px] font-medium leading-5 text-[#bd423e]">{error}</p>}
   </section>
   <section className="mt-7" aria-labelledby="photo-grid-title"><div className="mb-3 flex items-center justify-between"><h3 id="photo-grid-title" className="text-[17px] font-bold">Photos added</h3>{dpr.photos.length>0&&<span className="text-[12px] font-semibold text-[#858b99]">Tap to preview</span>}</div>{dpr.photos.length===0?<PhotosEmptyState processing={processing} onCamera={()=>cameraRef.current?.click()} onGallery={()=>galleryRef.current?.click()}/>:<div className="grid min-w-0 grid-cols-2 gap-3 sm:grid-cols-3"><AnimatePresence initial={false}>{dpr.photos.map((photo,index)=><PhotoCard key={photo.id} photo={photo} index={index} reduce={Boolean(reduce)} onView={()=>setViewer(photo)} onDelete={()=>requestDelete(photo)}/>)}</AnimatePresence><button onClick={()=>cameraRef.current?.click()} className="flex aspect-[4/3] min-w-0 flex-col items-center justify-center rounded-[17px] border border-dashed border-[#cdd2da] bg-white/60 text-[13px] font-bold text-[#687080]"><Plus size={22}/><span className="mt-2">Add photo</span></button></div>}</section>
  </main>
  <div className="fixed inset-x-0 bottom-0 z-30 border-t border-black/[.06] bg-white/94 px-4 pb-[calc(12px+env(safe-area-inset-bottom))] pt-3 shadow-[0_-8px_24px_rgba(24,24,27,.045)] backdrop-blur-xl lg:static lg:mx-auto lg:mt-5 lg:max-w-[980px] lg:border-0 lg:bg-transparent lg:px-6 lg:shadow-none"><div className="mx-auto flex max-w-[680px] gap-3"><Link href="/today" className="grid min-h-[54px] flex-1 place-items-center rounded-[14px] border border-black/[.08] bg-white text-[14px] font-bold">Back to DPR</Link><button onClick={onNext} className="flex min-h-[54px] flex-[1.45] items-center justify-center gap-2 rounded-[14px] bg-[#ed4f49] px-2 text-center text-[14px] font-bold text-white shadow-[0_8px_18px_rgba(237,79,73,.18)] active:scale-[.98]">Save &amp; Continue <ArrowRight size={18}/></button></div></div>
  <AnimatePresence>{viewer&&<PhotoPreview photo={viewer} onClose={()=>setViewer(null)} onCaption={caption=>{onCaption(viewer.id,caption);setViewer({...viewer,caption})}} onDelete={()=>requestDelete(viewer)} reduce={Boolean(reduce)}/>}</AnimatePresence>
  <BottomSheet open={Boolean(deleteTarget)} title="Delete photo?" onClose={()=>setDeleteTarget(null)}><div className="p-5"><p className="text-[14px] leading-6 text-[#717784]">This photo will be removed from today&apos;s DPR.</p><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={()=>setDeleteTarget(null)} className="h-12 rounded-[12px] border border-black/[.08] font-semibold">Cancel</button><button onClick={confirmDelete} className="h-12 rounded-[12px] bg-[#dc3f3a] font-semibold text-white">Delete</button></div></div></BottomSheet>
 </motion.div>
}

function PhotoCard({photo,index,reduce,onView,onDelete}:{photo:DPRPhoto;index:number;reduce:boolean;onView:()=>void;onDelete:()=>void}){return <motion.article layout initial={reduce?false:{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.96}} transition={{...transitions.reveal,delay:reduce?0:index*.035}} className="group relative min-w-0 overflow-hidden rounded-[17px] bg-white shadow-[0_7px_22px_rgba(20,25,35,.05)]"><button onClick={onView} className="block w-full min-w-0 text-left" aria-label={`Preview ${photo.caption||photo.name}`}><StoredPhoto src={photo.src} alt={photo.caption||photo.name||"Site progress photo"} className="aspect-[4/3] w-full bg-[#e9ebef] object-cover"/><span className="block min-w-0 p-3"><strong className="block truncate text-[13px]">{photo.caption||"Site progress photo"}</strong><span className="mt-1 block truncate text-[11px] text-[#8a909d]">{photo.name}</span></span></button><button onClick={onDelete} className="absolute right-2 top-2 grid size-11 place-items-center rounded-[13px] bg-black/55 text-white backdrop-blur-md" aria-label={`Delete ${photo.caption||photo.name}`}><Trash2 size={17}/></button></motion.article>}
function PhotosEmptyState({processing,onCamera,onGallery}:{processing:boolean;onCamera:()=>void;onGallery:()=>void}){return <div className="rounded-[20px] border border-dashed border-[#cfd3dc] bg-white p-5 text-center shadow-[0_6px_20px_rgba(20,25,35,.025)]"><span className="mx-auto grid size-12 place-items-center rounded-[15px] bg-[#fff3df] text-[#e99a13]"><Camera size={23}/></span><h3 className="mt-4 text-[17px] font-bold">No site photos yet</h3><p className="mx-auto mt-1.5 max-w-xs text-[13px] leading-5 text-[#7b8190]">Capture today&apos;s site progress and completed work.</p><button disabled={processing} onClick={onCamera} className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-[13px] bg-[#ed4f49] px-5 text-[14px] font-bold text-white active:scale-[.98] disabled:opacity-60"><Camera size={18}/>Take Photo</button><button disabled={processing} onClick={onGallery} className="mx-auto mt-2 flex min-h-11 items-center gap-2 px-3 text-[13px] font-bold text-[#596171]"><Images size={17}/>Choose from Gallery</button></div>}
function PhotoPreview({photo,onClose,onCaption,onDelete,reduce}:{photo:DPRPhoto;onClose:()=>void;onCaption:(caption:string)=>void;onDelete:()=>void;reduce:boolean}){const[caption,setCaption]=useState(photo.caption??"");return <motion.div role="dialog" aria-modal="true" aria-label={`Preview ${photo.caption||photo.name}`} initial={reduce?false:{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[80] flex min-w-0 flex-col bg-[#17181b]"><div className="flex min-h-[64px] items-center justify-between gap-3 px-4 pt-[env(safe-area-inset-top)] text-white"><span className="min-w-0 truncate text-[13px] font-semibold">{photo.caption||photo.name}</span><button onClick={onClose} className="grid size-11 shrink-0 place-items-center rounded-xl bg-white/10" aria-label="Close photo preview"><X size={21}/></button></div><div className="flex min-h-0 flex-1 items-center justify-center p-3"><StoredPhoto src={photo.src} alt={photo.caption||photo.name||"Site progress photo"} className="max-h-full max-w-full object-contain"/></div><div className="border-t border-white/10 bg-[#202125] px-4 pb-[calc(14px+env(safe-area-inset-bottom))] pt-3"><label className="block text-[12px] font-semibold text-white/70">Caption <span className="font-normal">(optional)</span><input value={caption} maxLength={120} onChange={event=>setCaption(event.target.value)} placeholder="e.g. Cable tray installation — 3rd Floor" className="mt-2 h-12 w-full min-w-0 rounded-[13px] border border-white/10 bg-white/10 px-3.5 text-[14px] text-white outline-none placeholder:text-white/35 focus:border-white/30"/></label><div className="mt-3 flex gap-3"><button onClick={onDelete} className="grid size-12 shrink-0 place-items-center rounded-[13px] bg-white/10 text-[#ff7772]" aria-label="Delete photo"><Trash2 size={19}/></button><button onClick={()=>{onCaption(caption.trim());onClose()}} className="h-12 flex-1 rounded-[13px] bg-[#ed4f49] text-[14px] font-bold text-white">Save caption</button></div></div></motion.div>}
function ProgressRing({percent,completed,reduce}:{percent:number;completed:number;reduce:boolean}){const circumference=2*Math.PI*27;return <div className="relative grid size-[76px] shrink-0 place-items-center"><svg viewBox="0 0 68 68" className="size-[76px] -rotate-90" aria-hidden="true"><circle cx="34" cy="34" r="27" fill="none" stroke="#e5e8ed" strokeWidth="6"/><motion.circle cx="34" cy="34" r="27" fill="none" stroke="#ed4f49" strokeWidth="6" strokeLinecap="round" strokeDasharray={circumference} initial={reduce?false:{strokeDashoffset:circumference}} animate={{strokeDashoffset:circumference*(1-percent/100)}} transition={{duration:reduce?0:.7,ease}}/></svg><span className="absolute text-center"><strong className="block text-[16px] leading-none">{percent}%</strong><span className="mt-1 block text-[9px] text-[#7d8290]">{completed} of 5</span></span></div>}

async function resizeImage(file:File){const source=await fileToDataUrl(file);const image=await loadImage(source);const maxEdge=1600;const scale=Math.min(1,maxEdge/Math.max(image.naturalWidth,image.naturalHeight));if(scale===1&&file.size<900_000&&file.type==="image/jpeg")return source;const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const context=canvas.getContext("2d");if(!context)throw new Error("processing");context.drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL("image/jpeg",.78)}
function fileToDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("read"));reader.readAsDataURL(file)})}
function loadImage(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("decode"));image.src=src})}
