"use client";

import {ArrowLeft,ArrowRight,CalendarDays,Check,ChevronDown,Copy,EllipsisVertical,Pencil,Plus,Target,Trash2} from "lucide-react";
import {AnimatePresence,motion,useReducedMotion} from "motion/react";
import Link from "next/link";
import {FormEvent,useRef,useState} from "react";
import {BottomSheet} from "@/components/dpr/bottom-sheet";
import {DPRDeleteMenu} from "@/components/dpr/dpr-delete-menu";
import {MobileOptionPicker} from "@/components/dpr/mobile-option-picker";
import {addDays,formatDPRDate,sectionComplete} from "@/lib/dpr";
import {ease,transitions} from "@/lib/motion";
import type {DPR,TomorrowActivity} from "@/types";

type Props={dpr:DPR;saveState:"saving"|"saved"|"error";completed:number;percent:number;onUpsert:(activity:TomorrowActivity)=>void;onDuplicate:(activity:TomorrowActivity)=>void;onDelete:(id:string)=>void;onReview:()=>void;onDprDeleted:()=>void};
const steps=["Work","Manpower","Materials","Photos","Tomorrow"];
const activityUnits:Record<string,string>={"Cable Tray Installation":"m","Conduit Laying":"m","Cable Pulling":"m","Panel Installation":"nos","Earthing":"m","Light Fixture Installation":"nos","Testing & Commissioning":"job","Other":""};
const unitOptions=["m","m²","m³","nos","kg","lot","job"];

export function TomorrowPlanScreen({dpr,saveState,completed,percent,onUpsert,onDuplicate,onDelete,onReview,onDprDeleted}:Props){
 const reduce=useReducedMotion();const[editing,setEditing]=useState<TomorrowActivity|null|undefined>(undefined);const[menuId,setMenuId]=useState<string|null>(null);const[deleteTarget,setDeleteTarget]=useState<TomorrowActivity|null>(null);const tomorrowDate=addDays(dpr.date,1);const complete=sectionComplete(dpr,"tomorrowPlan");
 const confirmDelete=()=>{if(!deleteTarget)return;onDelete(deleteTarget.id);setDeleteTarget(null)};
 return <motion.div initial={reduce?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={transitions.page} className="min-h-dvh overflow-x-clip bg-[#f6f7f9] pb-[calc(104px+env(safe-area-inset-bottom))] lg:pb-12">
  <header className="sticky top-0 z-40 border-b border-black/[.06] bg-[#f6f7f9]/92 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-[980px] items-center justify-between px-4 sm:px-6"><Link href="/today" className="focus-ring grid size-11 place-items-center rounded-xl" aria-label="Back to Today"><ArrowLeft size={23}/></Link><h1 className="absolute left-1/2 -translate-x-1/2 text-[18px] font-bold tracking-[-.03em]">Tomorrow&apos;s Plan</h1><div className="flex items-center gap-1"><motion.span key={saveState} initial={{opacity:0,y:2}} animate={{opacity:1,y:0}} className={`hidden text-[13px] font-semibold min-[360px]:block ${saveState==="saved"?"text-[#25a46f]":"text-[#777b88]"}`}>{saveState==="saving"?"Saving…":"Saved ✓"}</motion.span><DPRDeleteMenu dpr={dpr} onDeleted={onDprDeleted}/></div></div></header>
  <main className="mx-auto w-full min-w-0 max-w-[980px] px-4 pb-5 pt-5 sm:px-6 lg:pt-8">
   <section className="flex min-w-0 items-center justify-between gap-4"><div className="min-w-0"><div className="flex min-w-0 items-center gap-2"><h2 className="truncate text-[24px] font-bold tracking-[-.04em]">Commercial Tower</h2><span className="shrink-0 rounded-lg bg-[#ffebe9] px-2.5 py-1 text-[11px] font-bold text-[#df4b46]">Draft</span></div><p className="mt-1.5 text-[13px] text-[#7b8090]">MEP Works</p><p className="mt-1 text-[13px] text-[#7b8090]">Tomorrow <span className="px-1">•</span> {formatDPRDate(tomorrowDate)}</p></div><ProgressRing percent={percent} completed={completed} reduce={Boolean(reduce)}/></section>
   <nav aria-label="DPR sections" className="mt-7 grid grid-cols-5 gap-1">{steps.map((step,index)=>{const done=(index===0&&sectionComplete(dpr,"work"))||(index===1&&sectionComplete(dpr,"manpower"))||(index===2&&sectionComplete(dpr,"materials"))||(index===3&&sectionComplete(dpr,"photos"));const active=index===4;return <div key={step} aria-current={active?"step":undefined} className="relative flex min-w-0 flex-col items-center gap-2"><span className={`relative z-10 grid size-9 place-items-center rounded-full text-[13px] font-bold ${done?"bg-[#34ae79] text-white":active?"bg-[#242833] text-white":"bg-[#eceef2] text-[#7e8493]"}`}>{done?<Check size={17} strokeWidth={2.8}/>:index+1}</span>{index<steps.length-1&&<span className="absolute left-[calc(50%+22px)] top-[17px] h-px w-[calc(100%-36px)] bg-[#dfe2e8]"/>}<span className={`w-full truncate text-[11px] font-semibold sm:text-[12px] ${active?"text-[#20232d]":"text-[#858b9b]"}`}>{step}</span></div>})}</nav>
   <section className="mt-7"><div className="flex min-w-0 items-start justify-between gap-4"><div className="min-w-0"><h2 className="text-[22px] font-bold tracking-[-.035em]">Plan the next working day</h2><p className="mt-1.5 max-w-xl text-[14px] leading-5 text-[#777d8d]">Add the activities you expect to execute tomorrow.</p></div><button onClick={()=>setEditing(null)} className="hidden min-h-12 shrink-0 items-center gap-2 rounded-[13px] bg-[#fff0ef] px-4 text-[14px] font-bold text-[#e34c47] active:scale-[.98] sm:flex"><Plus size={18}/>Add Activity</button></div>
    <div className="mt-5 flex min-w-0 items-center justify-between rounded-[20px] border border-black/[.05] bg-white p-4 shadow-[0_7px_22px_rgba(20,25,35,.035)]"><span className="flex min-w-0 items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-[14px] bg-[#fff0ef] text-[#e34c47]"><CalendarDays size={20}/></span><span className="min-w-0"><strong className="block text-[22px] tracking-[-.04em]">{dpr.tomorrowPlan.length}</strong><span className="block truncate text-[12px] text-[#777d8c]">{dpr.tomorrowPlan.length===1?"activity planned":"activities planned"}</span></span></span><span className={`shrink-0 rounded-full px-3 py-1.5 text-[11px] font-bold ${complete?"bg-[#e8f7f0] text-[#29966f]":"bg-[#f1f2f4] text-[#777d89]"}`}>{complete?"Section complete":"Plan required"}</span></div>
   </section>
   <section className="mt-6" aria-labelledby="plan-title"><div className="mb-3 flex items-center justify-between"><h3 id="plan-title" className="text-[17px] font-bold">Planned activities</h3>{dpr.tomorrowPlan.length>0&&<span className="text-[12px] font-semibold text-[#858b99]">{dpr.tomorrowPlan.length} planned</span>}</div><div className="space-y-3">{dpr.tomorrowPlan.length===0?<PlanEmptyState onAdd={()=>setEditing(null)}/>:<AnimatePresence initial={false}>{dpr.tomorrowPlan.map((activity,index)=><PlanCard key={activity.id} activity={activity} index={index} reduce={Boolean(reduce)} menuOpen={menuId===activity.id} onToggleMenu={()=>setMenuId(menuId===activity.id?null:activity.id)} onCloseMenu={()=>setMenuId(null)} onEdit={()=>{setMenuId(null);setEditing(activity)}} onDuplicate={()=>{setMenuId(null);onDuplicate(activity)}} onDelete={()=>{setMenuId(null);setDeleteTarget(activity)}}/>)}</AnimatePresence>}</div>{dpr.tomorrowPlan.length>0&&<button onClick={()=>setEditing(null)} className="mt-4 flex min-h-[68px] w-full items-center justify-center gap-2 rounded-[17px] border border-dashed border-[#cfd3dc] bg-white/55 text-[14px] font-bold text-[#687080] active:scale-[.99]"><Plus size={19}/>Add another planned activity</button>}</section>
   <aside className="mt-5 flex gap-3 rounded-[17px] bg-[#eef6ff] p-4 text-[#4d6682]"><Target size={20} className="mt-0.5 shrink-0 text-[#3489db]"/><p className="text-[12px] leading-5"><strong className="block text-[13px] text-[#287bc7]">Planning tip</strong>Base tomorrow&apos;s plan on today&apos;s progress and the next site priority.</p></aside>
  </main>
  <div className="fixed inset-x-0 bottom-0 z-30 border-t border-black/[.06] bg-white/94 px-4 pb-[calc(12px+env(safe-area-inset-bottom))] pt-3 shadow-[0_-8px_24px_rgba(24,24,27,.045)] backdrop-blur-xl lg:static lg:mx-auto lg:mt-5 lg:max-w-[980px] lg:border-0 lg:bg-transparent lg:px-6 lg:shadow-none"><div className="mx-auto flex max-w-[680px] gap-3"><Link href="/today" className="grid min-h-[54px] flex-1 place-items-center rounded-[14px] border border-black/[.08] bg-white text-[14px] font-bold">Back to DPR</Link><button onClick={onReview} className="flex min-h-[54px] flex-[1.45] items-center justify-center gap-2 rounded-[14px] bg-[#ed4f49] px-2 text-[14px] font-bold text-white shadow-[0_8px_18px_rgba(237,79,73,.18)] active:scale-[.98]">Review DPR <ArrowRight size={18}/></button></div></div>
  <PlanForm key={editing?.id??(editing===null?"new":"closed")} open={editing!==undefined} current={editing??undefined} onClose={()=>setEditing(undefined)} onSave={activity=>{onUpsert(activity);setEditing(undefined)}}/>
  <BottomSheet open={Boolean(deleteTarget)} title="Delete planned activity?" onClose={()=>setDeleteTarget(null)}><div className="p-5"><p className="text-[15px] font-semibold text-[#202127]">{deleteTarget?.activity} — {deleteTarget?.planned} {deleteTarget?.unit}</p><p className="mt-2 text-[14px] leading-6 text-[#717784]">This activity will be removed from tomorrow&apos;s plan.</p><div className="mt-6 grid grid-cols-2 gap-3"><button onClick={()=>setDeleteTarget(null)} className="h-12 rounded-[12px] border border-black/[.08] font-semibold">Cancel</button><button onClick={confirmDelete} className="h-12 rounded-[12px] bg-[#dc3f3a] font-semibold text-white">Delete</button></div></div></BottomSheet>
 </motion.div>
}

function PlanCard({activity,index,reduce,menuOpen,onToggleMenu,onCloseMenu,onEdit,onDuplicate,onDelete}:{activity:TomorrowActivity;index:number;reduce:boolean;menuOpen:boolean;onToggleMenu:()=>void;onCloseMenu:()=>void;onEdit:()=>void;onDuplicate:()=>void;onDelete:()=>void}){return <motion.article layout initial={reduce?false:{opacity:0,y:7}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:.98}} transition={{...transitions.reveal,delay:reduce?0:index*.035}} className="relative min-w-0 rounded-[18px] border border-black/[.055] bg-white p-4 shadow-[0_7px_22px_rgba(20,25,35,.035)]"><button onClick={onEdit} className="flex w-full min-w-0 items-start gap-3 pr-9 text-left"><span className="grid size-10 shrink-0 place-items-center rounded-[13px] bg-[#fff0ef] text-[13px] font-bold text-[#e34c47]">{String(index+1).padStart(2,"0")}</span><span className="min-w-0 flex-1"><strong className="block truncate text-[16px] tracking-[-.02em]">{activity.activity}</strong>{activity.remarks&&<span className="mt-2 block text-[12px] leading-5 text-[#7d8391]">{activity.remarks}</span>}</span><span className="shrink-0 rounded-[13px] bg-[#f4f6f8] px-3 py-2 text-right"><span className="block text-[10px] font-semibold uppercase tracking-wide text-[#8b909d]">Target</span><strong className="mt-0.5 block text-[19px] tracking-[-.04em]">{activity.planned} <span className="text-[12px]">{activity.unit}</span></strong></span></button><button onClick={onToggleMenu} aria-label={`Options for ${activity.activity}`} aria-expanded={menuOpen} className="absolute right-1 top-1 grid size-11 place-items-center rounded-xl text-[#737a89]"><EllipsisVertical size={20}/></button>{menuOpen&&<><button aria-label="Close activity menu" onClick={onCloseMenu} className="fixed inset-0 z-40 cursor-default"/><div className="absolute right-3 top-11 z-50 w-40 rounded-[14px] border border-black/[.07] bg-white p-1.5 shadow-[0_12px_28px_rgba(24,24,27,.12)]"><MenuAction icon={<Pencil size={15}/>} label="Edit" onClick={onEdit}/><MenuAction icon={<Copy size={15}/>} label="Duplicate" onClick={onDuplicate}/><MenuAction icon={<Trash2 size={15}/>} label="Delete" onClick={onDelete} destructive/></div></>}</motion.article>}
function MenuAction({icon,label,onClick,destructive}:{icon:React.ReactNode;label:string;onClick:()=>void;destructive?:boolean}){return <button onClick={onClick} className={`flex h-10 w-full items-center gap-2 rounded-[10px] px-3 text-left text-[13px] font-semibold ${destructive?"text-[#d9423d] hover:bg-[#fff0ef]":"text-[#363a44] hover:bg-[#f5f6f8]"}`}>{icon}{label}</button>}
function PlanEmptyState({onAdd}:{onAdd:()=>void}){return <div className="rounded-[20px] border border-dashed border-[#cfd3dc] bg-white p-5 text-center shadow-[0_6px_20px_rgba(20,25,35,.025)]"><span className="mx-auto grid size-12 place-items-center rounded-[15px] bg-[#fff0ef] text-[#e34c47]"><CalendarDays size={22}/></span><h3 className="mt-4 text-[17px] font-bold">No activities planned yet</h3><p className="mx-auto mt-1.5 max-w-xs text-[13px] leading-5 text-[#7b8190]">Add the work you expect to execute tomorrow.</p><button onClick={onAdd} className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-[13px] bg-[#ed4f49] px-5 text-[14px] font-bold text-white active:scale-[.98]"><Plus size={18}/>Add Planned Activity</button></div>}

function PlanForm({open,current,onClose,onSave}:{open:boolean;current?:TomorrowActivity;onClose:()=>void;onSave:(activity:TomorrowActivity)=>void}){
 const options=Object.keys(activityUnits);const known=current&&options.includes(current.activity)?current.activity:"Other";const[activity,setActivity]=useState(current?known:options[0]);const[custom,setCustom]=useState(current&&known==="Other"&&current.activity!=="Other"?current.activity:"");const[planned,setPlanned]=useState(current?String(current.planned):"");const[unit,setUnit]=useState(current?.unit??activityUnits[activity]??"");const[remarks,setRemarks]=useState(current?.remarks??"");const[errors,setErrors]=useState<Record<string,string>>({});const customRef=useRef<HTMLInputElement>(null),plannedRef=useRef<HTMLInputElement>(null),unitRef=useRef<HTMLSelectElement>(null),noteRef=useRef<HTMLTextAreaElement>(null);const activityName=activity==="Other"?custom.trim():activity;const plannedNumber=Number(planned);
 const clearError=(key:string)=>setErrors(value=>{if(!value[key])return value;const next={...value};delete next[key];return next});const changeActivity=(next:string)=>{setActivity(next);clearError("activity");const suggested=activityUnits[next];if(suggested){setUnit(suggested);clearError("unit")}else if(next==="Other")setUnit(current?.activity===activityName?current.unit:"")};
 function save(event:FormEvent){event.preventDefault();const nextErrors:Record<string,string>={};if(!activityName)nextErrors.activity="Activity is required";if(planned===""||!Number.isFinite(plannedNumber)||plannedNumber<=0)nextErrors.planned="Enter a target greater than 0";if(!unit)nextErrors.unit="Unit is required";setErrors(nextErrors);if(Object.keys(nextErrors).length)return;onSave({id:current?.id??crypto.randomUUID(),activity:activityName,planned:plannedNumber,unit,remarks:remarks.trim()})}
 return <BottomSheet open={open} mobileTall title={current?"Edit Planned Activity":"Add Planned Activity"} description="Plan work for tomorrow." onClose={onClose}><form onSubmit={save} noValidate className="min-w-0 px-4 pt-5 sm:px-5">
  <div className="block min-w-0"><span className="mb-2 block text-[14px] font-bold">What are you planning tomorrow? <span className="text-[#e14d48]">*</span></span><MobileOptionPicker label="Tomorrow's activity" value={activity} options={options} onChange={changeActivity} error={errors.activity} icon={<CalendarDays size={19} className="text-[#e34c47]"/>}/></div>
  {activity==="Other"&&<motion.label initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} className="mt-4 block"><span className="mb-2 block text-[13px] font-semibold">Activity name <span className="text-[#e14d48]">*</span></span><input ref={customRef} value={custom} onChange={event=>{setCustom(event.target.value);clearError("activity")}} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();plannedRef.current?.focus()}}} enterKeyHint="next" placeholder="Describe tomorrow’s activity" className={`h-13 w-full min-w-0 rounded-[14px] border px-4 text-[15px] outline-none focus:border-[#e14d48] ${errors.activity?"border-[#dc4742]":"border-[#dfe2e8]"}`}/>{errors.activity&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.activity}</span>}</motion.label>}
  <fieldset className="mt-5 min-w-0"><legend className="text-[14px] font-bold">Target quantity</legend><div className="mt-2 grid min-w-0 grid-cols-[minmax(0,1fr)_112px] gap-2.5"><label className="min-w-0"><span className="mb-2 block text-[12px] font-semibold text-[#676d7a]">Target <span className="text-[#e14d48]">*</span></span><input ref={plannedRef} value={planned} onChange={event=>{setPlanned(event.target.value);clearError("planned")}} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();unitRef.current?.focus()}}} enterKeyHint="next" inputMode="decimal" type="number" min="0" step="any" placeholder="0" className={`h-14 w-full min-w-0 rounded-[14px] border px-4 text-[21px] font-bold outline-none focus:border-[#e14d48] [appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none ${errors.planned?"border-[#dc4742]":"border-[#dfe2e8]"}`}/></label><label className="min-w-0"><span className="mb-2 block text-[12px] font-semibold text-[#676d7a]">Unit <span className="text-[#e14d48]">*</span></span><span className="relative block"><select ref={unitRef} value={unit} onChange={event=>{setUnit(event.target.value);clearError("unit")}} onKeyDown={event=>{if(event.key==="Enter"){event.preventDefault();noteRef.current?.focus()}}} className={`h-14 w-full min-w-0 appearance-none rounded-[14px] border bg-white px-3 pr-8 text-[15px] font-bold outline-none focus:border-[#e14d48] ${errors.unit?"border-[#dc4742]":"border-[#dfe2e8]"}`}><option value="">Select</option>{Array.from(new Set([...unitOptions,current?.unit].filter((value):value is string=>Boolean(value)))).map(option=><option key={option}>{option}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute right-2.5 top-1/2 -translate-y-1/2 text-[#687080]"/></span></label></div>{errors.planned&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.planned}</span>}{errors.unit&&<span className="mt-1.5 block text-[12px] font-medium text-[#c8403b]">{errors.unit}</span>}</fieldset>
  <label className="mt-5 block"><span className="mb-2 block text-[14px] font-bold">Note <span className="font-medium text-[#858a97]">(optional)</span></span><textarea ref={noteRef} value={remarks} maxLength={300} onChange={event=>setRemarks(event.target.value)} rows={2} placeholder="e.g. Complete before consultant inspection" className="w-full min-w-0 resize-none rounded-[14px] border border-[#dfe2e8] p-4 text-[15px] leading-6 outline-none focus:border-[#e14d48]"/><span className="mt-1 block text-right text-[11px] text-[#8b909d]">{remarks.length}/300</span></label>
  {activityName&&plannedNumber>0&&unit&&<motion.div initial={{opacity:0,y:4}} animate={{opacity:1,y:0}} aria-live="polite" className="mt-3 flex min-w-0 items-center gap-3 rounded-[15px] bg-[#f4f6f8] p-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-[#e34c47]"><Target size={18}/></span><span className="min-w-0"><strong className="block truncate text-[14px]">{activityName}</strong><span className="mt-0.5 block text-[12px] text-[#687080]">Target: {plannedNumber} {unit}</span>{remarks.trim()&&<span className="mt-0.5 block truncate text-[11px] text-[#8b909d]">{remarks.trim()}</span>}</span></motion.div>}
  <div className="sticky bottom-0 z-10 -mx-4 mt-3 border-t border-black/[.06] bg-white/96 px-4 pb-[calc(12px+env(safe-area-inset-bottom))] pt-3 backdrop-blur-xl sm:-mx-5 sm:px-5"><button type="submit" className="h-[54px] w-full rounded-[14px] bg-[#ed4f49] text-[16px] font-bold text-white shadow-[0_8px_18px_rgba(237,79,73,.18)] active:scale-[.98]">{current?"Save Changes":"Add Planned Activity"}</button></div>
 </form></BottomSheet>}
function ProgressRing({percent,completed,reduce}:{percent:number;completed:number;reduce:boolean}){const circumference=2*Math.PI*27;return <div className="relative grid size-[76px] shrink-0 place-items-center"><svg viewBox="0 0 68 68" className="size-[76px] -rotate-90" aria-hidden="true"><circle cx="34" cy="34" r="27" fill="none" stroke="#e5e8ed" strokeWidth="6"/><motion.circle cx="34" cy="34" r="27" fill="none" stroke="#ed4f49" strokeWidth="6" strokeLinecap="round" strokeDasharray={circumference} initial={reduce?false:{strokeDashoffset:circumference}} animate={{strokeDashoffset:circumference*(1-percent/100)}} transition={{duration:reduce?0:.7,ease}}/></svg><span className="absolute text-center"><strong className="block text-[16px] leading-none">{percent}%</strong><span className="mt-1 block text-[9px] text-[#7d8290]">{completed} of 5</span></span></div>}
